### ISSUE TITLE
Cannot run the colab notebook for version 2.1 

### ISSUE THREAD

**Issue by thhung** [camenduru/stable-diffusion-webui-colab#10]
I cannot get it run, get the following errors: 
```
Installing requirements for Web UI
Launching Web UI with arguments: --share --force-enable-xformers
Loading config from: /content/stable-diffusion-webui/models/Stable-diffusion/v2-1_768-ema-pruned.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Downloading: 100% 3.94G/3.94G [00:51<00:00, 77.1MB/s]
^C
```

**Comment by camenduru** [comment]
it is working now I did nothing 😋

**Comment by thhung** [comment]
I still have the same issue. Did you run Colab with high ram mode?

**Comment by camenduru** [comment]
are we talking about same thing right 🤔 https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_1_webui_colab.ipynb is working right now

**Comment by thhung** [comment]
Yes, we talk about the same thing. When this one loads the model, it consumes more than 12 GB RAM, and Colab supports only 12 GB. Do you have Pro accounts?

**Comment by camenduru** [comment]
I am testing with free account please use this command `!nvidia-smi` and please post here what it returns

```
Wed Dec 14 21:04:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    28W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by thhung** [comment]
I mean RAM not GPU RAM. In this picture below: 
![Screenshot 2022-12-14 223028](https://user-images.githubusercontent.com/25224297/207719148-7f65db65-a003-42c6-9ac2-911f7671a2f6.png)

**Comment by thhung** [comment]
I think it is broken on the Auto1111's repo. Normally they have an option for "low ram" but it doesn't work anymore.

**Comment by camenduru** [comment]
please run this command `!grep MemTotal /proc/meminfo`

![Screenshot 2022-12-15 004200](https://user-images.githubusercontent.com/54370274/207721099-2cecd310-1de0-4b5d-abc1-61299bc4d56c.jpg)

**Comment by thhung** [comment]
Interesting, I have the same size of RAM as you. Here is the output: 
`13297220 kB`

**Comment by thhung** [comment]
If I run the notebook from your github, no problem. If I run the cloned version of it, it crashes. Interesting bugs right there.

**Comment by camenduru** [comment]
is everything same with this repo

**Comment by thhung** [comment]
I tried ony with version 2.1. When I have time, I will try with the rest.
