### ISSUE TITLE
Extension Suggestion

### ISSUE THREAD

**Issue by SenaKaito** [camenduru/stable-diffusion-webui-colab#100]
Hii, nice work as always 💖💖
I have a suggestion for you about this extension.
It's upscaler for img2img called Ultimate SD Upscale, and I found that extension is far better than original one.

And here the link,
https://github.com/Coyote-A/ultimate-upscale-for-automatic1111

Maybe you have interest about this extension."
Thank you and have a nice day (〃￣︶￣)人(￣︶￣〃)

**Comment by camenduru** [comment]
Maybe later we can add it when the extension has more functionality.
