### ISSUE TITLE
Connection errored out everytime change model

### ISSUE THREAD

**Issue by zaviier** [camenduru/stable-diffusion-webui-colab#105]
I can't change another model and got the connection errored out.
some model work, and some models not. same with LoRA, etc..

there is no error log in colab. just showing ^C
example: 
```
Loading weights [3a17d0deff] from /content/stable-diffusion-webui/models/Stable-diffusion/ChilloutMix/chilloutmix_NiCkpt.ckpt
^C
```

when this happened, I need to re-run the instance again.

**Comment by camenduru** [comment]
tomorrow I will start converting models and put them here https://huggingface.co/cnet

**Comment by camenduru** [comment]
some models are not fitting the free colab vram 😐

**Comment by etherealxx** [comment]
maybe, that model is too big for google colab's 12GB ram. try to use lowram on the launch line
```
!python launch.py --share --xformers --enable-insecure-extension-access --lowram
```
if you still can't, then it just can't. Google colab (free) limitation.

**Comment by camenduru** [comment]
oh no 😐

**Comment by etherealxx** [comment]
yeah, i just noticed Chilloutmix isn't an unpruned model

**Comment by camenduru** [comment]
Today, we can switch models. I really don't know why hehe

![Screenshot 2023-02-25 125555](https://user-images.githubusercontent.com/54370274/221350872-81a81ab8-13e7-41dc-9f55-750af4ddee1b.png)

**Comment by camenduru** [comment]
thanks @Daviljoe193 ❤ now memory issue fixed 🥳

**Comment by camenduru** [comment]
🥳
![Screenshot 2023-02-25 140714](https://user-images.githubusercontent.com/54370274/221353773-a04a4b71-3e99-41ec-8b96-05ba5f9e99f1.png)
