### ISSUE TITLE
Suggestion add protogen 3.4

### ISSUE THREAD

**Issue by alvaromaltrain** [camenduru/stable-diffusion-webui-colab#107]
Hopefully they can add protogen 3.4

**Comment by camenduru** [comment]
@etherealxx, do you want to make a PR for that?

**Comment by etherealxx** [comment]
@camenduru done. I've tested the unpruned model, colab can handle that.

**Comment by camenduru** [comment]
thanks @etherealxx ❤ 

please use this https://github.dev/camenduru/stable-diffusion-webui-colab your ide adding some interesting things 😐

![Screenshot 2023-02-17 132255](https://user-images.githubusercontent.com/54370274/219618972-49d4937f-59a6-4700-bf8d-b63a27c04a3a.jpg)
![Screenshot 2023-02-17 132733](https://user-images.githubusercontent.com/54370274/219619367-851d8ddf-c91a-47a4-ba86-71acc0ccef6d.jpg)

**Comment by etherealxx** [comment]
Whoops sorry😅
