### ISSUE TITLE
etherportal for google drive

### ISSUE THREAD

**Issue by navarisun** [camenduru/stable-diffusion-webui-colab#108]
Hello, i managed to convert the etherportal to work with google drive, so no need to install everything everytime, but i have 2 problems i cannot solve:

1. the script generates 2 stable diffusion webui folders, so i have after that to move files manually from one folder to another,
2. there is error just before stable diffusion about to start about git commits 
3. `Cloning K-diffusion into repositories/k-diffusion...
Traceback (most recent call last):
  File "launch.py", line 360, in <module>
    prepare_environment()
  File "launch.py", line 302, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "launch.py", line 162, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', None, "Couldn't checkout {name}'s hash: {commithash}")
  File "launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout {name}'s hash: {commithash}.
Command: "git" -C "repositories/k-diffusion" checkout 5b3af030dd83e0297272d861c19477735d0317ec
Error code: 1
stdout: <empty>
stderr: error: Your local changes to the following files would be overwritten by checkout:
	train.py
Please commit your changes or stash them before you switch branches.
Aborting` 

can someone please help with this ? 

here is the link to my colab: [link](https://colab.research.google.com/drive/1xKF5R9U41xwTzHPj1hwr2LOjrvZVMZ0g?usp=sharing)

**Comment by etherealxx** [comment]
checking it rn, please wait.

**Comment by etherealxx** [comment]
@navarisun okay, i figured out things, sort of. While i don't recommend using my colab with your google drive, since i usually do important updates/adjustments on the colab. but i think you have a reason, so.

[I made this for you](https://github.com/etherealxx/etherportal-webui-colab/blob/master/etherportal-gdrive.ipynb). Let me know if that works.

**Comment by navarisun** [comment]
@etherealxx that worked great , thx so much for your help. 
i tried it with dreambooth and it only needs to !pip install fastapi so it can work with no problem. 

also for model download link its not working.

but this really saved me lot of time, thanks for great help

**Comment by etherealxx** [comment]
> !pip install fastapi so it can work with no problem.
> also for model download link its not working.

Oh really? Well, i'm gonna check that later. Maybe after i update the main repo to include more model. That thing is outdated af.

**Comment by navarisun** [comment]
i will look into updates and try to update the gdrive version also, but know i'm happy with that, its fastest than any other colab i tried

**Comment by navarisun** [comment]
by the way is there any process that you recommend for updating ? @etherealxx

**Comment by etherealxx** [comment]
> also for model download link its not working.

[Fixed](https://github.com/etherealxx/etherportal-webui-colab/blob/master/etherportal-gdrive.ipynb), i forgot to put close bracket lol.

**Comment by etherealxx** [comment]
@navarisun i've [updated](https://github.com/etherealxx/etherportal-webui-colab) the main notebook and the gdrive one, now include even more models🎉

**Comment by navarisun** [comment]
> @navarisun i've [updated](https://github.com/etherealxx/etherportal-webui-colab) the main notebook and the gdrive one, now include even more models🎉

Thx so much for your hard work.
