### ISSUE TITLE
Hires. fix not showing and makes endless loading/stuck

### ISSUE THREAD

**Issue by zaviier** [camenduru/stable-diffusion-webui-colab#109]
![Screenshot_9](https://user-images.githubusercontent.com/17984219/219645472-a92adbd5-9d3d-492b-bfcb-1476c574e4c4.png)

I have already waited like 10 min and nothing, there is no images, error logs or something. I can't event click generate, need to refresh.
help please..

**Comment by NUROISEA** [comment]
It usually happens if the image is too big for gradio (~4MB+) and of the console says its 100% then its on your Image Browser.

As I've experienced, refreshing is the only way of fixing not being able to generate :/

**Comment by etherealxx** [comment]
My go to is usually upscale by 1.25 or 1.5 on that reso. You can try to use v1.6 instead. Sometimes it works there.
