### ISSUE TITLE
Add GIGACHAD Diffusion Pruned

### ISSUE THREAD

**Issue by CypherpunkSamurai** [camenduru/stable-diffusion-webui-colab#11]
Please add GIGACHAD Diffusion Pruned

**Comment by camenduru** [comment]
please upload here https://huggingface.co

**Comment by CypherpunkSamurai** [comment]
> please upload here https://huggingface.co

https://huggingface.co/SpiteAnon/gigachad-diffusion

**Comment by CypherpunkSamurai** [comment]
Hmm... Your colab notebook just loads the model. Ok I'll make a PR.
