### ISSUE TITLE
[Feature request]: Colab merge?

### ISSUE THREAD

**Issue by acheong08** [camenduru/stable-diffusion-webui-colab#112]
Why have so many different Colabs rather than merging them all into one with a simple dropdown to choose the model? If there are other options, maybe other checkboxes? 

Just a suggestion, no need to take me seriously

**Comment by etherealxx** [comment]
[There's this community colab that does the thing](https://github.com/camenduru/stable-diffusion-webui-colab/tree/community). I think the repo owner has it's own reason to not do that.

**Comment by acheong08** [comment]
Got it. Thanks
