### ISSUE TITLE
🚨 For Colab Pro Users

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#116]
please change the xformers line with `!pip install -q xformers==0.0.16`

**Comment by machiavel23** [comment]
We have pre xformers everywhere now, it can  be closed

**Comment by AnlloXander** [comment]
How to close xformers?

**Comment by camenduru** [comment]
Hi @AnlloXander 👋 please try again maybe we fixed the xformeres issue with `!pip install -q xformers==0.0.16`
