### ISSUE TITLE
🚨 Contribution Guide

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#120]
#### Video Tutorial
https://www.youtube.com/watch?v=XdjOiZkS6PU

#### Please add the token if it exists
Example: papercut_diffusion_webui_colab (Use the tokens `PaperCut` in your prompts for the effect.)

If you joined our discord server https://discord.gg/k5BwmmvJJU, please tell me your discord username.

**Comment by Siddhanta19** [comment]
# Last Step :
- Create Pull Requests to **MAIN & 2.0** From your Custom Branches

**Comment by camenduru** [comment]
If you joined our discord server https://discord.gg/k5BwmmvJJU, please tell me your discord username.
