### ISSUE TITLE
how to use ControlNet for Human Pose?

### ISSUE THREAD

**Issue by mikojiy** [camenduru/stable-diffusion-webui-colab#123]
![Screenshot_14](https://user-images.githubusercontent.com/125805092/219948907-a5bc01b8-a892-4395-9e1d-eb9e4b00b5b7.png)

I got black screen everytime I tried to use Openpose. or am I doing it wrong?

**Comment by camenduru** [comment]
Hi @mikojiy 👋 which colab?

**Comment by mikojiy** [comment]
> 

stable_diffusion_1_5_webui_colab.ipynb

**Comment by mikojiy** [comment]
> Hi @mikojiy 👋 which colab?


stable_diffusion_1_5_webui_colab.ipynb

**Comment by camenduru** [comment]
please try again I tried working

![Screenshot 2023-02-19 164734](https://user-images.githubusercontent.com/54370274/219952338-72a92508-3f9b-42f5-af56-e1c4d5a56f11.png)
