### ISSUE TITLE
CivitAI - doesn't work

### ISSUE THREAD

**Issue by batblz** [camenduru/stable-diffusion-webui-colab#124]
I can't search for anything, it doesn't return any results, what can it be?

**Comment by camenduru** [comment]
Hi @batblz  👋 which colab?

**Comment by batblz** [comment]
> Hi @batblz 👋 which colab?

I tried counterfeit, but it didn't work.

**Comment by camenduru** [comment]
1.6 or 2.0

**Comment by camenduru** [comment]
please try again I tried working

![Screenshot 2023-02-19 165118](https://user-images.githubusercontent.com/54370274/219952561-301a569c-8889-46c2-b00f-dd70c26e7dc8.png)

**Comment by camenduru** [comment]
Please don't forget to select the version

![Screenshot 2023-02-19 171452](https://user-images.githubusercontent.com/54370274/219954354-7be1550e-956c-46c8-b35c-c26876be8765.png)

**Comment by batblz** [comment]
I can't get the style of this lora, could you test it for me if it's not a bother?

https://civitai.com/models/6638/samdoesarts-sam-yang-style-lora
