### ISSUE TITLE
Not working x-formers

### ISSUE THREAD

**Issue by bropines** [camenduru/stable-diffusion-webui-colab#13]
![image](https://user-images.githubusercontent.com/57861007/207455221-cd67ba55-dd6d-41ea-a23a-cad7904f0338.png)

**Comment by camenduru** [comment]
which notebook?

**Comment by bropines** [comment]
> which notebook?

https://colab.research.google.com/drive/1onqZiV3R5OsKgBNEknN51KRo0XdQ1LRO?authuser=2#scrollTo=hVTBpnp85uPu

This is my notebook, with some of your additions

**Comment by camenduru** [comment]
your code is using old xformers use this one `!pip install -q https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15.dev0+189828c.d20221207-cp38-cp38-linux_x86_64.whl`

also delete this two 

```
!sed -i -e 's/numpy==1.23.3/numpy==1.21.6/g' requirements_versions.txt
!sed -i -e 's/fairscale==0.4.9/fairscale==0.4.6/g' requirements_versions.txt
```

**Comment by camenduru** [comment]
please check this https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/anything_3_webui_colab.ipynb and update your code
