### ISSUE TITLE
little question

### ISSUE THREAD

**Issue by tranthai2k2** [camenduru/stable-diffusion-webui-colab#130]
![image](https://user-images.githubusercontent.com/97587560/220126548-0281734c-df35-4975-88b7-74435ff6f343.png)
i use new model and it requires this even though camenduru's colab model is great but when i try with what i am doing and think it works the result is a bit different from what i expected
this is the original photo taken from another colab model
![image](https://user-images.githubusercontent.com/97587560/220126855-3993abad-ba58-4295-8087-5b3b9ad854df.png)here i try with your colab model and the result
[![image](https://user-images.githubusercontent.com/97587560/220126712-931e06f6-28ae-467e-95f9-44307b8743f2.png)
](https://cdn.discordapp.com/attachments/1067493777100525579/1077223950175703131/00001-1203884183.png)and when i manually load it into the folder i think that works and as a result it doesn't work at all
![image](https://user-images.githubusercontent.com/97587560/220126312-e2f1d807-2880-4152-8a21-bc79dfc95b28.png)

**Comment by camenduru** [comment]
Hi @tranthai2k2 👋 please add images with `PNG Info` then we can regenerate the problem

**Comment by etherealxx** [comment]
could you also give us the link of the 'other colab' in question? By 'colab model' do you mean 'colab notebook'?

**Comment by tranthai2k2** [comment]
https://colab.research.google.com/drive/1wEa-tS10h4LlDykd87TF5zzpXIIQoCmq#scrollTo=8Uvqba0yKW7U
here i use it and the result is very different i am trying them again

**Comment by etherealxx** [comment]
> https://colab.research.google.com/drive/1wEa-tS10h4LlDykd87TF5zzpXIIQoCmq#scrollTo=8Uvqba0yKW7U here i use it and the result is very different i am trying them again

That colab notebook uses so many different optimization tool that might change the result of the image generated a little bit. This repo's colab use the standard auto1111 version with little to none customization, except some useful extension.

> and when i manually load it into the folder i think that works and as a result it doesn't work at all

Could you explain more about this?

**Comment by tranthai2k2** [comment]
![image](https://user-images.githubusercontent.com/97587560/220130763-b9352cb5-975a-45d4-badc-4c12684cd01f.png)
i go to the folder like the picture and download the file i got from that colab manual see if it works sadly it doesnt work
https://huggingface.co/guon/tn/resolve/main/4x-AnimeSharp.pth

**Comment by etherealxx** [comment]
So you mean you tried to use an upscaler, and the result of the same upscaler between that colab and this colab is different?

**Comment by tranthai2k2** [comment]
your manual doesn't have that upscaler and I don't know how to get it to your model so I'm trying to ask here it seems my question is off-topic sorry for that

**Comment by machiavel23** [comment]
By default most of camenduru's colabs d9n't download any vae, and it looks like a vae issue to me.

**Comment by 7108** [comment]
I agree, eyes looks different here

**Comment by Siddhanta19** [comment]
> your manual doesn't have that upscaler and I don't know how to get it to your model so I'm trying to ask here it seems my question is off-topic sorry for that

![883222f1-e7e6-4fa4 gradio live_-copy](https://user-images.githubusercontent.com/98449368/220261707-9f0f94c6-27f9-4a5a-ac93-2b0c2cdd10c2.png)


I would recommend you to try version 2.0 branch colabs. The default main collabs run old version of the automatic 111 app.
It's possible that some settings for high res fix could be different.

**Comment by etherealxx** [comment]
@Siddhanta19 i think he is using the v2.0, since there is a width/height swap button on his photo.

**Comment by tranthai2k2** [comment]
@etherealxx  @camenduru 
I tried using command like this to insert the model but it doesn't seem to work so how do I edit the command to make that file appear in this section
!wget https://huggingface.co/guon/tn/resolve/main/4x-AnimeSharp.pth -O /content/stable-diffusion-webui/models/RealESRGAN/4x-AnimeSharp.pth

![image](https://user-images.githubusercontent.com/97587560/220641923-f6c352cb-ac7a-4286-8799-2c3a9cd224fc.png)

**Comment by etherealxx** [comment]
@tranthai2k2 test this `!wget https://huggingface.co/guon/tn/resolve/main/4x-AnimeSharp.pth -O /content/stable-diffusion-webui/models/ESRGAN/4x-AnimeSharp.pth`

**Comment by machiavel23** [comment]
You might just need to refresh the ui. There's buttons to refresh models and LoRAs, but there's none for upscalers iirc.
