### ISSUE TITLE
Generating the image in duchaitenaiart_v1_1 

### ISSUE THREAD

**Issue by sungsite** [camenduru/stable-diffusion-webui-colab#139]
Whatever i put in the prompt it always generate the same image of a mosaic in duchaitenaiart_v1_1 
hoping for a fix <3
much love

**Comment by camenduru** [comment]
Hi @sungsite 👋 which model

DucHaitenAIart_v1.1a_emaonly.ckpt
DucHaitenAIart_v2.0-emaonly.safetensors
DucHaitenDarkside_v1.0.safetensors

**Comment by sungsite** [comment]
i'm not aware of what these are, i always run it on google collab
it's this one: 
https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/duchaitenaiart_v1_1_webui_colab.ipynb

**Comment by etherealxx** [comment]
> i'm not aware of what these are, i always run it on google collab it's this one: https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/duchaitenaiart_v1_1_webui_colab.ipynb

yes, but that colab contains three different models, do you never change the model ever on your colab session?

**Comment by etherealxx** [comment]
the default seems to be `DucHaitenAIart_v2.0-emaonly.safetensors`

**Comment by etherealxx** [comment]
@camenduru the mozaic confirmed for `DucHaitenAIart_v2.0-emaonly.safetensors`. Other models from that colab works fine.
![image](https://user-images.githubusercontent.com/64251396/220490807-d3230cc9-3f9b-4a53-a6c2-966ea2e11fff.png)

**Comment by camenduru** [comment]
thanks @etherealxx ❤ @sungsite thanks for the info ❤ please it try
