### ISSUE TITLE
FATAL: this function is for sm80, but was built for sm750

### ISSUE THREAD

**Issue by mavisyyc** [camenduru/stable-diffusion-webui-colab#142]
![图片](https://user-images.githubusercontent.com/99957407/220505238-e43d76ad-0352-49a0-a4d5-15f1970a0e74.png)
how can l slove this problem? thank you .

**Comment by mavisyyc** [comment]
linux server 3090, python 3.8.5,

**Comment by camenduru** [comment]
maybe `!pip install -pre xformers`

**Comment by mavisyyc** [comment]
> maybe `!pip install -pre xformers`

that works! thank you
