### ISSUE TITLE
Textual inversion training

### ISSUE THREAD

**Issue by Rudy34160** [camenduru/stable-diffusion-webui-colab#144]
Is it possible when running the Colab to specify the save path of certain folders? For example, I would like that during training, the "textual_inversion" folder be on my Google Drive, in order to recover all the subfolders (embeddings, images, loss, etc...) so as not to lose them when closing of the Notebook.
If it is not possible for certain specific folders, can we indicate that we want to install all the files on our own Google Drive?

**Comment by machiavel23** [comment]
On colab you can explore the virtual machine storage. On the left side of colab, you have a dropdown menu, just choose files.

**Comment by Rudy34160** [comment]
> On colab you can explore the virtual machine storage. On the left side of colab, you have a dropdown menu, just choose files.

Thanks for reply.

Yes, I know that.
But when I run a 5K training with recording every 50 steps, it quickly becomes complicated to download all the images and all the .pts one by one... And I haven't yet found how to download a complete file from Colab . 😄
Hence my question of whether I can change the location choices: FastBen's Colab (currently not working for what I'm doing) was saving files to Drive, so this must be possible I think.

**Comment by etherealxx** [comment]
@Rudy34160 isn't like, there's an option to change the output file location? What tool did you use for TI training? Monkeypatch's one? There's an option.

**Comment by Rudy34160** [comment]
> @Rudy34160 isn't like, there's an option to change the output file location? 
Maybe I didn't see it right, but I couldn't find a specific option for training output files.

**Comment by etherealxx** [comment]
> Maybe I didn't see it right, but I couldn't find a specific option for training output files.

can you screenshot the UI

**Comment by Rudy34160** [comment]
@etherealxx 
![image](https://user-images.githubusercontent.com/118270456/220685511-847ac059-a910-4350-821d-e71faf40df0a.png)

**Comment by etherealxx** [comment]
i mean, where do you train it? The training tab

**Comment by Rudy34160** [comment]
> i mean, where do you train it? The training tab

Yes

> sorry i'm working on other project, might be slow response.

No problem

**Comment by etherealxx** [comment]
> i mean, where do you train it? The training tab
well, i mean, screenshot the training tab😅

**Comment by camenduru** [comment]
HI @Rudy34160 👋 check this https://www.youtube.com/watch?v=zjeziAAKx-o
then this https://www.youtube.com/watch?v=2ityl_dNRNw
use gdrive path for input and output folders

**Comment by Rudy34160** [comment]
> HI @Rudy34160 👋 check this https://www.youtube.com/watch?v=zjeziAAKx-o use gdrive path for input and output folders


I had already searched on my side before asking the question and had already seen your video: This clearly indicates how to redirect the output of the images generated in the WebUI. But at no time does it specify how to redirect the outputs of the train tab...

**Comment by Rudy34160** [comment]
> > i mean, where do you train it? The training tab
> 
> well, i mean, screenshot the training tab😅

Sorry..
Classic trainig tab 🤔

![image](https://user-images.githubusercontent.com/118270456/220705503-a8a65466-daf3-4a65-ac03-3db5262865c8.png)

**Comment by etherealxx** [comment]
@Rudy34160 that log directory. change it to something like /content/drive/MyDrive/textual_inversion

**Comment by Rudy34160** [comment]
> /content/drive/MyDrive/textual_inversion

I love you ! 😂
