### ISSUE TITLE
Kohya's extension

### ISSUE THREAD

**Issue by Rudy34160** [camenduru/stable-diffusion-webui-colab#145]
It seems that when running the Notebook, the extension is installed correctly:

![image](https://user-images.githubusercontent.com/118270456/220634968-b9a3353e-d2eb-4725-9e1d-db0b83c4f6e0.png)

However, I can't find a tab to access Kohya's functions 🤔 Did I forget something?

**Comment by camenduru** [comment]
please use this already installed https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0
