### ISSUE TITLE
ERROR: xformers-0.0.15.dev0+189828c.d20221207-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by FurkanGozukara** [camenduru/stable-diffusion-webui-colab#15]
I am trying to run s.d on kaggle and it has this command script

!pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15.dev0+189828c.d20221207-cp38-cp38-linux_x86_64.whl

it is throwing this error

ERROR: xformers-0.0.15.dev0+189828c.d20221207-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

here full code and error

![image](https://user-images.githubusercontent.com/19240467/208107173-1f9aa0f5-ed74-48a9-a42b-b243b8898464.png)

```
 !pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
!pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15.dev0+189828c.d20221207-cp38-cp38-linux_x86_64.whl

!git clone https://github.com/camenduru/stable-diffusion-webui
%cd /kaggle/working/stable-diffusion-webui

!sed -i -e 's/numpy==1.23.3/numpy==1.21.6/g' requirements_versions.txt
!sed -i -e 's/fairscale==0.4.9/fairscale==0.4.6/g' requirements_versions.txt

!cp /kaggle/input/stable-diffusion-webui-kaggle/models/wd-v1-3-float32.ckpt /kaggle/working/stable-diffusion-webui/models/Stable-diffusion/wd-v1-3-float32.ckpt
!cp /kaggle/input/stable-diffusion-webui-kaggle/models/sd-v1-5-inpainting.ckpt /kaggle/working/stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt
!cp /kaggle/input/stable-diffusion-webui-kaggle/models/v1-5-pruned-emaonly.ckpt /kaggle/working/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
!cp /kaggle/input/stable-diffusion-webui-kaggle/models/moDi-v1-pruned.ckpt /kaggle/working/stable-diffusion-webui/models/Stable-diffusion/moDi-v1-pruned.ckpt
#!cp /kaggle/input/stable-diffusion-webui-kaggle/models/PaperCut_v1.ckpt /kaggle/working/stable-diffusion-webui/models/Stable-diffusion/PaperCut_v1.ckpt
    
!python launch.py --share --force-enable-xformers
```

**Comment by FurkanGozukara** [comment]
i tried this and it failed too : !pip wheel git+https://github.com/facebookresearch/xformers#egg=xformers

**Comment by camenduru** [comment]
you are using python 3.8 wheel with python 3.7 vm please try this https://www.kaggle.com/code/camenduru/stable-diffusion-webui-kaggle please also use with T4 

xformers for kaggle T4 
`!pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.14/xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl`
