### ISSUE TITLE
how to add Lora models on it?

### ISSUE THREAD

**Issue by seniorghser** [camenduru/stable-diffusion-webui-colab#153]

**Comment by camenduru** [comment]
Hi @seniorghser please watch https://www.youtube.com/watch?v=2VwqHN7HDMc

**Comment by seniorghser** [comment]
> Hi @seniorghser 👋 please watch https://www.youtube.com/watch?v=2VwqHN7HDMc
thank you very much for help.
but however later after the update ,i use the same way to load the lora again,but it seemed like it doesnt work any more..
is the online frame of stable diffusion updated?
anyway i hope to get some assistance again

**Comment by etherealxx** [comment]
@seniorghser you can join the [discord server](https://discord.gg/k5BwmmvJJU) for more help from the community😁
