### ISSUE TITLE
📕 How To Zip And Download Folders

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#159]
Tutorial video: https://www.youtube.com/watch?v=n2DGve9BFeM

`zip -r /content/outputs.zip /content/stable-diffusion-webui/outputs`

![Screenshot 2023-02-23 115006](https://user-images.githubusercontent.com/54370274/220860630-89d47d30-e4d0-4ca1-b80f-36e063ca635b.png)

**Comment by 7108** [comment]
try downloading bigger zip and itll show error multiple times or the downloading speed is terribley slow

**Comment by etherealxx** [comment]
> try downloading bigger zip and itll show error multiple times or the downloading speed is terribley slow

the fastest option is always, import your google drive and move the zip to your drive. Then download from the drive website.

**Comment by camenduru** [comment]
@7108 push big files to your 🤗 Hugging Face account
