### ISSUE TITLE
Colab Storage

### ISSUE THREAD

**Issue by Rudy34160** [camenduru/stable-diffusion-webui-colab#160]
Is the original script modifiable, in order to save part of my configuration (model and parameter) on my Drive during the installation of the notebook?

1. I would like to keep my settings once they are configured.
2. I may be able to save some time by not downloading the same files every time.

**Comment by etherealxx** [comment]
[you can use this instead](https://colab.research.google.com/github/etherealxx/etherportal-webui-colab/blob/master/etherportal-gdrive.ipynb). It's a bit janky currently, but the point of that colab is, it install the whole stable diffusion on your google drive. I recommend you use a brand new google account for this, unless you have the non free google drive account.

**Comment by Rudy34160** [comment]
@etherealxx Why a bit janky ? I can save my info and my settings, I can choose my model, etc... That's exactly what I'm looking for: Just give it a try now! 😉
_I recommend you use a brand new google account for this_ > To save space on my personal Gdrive ? 🤔

**Comment by etherealxx** [comment]
> To save space on my personal Gdrive ? 🤔

yes, because downloading models to your drive will fill up the capacity quickly.

**Comment by etherealxx** [comment]
However, i think currently camenduru (the owner of this repo) is working on his own implementation, so you can use his instead when it comes out.✌️

**Comment by Rudy34160** [comment]
> yes, because downloading 4G+ models to your drive will fill up the capacity quickly.


I already use a specific account and I only use SD v1.4 for the moment for my training. 😉

**Comment by camenduru** [comment]
Hi @Rudy34160 👋 please try this https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive

**Comment by Rudy34160** [comment]
> Hi @Rudy34160 👋 please try this https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive

I have an error when I use "Run" Colab, after executing "One time install" Colab  :

![image](https://user-images.githubusercontent.com/118270456/221043132-1f7d4091-99ef-4240-af7a-52bc1f63907a.png)

😥
