### ISSUE TITLE
Kaggle Lora

### ISSUE THREAD

**Issue by myrzx** [camenduru/stable-diffusion-webui-colab#161]
kaggle版本没有加载Lora
在%cd /content/stable-diffusion-webui这一句上面加入：
!git clone https://github.com/kohya-ss/sd-webui-additional-networks /kaggle/working/stable-diffusion-webui/extensions/sd-webui-additional-networks
添加Lora的方式：
!wget https://civitai.com/api/download/models/14014 -O /kaggle/working/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/KoreanDollLikeness_v15.safetensors
找到lora文件的下载链接，然后用wget命令下载到webui里的Lora放模型的地方

**Comment by camenduru** [comment]
Hi @myrzx 👋 are you using this https://www.kaggle.com/code/camenduru/stable-diffusion-webui-kaggle

**Comment by camenduru** [comment]
Hi @myrzx 👋 please watch this https://www.youtube.com/watch?v=ovxve8tneCo
