### ISSUE TITLE
📕 How to install latest version and ControlNet to Google Drive

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#162]
Please select `drive` from `switch branches/tags`

![Screenshot 2023-02-23 165554](https://user-images.githubusercontent.com/54370274/220929669-c9580c92-da95-4f39-9229-6088ff2a5cd0.png)

https://www.youtube.com/watch?v=njW64feGMzI

**Comment by camenduru** [comment]
🚨 Important for 15G Free Google Drive Users: 

If you want to use more models, you can download your model into Colab, which has an empty 50GB space. 

Download models into `/content` and add `--ckpt-dir /content` at the end of the `launch.py` line

![Screenshot 2023-02-24 140103](https://user-images.githubusercontent.com/54370274/221163131-235a823e-4c0f-410e-935d-f870c0aab4bf.png)


thanks to twitter@muadoyoki ❤

**Comment by camenduru** [comment]
You can disable extension updates by adding the `#` character in front of the `git -C pull` line, like this:

![Screenshot_2023-03-03_185902](https://user-images.githubusercontent.com/54370274/222920272-8da07dbc-39e2-4bb1-8a9d-af59d65ea7c0.png)

 This means you will not receive extension updates and the startup time will be faster.

**Comment by yang-qing-fan** [comment]
hello，why it runs without launch.py



Status Legend:
(OK):download completed.
sed: can't read /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py: No such file or directory
sed: can't read /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py: No such file or directory
/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui
python3: can't open file '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/launch.py': [Errno 2] No such file or directory Installed
