### ISSUE TITLE
Install the WebUI Colab to Google Drive

### ISSUE THREAD

**Issue by Rudy34160** [camenduru/stable-diffusion-webui-colab#167]
I have an error when I use "Run" Colab, after executing "One time install" Colab :

![image](https://user-images.githubusercontent.com/118270456/221044031-f20b58ee-3f5b-429d-8112-39211425c237.png)

**Comment by camenduru** [comment]
Hi @Rudy34160 👋 please try again and tell us if it works

**Comment by Rudy34160** [comment]
> Hi @Rudy34160 👋 please try again and tell us if it works

The execution of the Webui seems to work: I'm testing a training session tomorrow morning and telling you if it works.

**Comment by Rudy34160** [comment]
Work in progress for training 🤗

However, OMG 😱?? I installed on a new account to start on a clean basis, is it normal that so much space is used? 🤔

![image](https://user-images.githubusercontent.com/118270456/221147524-4eaa6650-bf9e-4135-b700-f4ca9a96dd23.png)

**Comment by camenduru** [comment]
yep It makes sense if you buy 100GB of storage or more 😐

**Comment by Rudy34160** [comment]
Yes I know..

But it makes sense for me to be able to access all the data to analyze it and try to better understand the process of generating embeddings (loss, LR, inspect .pt, ...), to better create them after that. 
I collect all this information locally to analyze it quietly from my PC, so I basically don't need that much space, since each training session is a one shot.
Everyone finds an interest according to its use and the desired goal (and its financial means..). 😉

I was just surprised during the installation of the space used: On my previous Notebooks used (including that of FastBen, not to mention it ..), I do not remember such a heavy installation. But maybe there weren't as many options available.

That being said, it's still a great job: Thank you! 😘😋

**Comment by etherealxx** [comment]
> However, OMG 😱?? I installed on a new account to start on a clean basis, is it normal that so much space is used? 🤔

warned you😅

**Comment by camenduru** [comment]
you can download your models in colab (50GB empty) path like `/content/models` then 

`!python launch.py --share --xformers --enable-insecure-extension-access --gradio-queue --ckpt-dir /content/models`

**Comment by camenduru** [comment]
@Rudy34160 check this https://github.com/camenduru/stable-diffusion-webui-colab/issues/162#issuecomment-1443521514

**Comment by camenduru** [comment]
5.5GB ControlNet Models + 4GB Model = 1000000000GB 🤪

**Comment by Rudy34160** [comment]
> 5.5GB ControlNet Models + 4GB Model = 1000000000GB 🤪


I haven't looked into Controlnet enough yet, but to try, I think the Colab online will be enough for me for the moment.

**Comment by Rudy34160** [comment]
> @Rudy34160 check this [#162 (comment)](https://github.com/camenduru/stable-diffusion-webui-colab/issues/162#issuecomment-1443521514)

I don't understand... Everything was fine until I restarted a training session this afternoon. 🤔

![image](https://user-images.githubusercontent.com/118270456/221208951-4e09c476-2c3d-4b02-bd7e-8ab0e4318e6c.png)

However, I restarted the Notebook with some extensions disabled and the settings changed.

![image](https://user-images.githubusercontent.com/118270456/221209469-5ca930ad-aa46-4728-994e-b731db522977.png)
![image](https://user-images.githubusercontent.com/118270456/221209571-7441a632-8772-49bf-bac1-158cebba124c.png)

**Comment by etherealxx** [comment]
@Rudy34160 you want to train right? turn off every controlnet extension. Also using pruned 4GB models would decrease the chance of that out of memory error.

**Comment by Rudy34160** [comment]
> @Rudy34160 i suggest you turn off every controlnet extension. Also using pruned 4GB models would decrease the chance of that out of memory error.

Unfortunately not enough... 😔
And I'm using SD v1.4, not that heavy..

What I absolutely don't understand is that I haven't changed any settings since this morning when everything was working fine.. 🤔

![image](https://user-images.githubusercontent.com/118270456/221222372-1e9c3f87-be24-4605-911b-a4e59116b14b.png)
![image](https://user-images.githubusercontent.com/118270456/221222473-4973bb0b-98ee-4442-8b55-1b5f05866fe7.png)

**Comment by Rudy34160** [comment]
New test this morning

![image](https://user-images.githubusercontent.com/118270456/221356537-39ddd1e1-ef26-4872-a2c9-76cb6e429e43.png)

**Comment by etherealxx** [comment]
> New test this morning

a lot has going on today, from switching to cloudflare to fix for colab memory problem.

Do you use extension to train? Or purely from auto1111's webui?

**Comment by Rudy34160** [comment]
> a lot has going on today, from switching to cloudflare to fix for colab memory problem.

Only from A1111 for now.

Maybe because I haven't yet found any extensions that seemed essential to me..😄

**Comment by camenduru** [comment]
Hi @Rudy34160 please test again

**Comment by etherealxx** [comment]
> Only from A1111 for now.
> 

@Rudy34160 read [this](https://rentry.org/simplified-embed-training#heres-an-example-of-an-embed-i-fucked-up) (contains nsfw but it's a training tutorial). It uses monkeypatch extension. I tried several times and it worked flawlessly.

**Comment by Rudy34160** [comment]
Más que perfecto ! 😘

Just for my personal culture, this type of problem comes from what? 🤔

**Comment by etherealxx** [comment]
> Just for my personal culture, this type of problem comes from what? 🤔

idk man, auto1111 didn't really focus on the train tab anymore i think. That's why the extension exist.

**Comment by Rudy34160** [comment]
> idk man, auto1111 didn't really focus on the train tab anymore i think. That's why the extension exist.

What kind of extension ? 🤔
I lived in a cave for so long?😄

**Comment by etherealxx** [comment]
> What kind of extension ? 🤔 I lived in a cave for so long?😄

That link i gave you😅 everything is there. Read the tutorials.

**Comment by Rudy34160** [comment]
> That link i gave you😅 everything is there. Read the tutorials.

I must still be deep in my cave, I hadn't even seen your answer ! 🤣🤣

**Comment by etherealxx** [comment]
> I must still be deep in my cave, I hadn't even seen your answer ! 🤣🤣

@Rudy34160 scroll up
![image](https://user-images.githubusercontent.com/64251396/221368052-8a461a53-74b7-4c5d-84a5-11d2a2e4b513.png)
see that blue text?

**Comment by Rudy34160** [comment]
> @Rudy34160 scroll up ![image](https://user-images.githubusercontent.com/64251396/221368052-8a461a53-74b7-4c5d-84a5-11d2a2e4b513.png) see that blue text?

Yes, yes.. I'm a newbie, but not to that extent! 😁😂
I had already read this tut, more for the technique than for the extension. 
I will have to take a closer look at it to see the gains I can make with the textual inversions I want to do with real people.

**Comment by etherealxx** [comment]
I suggest you join the [discord channel](https://discord.gg/k5BwmmvJJU). Maybe we can talk more, or maybe other people can also help you.

**Comment by Rudy34160** [comment]
I think I declared victory too soon...

Error just now:

![image](https://user-images.githubusercontent.com/118270456/221374788-7da3d802-79f2-4f59-aa0b-7007f374b6fb.png)

**Comment by etherealxx** [comment]
> I think I declared victory too soon...
> 
> Error just now:
> 
> ![image](https://user-images.githubusercontent.com/118270456/221374788-7da3d802-79f2-4f59-aa0b-7007f374b6fb.png)

really though, i never get an error while training. Currently i'm busy, but hen i'm free i'll take a look on that.

**Comment by Rudy34160** [comment]
> really though, i never get an error while training. Currently i'm busy, but hen i'm free i'll take a look on that.

Can I bring my modest beginner's help to solve the problem?

**Comment by Rudy34160** [comment]
Seems to work today, but with the second link :

![image](https://user-images.githubusercontent.com/118270456/221561694-4b42667f-68af-46a5-b0bb-74502b13277d.png)
