### ISSUE TITLE
how to change the setting of Hires. fix

### ISSUE THREAD

**Issue by sky202203** [camenduru/stable-diffusion-webui-colab#168]
![2023-02-24 12 31 59](https://user-images.githubusercontent.com/122595656/221092471-fef50b1e-fdae-40e2-8765-6ffcc4cb39ef.png)

my web ui do not show the hires steps setting,
how can i  change the setting with hires steps

like this one
![2023-02-24 12 39 21](https://user-images.githubusercontent.com/122595656/221093137-ad6582b1-998f-4cb3-94cd-23ea9c8dad6f.png)

thank you

**Comment by NUROISEA** [comment]
Please use the [v2.0 branch](https://github.com/camenduru/stable-diffusion-webui-colab#how-to-use-latest-version-with-controlnet-)

**Comment by sky202203** [comment]
> Please use the [v2.0 branch](https://github.com/camenduru/stable-diffusion-webui-colab#how-to-use-latest-version-with-controlnet-)

ok, thank you
