### ISSUE TITLE
Can't train an embedding

### ISSUE THREAD

**Issue by NA-ID** [camenduru/stable-diffusion-webui-colab#17]
Hi! I'm getting this kind of error when trying to train an embedding
```
Training at rate of 0.005 until step 3000
Preparing dataset...
100% 156/156 [00:15<00:00, 10.04it/s]
  0% 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 328, in train_embedding
    loss = shared.sd_model(x, c)[0] / gradient_step
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 846, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 903, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```
TIA!

**Comment by camenduru** [comment]
thanks @NA-ID ❤ I will check

**Comment by camenduru** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3958#issuecomment-1331284615

**Comment by camenduru** [comment]
>Is there any method to make it start working on first launch?

hi @NA-ID  you can use like this 

`!sed -i -e '''/prepare_environment()/a\    os.system\(f\"""sed -i -e '' \"s/self.logvar\[t\]/self.logvar\[t.item()\]/g\" '' /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py""")''' /content/stable-diffusion-webui/launch.py`

**Comment by camenduru** [comment]
https://github.com/Stability-AI/stablediffusion/blob/d55bcd4d31d0316fcbdf552f2fd2628fdc812500/ldm/models/diffusion/ddpm.py#L903

`logvar_t = self.logvar[t].to(self.device)` to `logvar_t = self.logvar[t.item()].to(self.device)`

**Comment by camenduru** [comment]
https://github.com/Stability-AI/stablediffusion/pull/119

**Comment by camenduru** [comment]
example usage here
https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_1_5_webui_colab.ipynb
