### ISSUE TITLE
🚨 We switched Gradio Tunnel to Cloudflare Tunnel

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#172]
### This is why we switched to cloudflare 

- Cloudflare faster 
- Restart working with Cloudflare 
- Cloudflare has no timeout problem

https://user-images.githubusercontent.com/54370274/221298345-0e3a738a-927a-4b6d-8500-72c327731288.mp4

### Now our link appears here

![Screenshot 2023-02-25 160902](https://user-images.githubusercontent.com/54370274/221359994-2c4b1841-657e-4ddb-add0-bbf5d77d6cfd.png)

Thanks to @Bing-su's ❤️ sd-webui-tunnels extension, we now have four tunnels.

If you want to use GoogleUserContent Tunnel (HTTPS), simply add `--googleusercontent` to the end of the launch.py line
```py
For --googleusercontent if you are using v2.0 please remove the --gradio-queue if you are using v1.6 please remove 
!sed -i -e 's/default_enabled=False/default_enabled=True/' /content/stable-diffusion-webui/webui.py
```
![Screenshot 2023-02-26 043706](https://user-images.githubusercontent.com/54370274/221387648-fecdffa7-ae3b-4337-946d-59858e7644e0.png)

If you want to use Cloudflare Tunnel (HTTPS), simply add `--cloudflared` to the end of the launch.py line
![Screenshot 2023-02-26 015754](https://user-images.githubusercontent.com/54370274/221383507-8475079a-c047-4bef-b697-08d33884ec8d.png)

If you want to use LocalHostRun Tunnel (HTTP), simply add `--localhostrun` to the end of the launch.py line
![Screenshot 2023-02-26 015823](https://user-images.githubusercontent.com/54370274/221383509-2fb557e2-c639-4553-aef0-a1894a9c6f6f.png)

If you want to use RemoteMoe Tunnel (HTTP), simply add `--remotemoe` to the end of the launch.py line
![Screenshot 2023-02-26 015840](https://user-images.githubusercontent.com/54370274/221383511-44eec846-274a-4eda-8f1f-73efc1ac2ae1.png)

If you want to use Gradio Tunnel (HTTPS), simply add `--share` to the end of the launch.py line
![Screenshot 2023-02-26 015910](https://user-images.githubusercontent.com/54370274/221383512-9608d179-c408-409b-8ea5-48ac1b58ed8e.png)

**Comment by neon1978** [comment]
Thank you. This is a huge help.

**Comment by camenduru** [comment]
Thanks to Suyay2727 ❤ and TBMVD ❤ for the info, Now we can't switch models with this, I will fix it

**Comment by meefs** [comment]
Thank you!

**Comment by Falyn892** [comment]
controlnet?

**Comment by kengomj** [comment]
I m new on sd. How can I make the sd private although someone have the url? need to add something like auth?

**Comment by DeedgeMatrixGrafx** [comment]
Got that "A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type" error.

Tried putting the --no-half argument

Turn up with slower renders with blanks in the end.

I give up and wish everyone else who got their sessions running my blessings.

**Comment by etherealxx** [comment]
> I m new on sd. How can I make the sd private although someone have the url? need to add something like auth?

@kengomj add `-gradio-auth <yourusername:<yourpassword>`

**Comment by yesyeahvh123** [comment]
in v2.0, i see slower renders and blanks in the end, cant click generator button

**Comment by etherealxx** [comment]
@DeedgeMatrixGrafx @yesyeahvh123 the repo owner are currently resting🙏.
Would be nice if you guys open a new issue, then explains in detail about your problem. A screenshot and a copy of the console log text would be nice😁✨

**Comment by Metheenami** [comment]
Umm i have problem with this new update Gradio to Cloudflare.

When i do generate and image, it's proccessing so well until finished, then i can't see the generate image. 
I checked the generate image on imageBrowser, my generate image was there..

But when i want to generate for the second time. i pressing the generate button again and again, but didn't work at all. take a look my terminal, they don't process anything when i'm pressing generate button.

Hope someone can explain this and also maybe this is need to be fixed.

(Sorry my english so bad maybe)

**Comment by kengomj** [comment]
> -gradio-auth

thank you! perfect!

**Comment by camenduru** [comment]
HI @Metheenami 👋 are you using v2.0

**Comment by camenduru** [comment]
Hi @yesyeahvh123 👋 Hi @Metheenami 👋 Hi @DeedgeMatrixGrafx  👋 please try it again with v2.0 maybe it will works now

**Comment by Metheenami** [comment]
Hi.. i'm sorry, again when i'm running the server just now. i can't find the following link, example (https://organizations-golf-techrepublic-nano.trycloudflare.com) to open my stable diffusion web ui. i'm looking for the cloudflare as i know it must be my link to open my web ui on public

Terakhir kali sebelum pembaruan, itu ada di sana di tengah-tengah pelaksanaan proses terminal

**Comment by Cherryblossomoflove** [comment]
> Hi.. i'm sorry, again when i'm running the server just now. i can't find the following link, example (https://organizations-golf-techrepublic-nano.trycloudflare.com) to open my stable diffusion web ui. i'm looking for the "cloudflare" link as i know it must be my link to open my web ui on public
> 
> Last time before the update, it was there in the middle of executing the terminal process

Are you using 1.6 version or 2.0?

**Comment by Metheenami** [comment]
> > Hi.. i'm sorry, again when i'm running the server just now. i can't find the following link, example (https://organizations-golf-techrepublic-nano.trycloudflare.com) to open my stable diffusion web ui. i'm looking for the "cloudflare" link as i know it must be my link to open my web ui on public
> > Last time before the update, it was there in the middle of executing the terminal process
> 
> Are you using 1.6 version or 2.0?

version 1.6

**Comment by Cherryblossomoflove** [comment]
> > > Hi.. i'm sorry, again when i'm running the server just now. i can't find the following link, example (https://organizations-golf-techrepublic-nano.trycloudflare.com) to open my stable diffusion web ui. i'm looking for the "cloudflare" link as i know it must be my link to open my web ui on public
> > > Last time before the update, it was there in the middle of executing the terminal process
> > 
> > 
> > Are you using 1.6 version or 2.0?
> 
> version 1.6



> > > Hi.. i'm sorry, again when i'm running the server just now. i can't find the following link, example (https://organizations-golf-techrepublic-nano.trycloudflare.com) to open my stable diffusion web ui. i'm looking for the "cloudflare" link as i know it must be my link to open my web ui on public
> > > Last time before the update, it was there in the middle of executing the terminal process
> > 
> > 
> > Are you using 1.6 version or 2.0?
> 
> version 1.6, should i use version 2.0 instead?

yea it has the link

**Comment by Cherryblossomoflove** [comment]
I'm using 2.0 version and I see it

@Metheenami

**Comment by Metheenami** [comment]
> > > > Hi.. i'm sorry, again when i'm running the server just now. i can't find the following link, example (https://organizations-golf-techrepublic-nano.trycloudflare.com) to open my stable diffusion web ui. i'm looking for the "cloudflare" link as i know it must be my link to open my web ui on public
> > > > Last time before the update, it was there in the middle of executing the terminal process
> > > 
> > > 
> > > Are you using 1.6 version or 2.0?
> > 
> > 
> > version 1.6
> 
> > > > Hi.. i'm sorry, again when i'm running the server just now. i can't find the following link, example (https://organizations-golf-techrepublic-nano.trycloudflare.com) to open my stable diffusion web ui. i'm looking for the "cloudflare" link as i know it must be my link to open my web ui on public
> > > > Last time before the update, it was there in the middle of executing the terminal process
> > > 
> > > 
> > > Are you using 1.6 version or 2.0?
> > 
> > 
> > version 1.6, should i use version 2.0 instead?
> 
> yea it has the link

Got it!

**Comment by DeedgeMatrixGrafx** [comment]
> Got that "A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type" error.
> 
> Tried putting the --no-half argument
> 
> Turn up with slower renders with blanks in the end.
> 
> I give up and wish everyone else who got their sessions running my blessings.

It's working properly for me now. 
2.0 user by the way.

**Comment by Enferlain** [comment]
> in v2.0, i see slower renders and blanks in the end, cant click generate button

Same exact thing, but not in v2. Slower generation and bugged on the end with clicking on generate not doing anything, similar to before colabs switched to using gradio.

**Comment by camenduru** [comment]
Hi @Enferlain please try other tunnels

![Screenshot 2023-02-26 020641](https://user-images.githubusercontent.com/54370274/221385147-c30717cd-9e70-4a34-858b-2a9c01b7bb2a.png)

**Comment by Daviljoe193** [comment]
@Camenduru I just accidentally came across some functionality that Colab has built-in that can tunnel ports, just like Localtunnel/Ngrok/Cloudflared!

```
from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(7860)"))
```

Started with me noticing a random Colab notebook had this function called "google.colab.kernel.proxyPort", and after Google searching it, I found [this page](https://gist.github.com/arifsuhan/0566da9a3e0383a48643ba5dfb10cdc0).

**Comment by Semonxue** [comment]
It looks now the Cloudflare also will down sometime. I added following code before the last line (`!python launch.py ...`) to print out googleusercontent url , works well until now.

```
from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(7860)"))
```

**Comment by camenduru** [comment]
now we have --multiple tunnels at the same time 🥳 `cloudflared` and `remotemoe` and `gradio` and do not use gradio link we are getting ERROR: Exception in ASGI application

**Comment by muuua1004** [comment]
I use [sdxl-colab](https://github.com/camenduru/sdxl-colab), and can I use Cloudflare Tunnel too?
