### ISSUE TITLE
Having problem with colab notebook "set 'share=True' in 'launch()'"

### ISSUE THREAD

**Issue by JerryOver** [camenduru/stable-diffusion-webui-colab#174]
Thank you for creating these colab notebooks; they're awesome. I was using it yesterday with no problems, but today I can't get a public link. It tells me, "To create a public link, set 'share=True' in 'launch()'. I tried using "stable_diffusion_1_5_webui_colab" colab notebook and the one with ControlNet having the same issue. I included a picture of it.
![gergg](https://user-images.githubusercontent.com/120525455/221351082-c9287144-3591-4e12-943c-538574e2e1eb.png)

**Comment by camenduru** [comment]
HI @JerryOver 👋 please check this https://github.com/camenduru/stable-diffusion-webui-colab/issues/172

**Comment by camenduru** [comment]
we should make this more visible 

![221351082-c9287144-3591-4e12-943c-538574e2e1eb](https://user-images.githubusercontent.com/54370274/221351752-2cf89065-1153-48ca-9ee9-accc01dc19b7.png)

**Comment by camenduru** [comment]
Now link appears here

![Screenshot 2023-02-25 160902](https://user-images.githubusercontent.com/54370274/221360125-46e7125d-3469-432a-a038-86a1d8d2e6b1.png)

**Comment by Adiz2115** [comment]
![image_2023-02-25_203331699](https://user-images.githubusercontent.com/68333665/221364161-34c1ad8f-f152-48f6-b0a8-67a362186456.png)

ey dude, I've been using these colab notebooks for the past few days, and they are amazing. Thanks for your work, but now I'm facing a similar problem to the above one, difference being that im not able to find the above link either, I've attached a pic of it too.

**Comment by etherealxx** [comment]
> ey dude, I've been using these colab notebooks for the past few days, and they are amazing. Thanks for your work, but now I'm facing a similar problem to the above one, difference being that im not able to find the above link either, I've attached a pic of it too.

try to disconnect the colab, close the colab tab, and open it again. new update just dropped.

**Comment by JerryOver** [comment]
> Now link appears here
> 
> ![Screenshot 2023-02-25 160902](https://user-images.githubusercontent.com/54370274/221360125-46e7125d-3469-432a-a038-86a1d8d2e6b1.png)

It's working again! Thank you sir.
