### ISSUE TITLE
 Can't connect to Cloudflare Edge

### ISSUE THREAD

**Issue by MihaiWill** [camenduru/stable-diffusion-webui-colab#177]
i get this error when i am trying to run [sd1_5](https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_1_5_webui_colab.ipynb) in google colab
```
2023-02-25 20:38:07 (180 MB/s) - ‘/content/cloudflared-linux-amd64’ saved [36031373/36031373]

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "<ipython-input-2-cb7879bbaee9>", line 46, in cloudflared
Exception: Can't connect to Cloudflare Edge
```

**Comment by camenduru** [comment]
Hi @MihaiWill 👋 please add --share to the end of the launch.py line

![Screenshot 2023-02-25 183109](https://user-images.githubusercontent.com/54370274/221365563-7fb92294-02df-45bf-a2f0-41fa7a39f5a6.png)

**Comment by MihaiWill** [comment]
i still get the same error

**Comment by camenduru** [comment]
please try again now we have 3 options 

if `--cloudflared` not works delete `--cloudflared` add `--localhostrun`
if `--localhostrun` not works delete `--localhostrun` add `--remotemoe`

**Comment by MihaiWill** [comment]
`--localhostrun --share`  worked

thank you!

**Comment by etherealxx** [comment]
> `--localhostrun --share` worked

did you use it one by one or you use them both at the same time?

**Comment by MihaiWill** [comment]
Both at the same time

First time I used just  --localhostrun, but i couldn't access the UI on IP
address because it was local on google colab, of course, so with --share it
gaved me a working url

**Comment by camenduru** [comment]
please use only one at a time like this

![Screenshot 2023-02-26 020641](https://user-images.githubusercontent.com/54370274/221383784-7c492a2a-6545-4e88-93ec-f69b5aa58534.png)
