### ISSUE TITLE
v1.6 use lora always error

### ISSUE THREAD

**Issue by chenfgit** [camenduru/stable-diffusion-webui-colab#183]
When I use the lora function, it always goes wrong, and the error message is as follows:
LoRA weight: 0.5, model: Korean-Doll-Likeness(7fdca26d)
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 338, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 177, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 73, in create_network_and_apply_compvis
    network_dim = min([s for s in size if s > 1])
ValueError: min() arg is an empty sequence

**Comment by Enferlain** [comment]
Same

**Comment by camenduru** [comment]
I tested with 
https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/chillout_mix_webui_colab.ipynb
and this
https://civitai.com/models/7448/korean-doll-likeness

![Screenshot 2023-02-27 160242](https://user-images.githubusercontent.com/54370274/221570896-ca9663d2-fdab-47d6-a6f6-0c35ab664e02.png)

```py
<lora:koreanDollLikeness_v15:0.66>, best quality, ultra high res, (photorealistic:1.4), 1girl, beige sweater, smile, laughing, bare shoulders, solo focus, ((full body), (platinum pink hair:1), ((puffy eyes)), looking at viewer, facing front, closeup
Negative prompt: paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, glans
Size: 512x768, Seed: 1735215259, Model: chilloutmix_cilloutmixNi, Steps: 28, Sampler: DPM++ SDE Karras, CFG scale: 8, Model hash: 7234b76e42, Hires steps: 20, Hires upscale: 1.75, Hires upscaler: Latent (bicubic antialiased), Denoising strength: 0.5
```

![00002-1735215259-koreanDollLikeness_v15, best quality, ultra high res, (photorealistic_1 4), 1girl, beige sweater, smile, laughing, bare shoulder](https://user-images.githubusercontent.com/54370274/221570795-fc62b283-cc47-4f5a-8624-730046a44bcd.png)


I switched token from `<lora:koreanDollLikeness_v15:0.66>` to ` koreanDollLikeness_v15`

if you want use like this `<lora:koreanDollLikeness_v15:0.66>` please use v2.0 

https://github.com/camenduru/stable-diffusion-webui-colab/blob/v2.0/chillout_mix_webui_colab.ipynb
