### ISSUE TITLE
apply color correction to img2img results to match original colors error.

### ISSUE THREAD

**Issue by Asmedeus998** [camenduru/stable-diffusion-webui-colab#185]
I trying to add this parameter `, initial_noise_multiplier, img2img_color_correction` in `user interface` at settings and then restart the UI 

the following error show up after I check it at extensions get `error loop is closed`

![image](https://user-images.githubusercontent.com/60872999/221402111-95e2b0d2-24da-4c18-a30c-0ff3082a8045.png)

is there any alternative method to get Noise multiplier for img2img?

**Comment by etherealxx** [comment]
are you using the main/ v1.6 version? There's a chance that the feature isn't there yet. Try to use the v2.0 one.
