### ISSUE TITLE
[Bug]: Error loading script: ssh_tunnel.py

### ISSUE THREAD

**Issue by NUROISEA** [camenduru/stable-diffusion-webui-colab#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

any

### Which repo branch did the colab you use comes from ?

main (v1.6)

### Which tunnel did you use ?

--remotemoe

### What happened?

Try running any notebook after finishing setting up and trying to launch the error `Error loading script: ssh_tunnel.py` appears.

### Console logs

```Shell
Launching Web UI with arguments: --xformers --enable-insecure-extension-access --remotemoe
remote.moe detected, trying to connect...
Warning: Permanently added 'remote.moe,159.69.126.209' (ECDSA) to the list of known hosts.
Error loading script: ssh_tunnel.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/sd-webui-tunnels/scripts/ssh_tunnel.py", line 87, in <module>
    ssh_tunnel(REMOTE_MOE)
  File "/content/stable-diffusion-webui/extensions/sd-webui-tunnels/scripts/ssh_tunnel.py", line 73, in ssh_tunnel
    strings.en["PUBLIC_SHARE_TRUE"] = f"Public WebUI Colab URL: {tunnel_url.tunnel}\nPrivate WebUI Colab URL:{colab_url}"
AttributeError: 'str' object has no attribute 'tunnel'
```

**Comment by camenduru** [comment]
thanks @NUROISEA ❤ fixed please try again

**Comment by NUROISEA** [comment]
Thanks for the quick bug fix! ♥

Closing as completed now! :)
