### ISSUE TITLE
Can not train embedding nor hypertwork in sd 2.1

### ISSUE THREAD

**Issue by tomazf8** [camenduru/stable-diffusion-webui-colab#19]
sorry, i am new. i am in stable diffusion 2.1 and keep on getting Training finished at 0 steps.
Embedding saved to /content/stable-diffusion-webui/embeddings/snukymay.pt when I created embedings, preprocessed images and set trainng to motion.

images are uploaded to the directories of colab which I created.

the results on colab:
100% 10/10 [00:09<00:00,  1.03it/s]
Training at rate of 0.005 until step 1000
Preparing dataset...
100% 40/40 [00:02<00:00, 14.15it/s]
  0% 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 328, in train_embedding
    loss = shared.sd_model(x, c)[0] / gradient_step
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 846, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 903, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

Applying xformers cross attention optimization.

please help...

**Comment by SkyFryz24** [comment]
How to use other embedding? Is there a way to that

**Comment by camenduru** [comment]
example [here](https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_1_webui_colab.ipynb)

hi @SkyFryz24 👋 you can add like this 
```
!wget https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding/resolve/main/dblx.pt -O /content/stable-diffusion-webui/embeddings/dblx.pt
!wget https://huggingface.co/Conflictx/AnimeScreencap/resolve/main/AnimeScreenCap.pt -O /content/stable-diffusion-webui/embeddings/AnimeScreenCap.pt
```

**Comment by SkyFryz24** [comment]
> example [here](https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_1_webui_colab.ipynb)
> 
> hi @SkyFryz24 👋 you can add like this
> 
> ```
> !wget https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding/resolve/main/dblx.pt -O /content/stable-diffusion-webui/embeddings/dblx.pt
> !wget https://huggingface.co/Conflictx/AnimeScreencap/resolve/main/AnimeScreenCap.pt -O /content/stable-diffusion-webui/embeddings/AnimeScreenCap.pt
> ```

Thank you so much!!!

**Comment by camenduru** [comment]
hi @tomazf8 thanks for opening this issue ❤ now 🚂 is working 🎉 

https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_webui_colab.ipynb
