### ISSUE TITLE
Convert pytorch to Flax & Jax & TPU 

### ISSUE THREAD

**Issue by tralala87** [camenduru/stable-diffusion-webui-colab#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

Any possibility to make a tutorial or a colab how to convert any cuda / pytorch to run on flax / tpu?

### Which repo branch did the colab you use comes from ?

I don't know

### Which tunnel did you use ?

--cloudflared

### What happened?

Any possibility to make a tutorial or a colab how to convert any cuda / pytorch to run on flax / tpu?

### Console logs

```Shell
Any possibility to make a tutorial or a colab how to convert any cuda / pytorch to run on flax / tpu?
```

**Comment by camenduru** [comment]
Hi @tralala87 please try this https://github.com/camenduru/converter-colab
