### ISSUE TITLE
[Bug]: LoRA Error {min() arg is an empty sequence}

### ISSUE THREAD

**Issue by monsterdoc** [camenduru/stable-diffusion-webui-colab#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

Abyss Orange Mix 3

### Which repo branch did the colab you use comes from ?

main (v1.6)

### Which tunnel did you use ?

--cloudflared

### What happened?

While using the LoRAs (no matter which one) I receive error as you can see below. I have watched the video tutorial on YT (https://www.youtube.com/watch?v=2VwqHN7HDMc) so I'm sure that everything is done ok.
The same errors are generated when I tried to use Grapefruit model.

### Console logs

```Shell
LoRA weight: 0.7, model: ahegao_v1(79896a2f)
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 338, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 177, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 73, in create_network_and_apply_compvis
    network_dim = min([s for s in size if s > 1])
ValueError: min() arg is an empty sequence
```

**Comment by machiavel23** [comment]
That could be because it didn't updated the LoRA weight. Try Moving the weight slider instead of writing in the text field.

**Comment by BigColombian** [comment]
I am having the same issue. Using the slider to change the lora weight does not resolve the error.

**Comment by monsterdoc** [comment]
Can confirm @BigColombian - I'm also using sliders instead of writing the weight in the prompt and it's still causing that error. I also tried to add the weight in the prompt and match it with the slider but it's not working anyway. The strange fact is that I used the same LoRAs last week and everything worked fine.

**Comment by camenduru** [comment]
Hi @BigColombian 👋 Hi @monsterdoc 👋 please send the lora link and please try with this https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0

**Comment by machiavel23** [comment]
> Hi @BigColombian 👋 Hi @monsterdoc 👋 please send the lora link and please try with this https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0

It won't change anything. It's a gradio app issue, it just sucks at updating values.

**Comment by BigColombian** [comment]
> > Hi @BigColombian 👋 Hi @monsterdoc 👋 please send the lora link and please try with this https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0
> 
> It won't change anything. It's a gradio app issue, it just sucks at updating values.

Is there any sort of workaround?

**Comment by camenduru** [comment]
hi @monsterdoc I tested `LoRA weight: 0.7, model: ahegao_v1(79896a2f)` 

I got the same image. Please be sure that the model downloaded correctly.

![Screenshot 2023-03-02 212731](https://user-images.githubusercontent.com/54370274/222519346-95dc46d9-dab4-4b8e-b586-0f455986a473.png)

![Screenshot 2023-03-02 205435](https://user-images.githubusercontent.com/54370274/222519420-7af21499-ae42-495f-90ad-f079cdf3aa0b.png)
