### ISSUE TITLE
[Enhancement] adding a brief description of models in the table itself

### ISSUE THREAD

**Issue by Tanmay09516** [camenduru/stable-diffusion-webui-colab#199]
I feel there are so many models present it almost gets impossible to search through them, to make that better we can add a brief one liner description of the models such as
1. for mo_di_diffusion_webui_colab: model trained on screenshots from a popular animation studio. 
2. for arcane_diffusion_3_webui_colab: model trained on images from the TV Show Arcane.
3. for papercut_diffusion_webui_colab: model trained on Paper Cut images.
and so on.
I feel this would be an subtle but a greatly helpful feature for people who are new to all this. 
I would love to work on this issue!

**Comment by camenduru** [comment]
thanks @Tanmay09516 ❤ super good idea 🤩 also we can use your data in here https://github.com/camenduru/ai-creator-archive  UI https://aica.pages.dev/ 🥳

**Comment by camenduru** [comment]
If you are on Discord, we can open a channel for your idea and complete it together. I also want to generate images for each model.

**Comment by Tanmay09516** [comment]
Yes I am present there, I'll just ping you

**Comment by camenduru** [comment]
moved to discord
