### ISSUE TITLE
[ask] is there any reason to not use the non forked webui?

### ISSUE THREAD

**Issue by etherealxx** [camenduru/stable-diffusion-webui-colab#20]
How often will you update the forked one? And is there a special condition that determines "now it's time to update the fork"?
(anyway great repo, tysm, especially the custom built xformers)

**Comment by camenduru** [comment]
I usually wait a week and check for any major problems 🐜 in the main repo. If there are none, I sync. or If there is a cool feature, I test it and sync 🎉
