### ISSUE TITLE
🚨 Tensorflow /oneDNN/ Tensorflow compiler is not an issue

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#201]
We are using sed inside sed and sed inside sed can't see the feature  file then thinks this is an error 🤪 (time is relative 😋)

**Comment by etherealxx** [comment]
![image](https://user-images.githubusercontent.com/64251396/221920032-c901751c-4761-4fcf-bdad-bd9a3c7fceb1.png)
These things is also not an error

**Comment by camenduru** [comment]
My theory was wrong 🤪 this is a bug 🐛 oops 😋 sorry 😔 thanks to @NUROISEA ❤ for fixing it 🥳

**Comment by JinuMathers** [comment]
How to fix this?

**Comment by machiavel23** [comment]
> How to fix this?

Just use the colab from github, not the one you copies to your gdrive.

**Comment by camenduru** [comment]
thanks to https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information/42121886#42121886 ❤

`%env TF_CPP_MIN_LOG_LEVEL=1`
