### ISSUE TITLE
After I downloaded the model and opened the link, it kept loading

### ISSUE THREAD

**Issue by 000328** [camenduru/stable-diffusion-webui-colab#206]
<img width="1246" alt="截屏2023-03-02 11 03 01" src="https://user-images.githubusercontent.com/111692364/222320384-4671768a-5b34-452d-a3f3-1080f7f4534a.png">
After I downloaded the model and opened the link, it kept loading

**Comment by camenduru** [comment]
next time please click this button 

![Screenshot 2023-03-02 200040](https://user-images.githubusercontent.com/54370274/222499494-ab6bc538-1757-4648-bdb1-7daf11d527c9.png)
