### ISSUE TITLE
After I enabled ControlNet, It didn't work. 

### ISSUE THREAD

**Issue by clairelovesgravy** [camenduru/stable-diffusion-webui-colab#207]
### What happened?

It seems that I installed successfully, but when I generate a picture, I couldn't apply ControlNet.
![image](https://user-images.githubusercontent.com/32905744/222403013-6fd2b2c4-e00e-4c8e-a718-3ab40ee78a4d.png)

### Console logs

```Shell
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 612, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 471, in build_control_model
    network = network_module(
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 63, in __init__
    config = OmegaConf.load(config_path)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/omegaconf.py", line 187, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/stable-diffusion-webui/models/cldm_v15.yaml'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

stable_diffusion_1_5_webui_colab

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--cloudflared

**Comment by etherealxx** [comment]
@clairelovesgravy thanks for reporting. Try this command on the huggingface tab, run it:
```
wget -O /content/stable-diffusion-webui/models/cldm_v15.yaml https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/cldm_v15.yaml
```
and tell me what happened.

we will fix this soon

**Comment by IPv6** [comment]
Also hit this problem! With EIMIS problem.
Manual copy of /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/cldm_v15.yaml to '/content/stable-diffusion-webui/models/' fixed it

**Comment by clairelovesgravy** [comment]
But now I couldn't reproduce the situation...... I will do this once I run into the problem again.
Thanks~

**Comment by camenduru** [comment]
Hi @clairelovesgravy thanks for the info ❤ this was the problem https://github.com/Mikubill/sd-webui-controlnet/commit/38535ff17b3916d21562b10f897fc2efcfc1e65e
and 5 hours ago fixed https://github.com/Mikubill/sd-webui-controlnet/commit/9b19c63e9872e3dc059c07a592bbe83250e8ce79 thanks to @Mikubill ❤
