### ISSUE TITLE
🚨 Downloading models with CivitAi

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#209]
Please be sure that the model downloaded correctly.

Please `select all the drop-down menus until you see the download URL`.

![Screenshot 2023-03-02 205435](https://user-images.githubusercontent.com/54370274/222520531-c24e3e8b-4b6d-4d60-aa1b-12e2b9ba5e09.png)

Please make sure that the `Additional Networks` `Enabled` `model is selected` and that the `weight is not 0`

![Screenshot 2023-03-02 214025](https://user-images.githubusercontent.com/54370274/222521914-e0c1f5aa-0f1d-43ed-8f69-02c323529bb6.png)

If you want to use LoRA with auto this button please uncheck the `save LoRA to additional-networks`

![Screenshot 2023-03-04 003205](https://user-images.githubusercontent.com/54370274/222833321-dfc34de2-3eb3-44f2-96e1-6129747dcc97.png)

![Screenshot 2023-03-04 003034](https://user-images.githubusercontent.com/54370274/222833175-703d78de-4071-4dba-842f-14e0dcbdce35.png)

**Comment by FrisanBR** [comment]
the CIVITAI tab does not appear here

**Comment by guranu** [comment]
Get an error when trying to search for a model.

**Comment by keithhcyrus** [comment]
@guranu Elaborate on it so we can help.

**Comment by guranu** [comment]
> @guranu Elaborate on it so we can help.

Already fixed.

**Comment by AlphaEquities** [comment]
I cant download the model, whe I click "4th - Download Model" nothing happens
