### ISSUE TITLE
(memory?) issue with stable_diffusion_v2_1_webui_colab when mounting Google Drive

### ISSUE THREAD

**Issue by system1system2** [camenduru/stable-diffusion-webui-colab#21]
Hi. All your colab notebooks are amazing. Thanks for sharing them with the community. 

I have a problem with one of them: `stable_diffusion_v2_1_webui_colab`

If I create a new cell to mount my Google Drive and run it before your cell to initialize SD2.1, the initialization interrupts half way and I get this output:

> Python 3.8.16 (default, Dec  7 2022, 01:12:13) 
> [GCC 7.5.0]
> Commit hash: 4af3ca5393151d61363c30eef4965e694eeac15e
> Installing gfpgan
> Installing clip
> Installing open_clip
> Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
> Cloning Taming Transformers into repositories/taming-transformers...
> Cloning K-diffusion into repositories/k-diffusion...
> Cloning CodeFormer into repositories/CodeFormer...
> Cloning BLIP into repositories/BLIP...
> Installing requirements for CodeFormer
> Installing requirements for Web UI
> Launching Web UI with arguments: --share --force-enable-xformers
> No module 'xformers'. Proceeding without it.
> Cannot import xformers
> Traceback (most recent call last):
>   File "/content/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 18, in <module>
>     import xformers.ops
> ModuleNotFoundError: No module named 'xformers.ops'; 'xformers' is not a package
> 
> Loading config from: /content/stable-diffusion-webui/models/Stable-diffusion/v2-1_768-ema-pruned.yaml
> LatentDiffusion: Running in v-prediction mode
> DiffusionWrapper has 865.91 M params.
> Downloading: 100% 3.94G/3.94G [00:57<00:00, 69.0MB/s]
> ^C

I read that the `^C` interrupt might indicate the system has run out of memory.

If I do not run the cell that mounts Google Drive, everything works fine. 

Also, and this is where it's strange, if I run another of your Colab notebooks, like analog_diffusion_webui_colab, by running the cell that mounts Google Drive first, everything works fine, too.

**Comment by camenduru** [comment]
--force-enable-xformers obsolete please use --xformers

**Comment by camenduru** [comment]
wait it is not working with gdrive interesting 😋

**Comment by camenduru** [comment]
stable_diffusion_v2_1_webui_colab
| with gdrive (crashed) | without gdrive
| --- | --- |
![Screenshot 2022-12-29 144347](https://user-images.githubusercontent.com/54370274/209947191-0e01b66e-97f2-4d8c-851f-ee0112bc985f.jpg) | ![Screenshot 2022-12-29 144950](https://user-images.githubusercontent.com/54370274/209947193-67139c5d-8142-4f81-a7de-cc49aa4ed506.jpg)

stable_diffusion_1_5_webui_colab with gdrive
![Screenshot 2022-12-29 151319](https://user-images.githubusercontent.com/54370274/209949791-30d7d5ec-c079-4fb1-b3e7-84d1b20e6182.jpg)

stable_diffusion_v2_1 using too much system ram 
without gdrive working 
with gdrive and stable_diffusion_v2_1 not fitting the system ram 😨

**Comment by MitPitt** [comment]
Had the same problem, figured out a workaround fix — crash the colab right before launching the UI, this will free up the RAM

Do this after downloading the models:
```
import os
os.kill(os.getpid(), 9)
```
This will crash the runtime.
Now reconnect and run:
```
%cd /content/stable-diffusion-webui
!python launch.py --share --xformers
```

**Comment by camenduru** [comment]
thanks @MitPitt ❤ good idea 🤩

**Comment by MitPitt** [comment]
Google drive is taking RAM as well, I had this problem. You will have to download any needed files manually, without mounting the drive.
Use this command to download public files from google drive:
```
!curl -o train_images.zip -L 'https://drive.google.com/uc?export=download&confirm=yes&id=[ID]' # repalce ID
```
And you can find your file's ID by looking at the share link: ```https://drive.google.com/file/d/ABCDEFG/view?usp=share_link```
Here, the ID is ABCDEFG

**Comment by camenduru** [comment]
hi @system1system2 👋 I converted to fp16 now 2.58 GB please use this with gdrive

https://huggingface.co/ckpt/stable-diffusion-2-1/resolve/main/v2-1_768-ema-pruned-fp16.ckpt

**Comment by camenduru** [comment]
at this point, I am thinking that there may be a memory leak in the code 🤔

**Comment by MisoSpree** [comment]
Agree with all above.  I tried just installing the WebUI without connecting my drive.  It died the same death as described above.

`Launching Web UI with arguments: --share --xformers
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Loading config from: /content/stable-diffusion-webui/models/Stable-diffusion/768-v-ema.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Downloading: 100% 3.94G/3.94G [00:56<00:00, 69.6MB/s]
^C`

And I switched to this latest version because I can't fix the "RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)" on the older version that I used to be able to fix.  (Now, none of the suggested edits to the ddpm file work.) I would so dearly love to train more embeddings but I can't seem to find a version that runs for me on Colab (with a paid account.)

**Comment by thx-pw** [comment]
Forking and patching the stablediffusion repository of Stability-AI will bring it within 12 GB.
Here is a similar Issue.
(Translated at DeepL)

https://github.com/ddPn08/automatic1111-colab/issues/16
https://github.com/ddPn08/automatic1111-colab/commit/27484525d2aaf98b8ba75ce955dd553dc2eb3ab3

**Comment by camenduru** [comment]
@thx-pw さん、ありがとうございます。 ❤ ❤

**Comment by camenduru** [comment]
`!sed -i -e '''/prepare_environment()/a\    os.system\(f\"""sed -i -e ''\"s/dict()))/dict())).cuda()/g\"'' /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py""")''' /content/stable-diffusion-webui/launch.py`

**Comment by camenduru** [comment]
@thx-pwさん、こちらも動作しています `return get_obj_from_str(config["target"])(**config.get("params", dict())).cuda()`

**Comment by camenduru** [comment]
ご確認ください

**Comment by camenduru** [comment]
@system1system2 please try this https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_1_webui_colab.ipynb

**Comment by MisoSpree** [comment]
> @system1system2 please try this https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_1_webui_colab.ipynb

I am running.  So far, sed is throwing "no such file or directory" errors (for both sed calls).

**Comment by camenduru** [comment]
hi @MisoSpree 👋 sed is working we are getting this message because we are using sed inside sed before getting the file from repo little trick hehe 

```
sed: can't read /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py: No such file or directory
sed: can't read /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py: No such file or directory
```

**Comment by MisoSpree** [comment]
Roger that.  Ignoring error messages is right up my alley.

**Comment by MisoSpree** [comment]
Note that when training an embedding, the loss is reported as a NaN:

[Epoch 499: 10/10]loss: nan:  10% 4999/50000 [45:34<6:49:13,  1.83it/s]

And the image put out every N steps is just black.  Looks like something is broken still.

**Comment by camenduru** [comment]
oh no 😐

**Comment by ddPn08** [comment]
In my environment, I had no problem learning embedding.

**Comment by camenduru** [comment]
hi @ddPn08 can you train without black example output? please show us how

**Comment by camenduru** [comment]
I tried, and I also got a black output 😭

**Comment by ddPn08** [comment]
I created embedding from the train tab of AUTOMATIC1111 and trained without changing any settings.
I tested it on my notebook, so I'll try it on this one too.

**Comment by camenduru** [comment]
are you used this colab https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_1_webui_colab.ipynb

**Comment by MisoSpree** [comment]
> I tried, and I also got a black output 😭

I am glad I am not the only one.  Were you seeing loss reported as NaN?

**Comment by thx-pw** [comment]
Even after removing the low RAM patch, I am still getting the nan error in learning.
So I tried everything and when I changed from SD2.1 to WD1.4e1, the nan error was gone.
https://huggingface.co/hakurei/waifu-diffusion-v1-4/tree/main
I don't know why.

**Comment by camenduru** [comment]
I tested it this one and it worked with gdrive I didn't change anything maybe you are getting less ram I got 12.68GB
https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_1_webui_colab.ipynb
![Screenshot 2023-01-13 162026](https://user-images.githubusercontent.com/54370274/212329650-d1db9d9a-c568-4ef8-a759-660af26d2772.jpg)
