### ISSUE TITLE
Extensions problem

### ISSUE THREAD

**Issue by jabbasami** [camenduru/stable-diffusion-webui-colab#210]
### What happened?

Hello please, the extension installed not working, after i install an extension no matter which one,it doesn't work in 2.0 version nor in main version 

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

dreamlike diffusion 1.0

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--googleusercontent, --cloudflared, --localhostrun, --remotemoe, --share (Gradio Tunnel)

**Comment by camenduru** [comment]
Hi @jabbasami 👋 this extension ? https://github.com/Animator-Anon/animator_extension

**Comment by camenduru** [comment]
please join our discord for better communication https://discord.gg/k5BwmmvJJU
