### ISSUE TITLE
[Bug]: why civitai download to wrong file path?

### ISSUE THREAD

**Issue by jimys** [camenduru/stable-diffusion-webui-colab#213]
### What happened?

![13341677876627_ pic](https://user-images.githubusercontent.com/1137380/222830349-07b65fa1-7707-40ab-8269-a5e376e9a041.jpg)

![13351677876645_ pic](https://user-images.githubusercontent.com/1137380/222830375-c47258c1-4ab1-4c8c-af2c-d9d0ba6358b0.jpg)

lora loading folder is models/lora

but when I using civitai tab to download lora model,

it download to extensions/sd-webui-additional-networks/lora

why not just made civitai download to models/lora ?

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

stable_diffusion_1_5_webui_colab

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

**Comment by camenduru** [comment]
Hi @jimys we have a check box in the civitai extension please uncheck the `save LoRA to additional-networks`

**Comment by jimys** [comment]
oh, now I understand the additional network,

sorry for I using old version of webui before, so I don't know additional networks
