### ISSUE TITLE
无法加载显示输出内容所需的 JavaScript 文件。这可能是因为您的 Google 帐号登录权限已过期或您的浏览器不允许使用第三方 Cookie。请重新加载该页面。

### ISSUE THREAD

**Issue by AugustRush** [camenduru/stable-diffusion-webui-colab#214]
### What happened?

无法加载显示输出内容所需的 JavaScript 文件。这可能是因为您的 Google 帐号登录权限已过期或您的浏览器不允许使用第三方 Cookie。请重新加载该页面。

### Console logs

```Shell
无法加载显示输出内容所需的 JavaScript 文件。这可能是因为您的 Google 帐号登录权限已过期或您的浏览器不允许使用第三方 Cookie。请重新加载该页面。
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

xx

### Which repo branch did the colab you use comes from ?

community

### Which tunnel did you use ?

--cloudflared

**Comment by camenduru** [comment]
Hi @AugustRush 👋 请重新加载该页面。

**Comment by AugustRush** [comment]
加载了 没有作用 依然是这样的提示

**Comment by camenduru** [comment]
请发送一张截图。

**Comment by AugustRush** [comment]
我换其他的浏览器再试试

**Comment by ZJWDJCZ** [comment]
请问博主的问题解决了吗?我遇到了同样的问题，edge和chrome浏览器都是这样

**Comment by ZJWDJCZ** [comment]
> maybe proxy problem please check you proxy settings

太感谢你了！！！我试了好多种办法都不行，看了你的回答，换了一个vpn，然后问题解决啦！
