### ISSUE TITLE
why run.ipynb take so long time to run?

### ISSUE THREAD

**Issue by jimys** [camenduru/stable-diffusion-webui-colab#216]
### What happened?

thank you for the great work!

maybe I am wrong, I thought people install webui to Google drive,

it is because don't need to wait the download and initial every time before we run the webui,

I though after I install webui to Google drive,

then every time I run the run.ipynb,

the webui will be ready in seconds.

but now, the run.ipynb still takes minutes to run,

it's not much fast than the colab version,

so will this get improve?

thank you

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

run.ipynb

### Which repo branch did the colab you use comes from ?

drive

### Which tunnel did you use ?

--share (Gradio Tunnel)

**Comment by camenduru** [comment]
Hi @jimys because we are getting updates every day deforum and controlnet improve their code you can stop updates just adding `#` character before the `git pull` lines

**Comment by camenduru** [comment]
https://media.discordapp.net/attachments/1081243347735302204/1081244666441257023/Screenshot_2023-03-03_185902.png

**Comment by jimys** [comment]
thank you very much for your lightning speed reply, sorry for my English, hope you get it
