### ISSUE TITLE
Bug: Installing Deforum requirement: rich

### ISSUE THREAD

**Issue by yudiwardana2209** [camenduru/stable-diffusion-webui-colab#217]
the installation stuck in  "Installing Deforum requirement: rich" almost 30 minutes

**Comment by anuragrajput40904** [comment]
yes it is stuck on intalling webui requirements

**Comment by etherealxx** [comment]
@yudiwardana2209 @anuragrajput40904 is this new?

**Comment by mds-hopp** [comment]
yes, it's new. yesterday it still worked.

**Comment by etherealxx** [comment]
temporary fix is to not use deforum. add a hashtag in front of this line.
![image](https://user-images.githubusercontent.com/64251396/222897287-01b5f364-4ae4-4e9d-8dfb-4303f2666015.png)

we will figure out the fix soon

**Comment by machiavel23** [comment]
It's apparently solved, I runned a test 2 hours ago it worked fine
