### ISSUE TITLE
[Bug]: The restart interface shows that theConnection errored out.

### ISSUE THREAD

**Issue by L134139** [camenduru/stable-diffusion-webui-colab#218]
### What happened?

The restart interface shows that theConnection errored out.[](url)
![12](https://user-images.githubusercontent.com/51356527/222890366-7fa84374-9867-47a6-8ba4-ac7c34d2c7bc.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

7th laye

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--cloudflared

**Comment by etherealxx** [comment]
Do you have a more detailed explanation on what did you do before?

anyway, you can press the stop button on the colab menu, then press play again, it will refresh the webui session, and you can click on the newly generated link.

**Comment by machiavel23** [comment]
It's caused because cloudflare suck and is randomly down regularly. Just wait 1 minute and you'll be good
