### ISSUE TITLE
No module 'xformers'. Proceeding without it.

### ISSUE THREAD

**Issue by SiTu1O** [camenduru/stable-diffusion-webui-colab#22]
No module 'xformers'. Proceeding without it.
Cannot import xformers
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 18, in <module>
    import xformers.ops
ModuleNotFoundError: No module named 'xformers.ops'; 'xformers' is not a package

**Comment by camenduru** [comment]
--force-enable-xformers obsolete please use --xformers
