### ISSUE TITLE
请求做一个离线版的Drive版

### ISSUE THREAD

**Issue by jimys** [camenduru/stable-diffusion-webui-colab#223]
### What happened?

camenduru好像懂中文，那我中文表达可能清楚点，

我们用colab版的用久了，天天用日日用，每次打开下载将近10分钟才能干活真的很恼人，

而且每个帐号的免费时间过了之后，又得重新来一次十分钟开机下载，

好在有了Drive版，这个版的存在应该是让我们拥有PC版的方便吧，

之前camenduru让我注释掉git pull之后，确实开机时间缩短到了2分钟左右，

不过这只是不下载git pull的那些东西，

像webUI这些每次都要重新下，我理解camenduru说的controlnet之类的内容在每日更新，

结果就在那天，webUI居然没办法下载下来，等了几个小时才恢复，

我因为没实际装过PC版的stable diffusion，

我想象中PC版是不是任何时候在浏览器输入127.0.0.1就开始干活了？

真希望Drive版也能这么方便，
----------------------------
我的建议是希望install.ipynb能安装出一个离线就能运行的版本，
然后run.ipynb里可能就是一行代码直接启动stable diffusion，
Drive用户如果想更新了，再重新运行一次install.ipynb就好了。

camenduru您觉得呢？

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

run.ipynb

### Which repo branch did the colab you use comes from ?

drive

### Which tunnel did you use ?

--share (Gradio Tunnel)

**Comment by camenduru** [comment]
你好 @jimys 👋 好主意 🤩 我正在使用翻译器 😋 你有错误信息吗？如果有，请发送它。

**Comment by jimys** [comment]
Oh my god, so you don't understand Chinese, I am sorry,

All I want is made the drive version launch fast, don't update every time at launch,

I would like a stable and fast version for working, especially using it everyday more than 8 hours, and launching so many times a day.

if it git pull new version every time at launch, it would be slow and sometime more bugs,

if someone like newest version every time, just use the main or 2.0 version,

or reinstall the drive version it would be newest version.

**Comment by camenduru** [comment]
Hi @jimys 👋 now we have v1.9 and no updates are needed. I will convert to drive version like v2.0. are you using ControlNet?

**Comment by camenduru** [comment]
now install colab getting extensions updates thanks for the idea ❤ please try it

**Comment by jimys** [comment]
> Hi @jimys 👋 now we have v1.9 and no updates are needed. I will convert to drive version like v2.0. are you using ControlNet?

Yes, I am using ControlNet, 

it's too good to be true, I will try it! 

Thank you very much!
