### ISSUE TITLE
Unable to use Controlnet

### ISSUE THREAD

**Issue by duggie611** [camenduru/stable-diffusion-webui-colab#225]
### What happened?

Hi, I'm having a problem when trying to use Controlnet. I use the Openpose extension to create a skeleton for Controlnet. But whenever I use the Controlnet, it always generates a completely different pose image and a white image. I don't know why. Here are my settings for the Controlnet.
![1](https://user-images.githubusercontent.com/50878317/223139868-e1fb11ac-581a-47dc-9571-1cb132f84ba1.PNG)
![2](https://user-images.githubusercontent.com/50878317/223139882-967dced8-75e4-4215-b38c-35f0612133c2.PNG)
![3](https://user-images.githubusercontent.com/50878317/223139888-5bf36e2e-c04a-4edc-9819-417b723e9732.PNG)
In the third image, the image generated were always a girl sitting, not standing pose like the skeleton.

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

anything_4_webui_colab

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--cloudflared

**Comment by duggie611** [comment]
> did you try to set preprocessor to openpose?

I did not try it, but I think I had read from some guide and they said if using the skeleton then you don't need to use the preprocessor to openpose, if i remember correctly.

**Comment by camenduru** [comment]
Hi @duggie611 👋 what browsers do you use to access the webui ?

**Comment by duggie611** [comment]
Oh, I am using Brave browser.

**Comment by duggie611** [comment]
> Hi @duggie611 👋 what browsers do you use to access the webui ?

Oh, I am using Brave browser.

**Comment by camenduru** [comment]
We have multiple issues with the Brave browser. Please try another browser.

**Comment by duggie611** [comment]
> We have multiple issues with the Brave browser. Please try another browser.

Thank you for the answer, I'll try another browser.
