### ISSUE TITLE
[Bug]: The main model of CHECKPOINT TRAINED was downloaded, but the corresponding VAE could not be refreshed

### ISSUE THREAD

**Issue by LUKESkaywalker314** [camenduru/stable-diffusion-webui-colab#236]
### What happened?

The main model of CHECKPOINT TRAINED was downloaded, but the corresponding VAE could not be refreshed.How to solve this problem plz

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

a_certain_model_webui_colab.ipynb

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Microsoft Edge

**Comment by camenduru** [comment]
Hi @LUKESkaywalker314 👋 please send model and vae links
