### ISSUE TITLE
[Bug]: The problem of unavailability after ReloadUI

### ISSUE THREAD

**Issue by tyraut** [camenduru/stable-diffusion-webui-colab#238]
### What happened?

I'm trying to increase the number of contorlnet in the settings：
![image](https://user-images.githubusercontent.com/52126085/223606527-a86228ef-73f0-4732-8bb6-7d41a4d69339.png)
Then I clicked on ''apply setting''and''Reload UI''.After opening the new webui, 3 controlnets appear, but at this point the webui is not available.
![image](https://user-images.githubusercontent.com/52126085/223648020-758bccc4-484d-4983-a9ca-c945857a824f.png)
![image](https://user-images.githubusercontent.com/52126085/223648147-334e833a-eaff-4d06-8946-751ee364e102.png)
It does not generate images and the settings are not displayed.Even if I refresh the page it doesn't work, but I restart launch.py and it's back to normal.Virtually all webui has this problem with me

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

anything_4

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Microsoft Edge

**Comment by camenduru** [comment]
Hi @tyraut Gradio restart is a little problematic. Maybe the Gradio team will fix it soon. I will make a tutorial video about setting web UI configurations without restarting

**Comment by tyraut** [comment]
> Hi @tyraut 👋 Gradio restart is a little problematic. Maybe the Gradio team will fix it soon. I will make a tutorial video about setting web UI configurations without restarting

Okay, thank you for your work！
