### ISSUE TITLE
Can you update Lora's training tutorial?

### ISSUE THREAD

**Issue by sukbearsuwu** [camenduru/stable-diffusion-webui-colab#240]
### What happened?

Can you update Lora's training tutorial?

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

Can you update Lora's training tutorial?

### Which repo branch did the colab you use comes from ?

I don't know

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Microsoft Edge

**Comment by camenduru** [comment]
Hi @sukbearsuwu  👋 I will make a new tutorial very soon
