### ISSUE TITLE
[Bug]: The model cannot be loaded

### ISSUE THREAD

**Issue by L134139** [camenduru/stable-diffusion-webui-colab#241]
### What happened?

Why does Google Drive have a model, but it cannot be displayed on the loading model interface?
[](url)
![01](https://user-images.githubusercontent.com/51356527/223668823-364a0d80-747c-47ac-b11a-797a1b89fc97.png)
![02](https://user-images.githubusercontent.com/51356527/223668831-df9b0183-f5a7-461a-8e38-aa17fdada6f7.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

7th laye

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
Hi @L134139 👋 I tested and it is working  🥳 please add you model in this folder
```
/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Stable-diffusion
```
or use this tool `Add Model`

https://github.com/camenduru/stable-diffusion-webui-colab/blob/drive/add.ipynb

![Screenshot 2023-03-08 132624](https://user-images.githubusercontent.com/54370274/223689457-a2b1c9cf-5226-485b-ad93-a02320710efd.jpg)
![Screenshot 2023-03-08 132911](https://user-images.githubusercontent.com/54370274/223689472-4c8cba01-9f02-4dcb-a201-61b6307960fc.jpg)

**Comment by L134139** [comment]
I uploaded the local model to Google Drive /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Stable-diffusion  But the model loading interface does not have this mod
![03](https://user-images.githubusercontent.com/51356527/223699749-6ed37791-181a-47e1-9760-c3eeb6561c28.png)
![01](https://user-images.githubusercontent.com/51356527/223699812-14467e1d-417b-4a19-9e2d-7d4c5e6c8c26.png)
