### ISSUE TITLE
Having problem with multi controlnet

### ISSUE THREAD

**Issue by JerryOver** [camenduru/stable-diffusion-webui-colab#242]
I have been using multi-controlnet with v2.0 with no issue, but today, I was using 5 simultaneously but didn't work right. The resulting picture only used the the first control net. I knew this because it would show only two pictures: the resulting image and the canny picture, I looked at the runtime window, and it did seem to process the other multiple control nets but the resulting pictures from the other interface said otherwise. I even triple checked to see if I checked all the "enable" boxes, and I did. I even terminated the session and began a new, but the same result. Perhaps this is a temporary issue that you would have remedied, but I thought I would bring it to your attention. Thanks.

**Comment by camenduru** [comment]
Hi @JerryOver 👋 if the prompt has more than 75 tokens (words) maybe it won't work.

**Comment by JerryOver** [comment]
I actually did check that. The prompt was less than 75 words, but even when it was working before, I never checked. This has been the first time the multicontrolnet didn't work at all.

**Comment by camenduru** [comment]
Is there a similar issue here? https://github.com/Mikubill/sd-webui-controlnet/issues

**Comment by JerryOver** [comment]
Thanks Camenduru, it appears to be working again. Next time I have this problem, I'll make the issue with Mikubill. It was probably from their end any way.
