### ISSUE TITLE
[Feature Request]: Addition of Perfect World CivitAI model 

### ISSUE THREAD

**Issue by Necrozma200** [camenduru/stable-diffusion-webui-colab#247]
Link for Model: https://civitai.com/models/8281/perfect-world
If someone can guide me on how to do this for collab, I'll do it myself and make a pull request adding the desired model.
Thanks

**Comment by etherealxx** [comment]
@Necrozma200 this is the guide: https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/CONTRIBUTING.md
