### ISSUE TITLE
[Bug]: lora can't load

### ISSUE THREAD

**Issue by L134139** [camenduru/stable-diffusion-webui-colab#249]
### What happened?

I uploaded the lora model of the local computer to the Google hard drive content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Lora, but it was displayed on the Lora loading interface
![04](https://user-images.githubusercontent.com/51356527/223990402-66f035dc-046d-4971-a1d5-176843b42049.png)
![05](https://user-images.githubusercontent.com/51356527/223990408-9b1119e9-5c75-4a99-9c24-5ee9c06db5b1.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

7th layer

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by sukbearsuwu** [comment]
试试drive，这个可以没问题

**Comment by camenduru** [comment]
Hi @L134139 👋 If you are still experiencing the same problem, please reopen this issue
