### ISSUE TITLE
Kaggle issue

### ISSUE THREAD

**Issue by KamalAjamal** [camenduru/stable-diffusion-webui-colab#25]
`
Installing requirements for Web UI
Traceback (most recent call last):
  File "launch.py", line 294, in <module>
    prepare_environment()
  File "launch.py", line 246, in prepare_environment
    run_pip(f"install -r {requirements_file}", "requirements for Web UI")
  File "launch.py", line 78, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "/opt/conda/bin/python" -m pip install -r requirements_versions.txt --prefer-binary
Error code: 1
stdout: <empty>
stderr: ERROR: Ignored the following versions that require a different python version: 2022 Requires-Python >=3.8,<4.0
ERROR: Could not find a version that satisfies the requirement blendmodes==2022 (from versions: 2020, 2020.1, 2020.2, 2020.2.1, 2020.2.2, 2020.3.0, 2021, 2021.1, 2021.2, 2021.3, 2021.3.1, 2021.3.2, 2021.3.3)
ERROR: No matching distribution found for blendmodes==2022
`

U have done a wonderful job so far, but I'm getting this ,..!! how do i overcome this error...

**Comment by camenduru** [comment]
which notebook is this?

**Comment by camenduru** [comment]
@KamalAjamal thanks for the issue ❤fixed please use latest version
