### ISSUE TITLE
[Bug]: unsupported ScalarType BFloat16

### ISSUE THREAD

**Issue by 4garfield** [camenduru/stable-diffusion-webui-colab#250]
### What happened?

I'm trying to load lora file through additional networks but failed due to BFloat16 unsupported

### Console logs

```Shell
Error running process_batch: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 216, in process_batch
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight_tenc, weight_unet, text_encoder, unet)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 131, in create_network_and_apply_compvis
    modules_alpha[lora_name] = float(value.detach().cpu().numpy())
TypeError: Got unsupported ScalarType BFloat16
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

chillout_mix_webui_colab

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by KenfoxDS** [comment]
https://github.com/kohya-ss/sd-webui-additional-networks/issues/80

**Comment by camenduru** [comment]
oh no 😐

**Comment by camenduru** [comment]
Hi @4garfield 👋 please send your lora model link 
`TypeError: Got unsupported ScalarType BFloat16` maybe your model trained for TPUs

**Comment by 4garfield** [comment]
> [kohya-ss/sd-webui-additional-networks#80](https://github.com/kohya-ss/sd-webui-additional-networks/issues/80)
> 
> Check out more here: [kohya-ss/sd-webui-additional-networks#127](https://github.com/kohya-ss/sd-webui-additional-networks/issues/127)

Thanks for your help, it's additional-networks extension issue. I fixed it by just copy lora files to models/Lora folder, and not using additiona-networks to load lora files

**Comment by camenduru** [comment]
thanks for the info @4garfield ❤
