### ISSUE TITLE
How do I save the model to Google Driver?

### ISSUE THREAD

**Issue by LUKESkaywalker314** [camenduru/stable-diffusion-webui-colab#255]
### What happened?

How to save the trained model to google drive? Otherwise, I have to re-download the corresponding model and adjust the parameters each time, which seems to take a bit of time.

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

a_certain_model_webui_colab.ipynb

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--localhostrun

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
Hi @LUKESkaywalker314 👋 please use this https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive
