### ISSUE TITLE
stable-diffusion-webui I can't use it now. Both 1.9 and 2.0 have bugs, and neither of them has sent a running chart.

### ISSUE THREAD

**Issue by w8988998ww** [camenduru/stable-diffusion-webui-colab#256]

**Comment by etherealxx** [comment]
### Please,

explain the bugs like how the template is supposed to be, so we can help you as much as we can, thank you🙏

**Comment by geekyouth** [comment]
![image](https://user-images.githubusercontent.com/12899262/224486964-e8260b5d-6897-46ee-b739-67356a88eec2.png)

### after install done, what is the webui URL ???

**Comment by etherealxx** [comment]
> ### after install done, what is the webui URL ???

![image](https://user-images.githubusercontent.com/64251396/224508726-1a043a51-ef0f-4731-be7e-9cfd9777ace4.png)

there's install and run. You just did the install one.
