### ISSUE TITLE
[Bug]: simple_lora_trainer.ipynb fails for other model

### ISSUE THREAD

**Issue by knittely** [camenduru/stable-diffusion-webui-colab#259]
### What happened?

I tried using the anything-v4 model for the **simple_lora_trainer.ipynb**

Following setup:
**model_url:** https://huggingface.co/andite/anything-v4.0/resolve/main/anything-v4.5-pruned.ckpt
**model_name:** anything-v4.5-pruned.ckpt
**root_path:** /content/drive/MyDrive/AI/training
**instance_prompt:** yua
**max_train_steps:** 1600

**Expected result:** Training
**Actual Result:** Exception 

Using the ACertainty default values, training worked fine.

**Suggestion:**
I looked at the code and found this line:
`!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M {model_url} -d /content/model -o ACertainty.ckpt`
which I assume should probably be (did not test)
`!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M {model_url} -d /content/model -o {model_name}`

### Console logs

```Shell
Unfortuantely I did not copy the console logs in time before closing the runtime.
If you need I can rerun it tomorrow and paste the logs.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

simple_lora_trainer.ipynb

### Which repo branch did the colab you use comes from ?

training

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
oops 😋 thanks @knittely ❤
