### ISSUE TITLE
can't run stable_diffusion_v2_1_webui in kaggle because it default still python 3.7

### ISSUE THREAD

**Issue by Asmedeus998** [camenduru/stable-diffusion-webui-colab#26]
hello camenduru thanks for the amazing notebook and I really appreciate it. I just wondering is there a way to run SD 2.1 in kaggle. 

here the error message when I try to run it on kaggle.

`Error code: 1
stdout: <empty>
stderr: ERROR: Ignored the following versions that require a different python version: 2022 Requires-Python >=3.8,<4.0
ERROR: Could not find a version that satisfies the requirement blendmodes==2022 (from versions: 2020, 2020.1, 2020.2, 2020.2.1, 2020.2.2, 2020.3.0, 2021, 2021.1, 2021.2, 2021.3, 2021.3.1, 2021.3.2, 2021.3.3)
ERROR: No matching distribution found for blendmodes==2022`

**Comment by camenduru** [comment]
maybe you are missing `-b v1.5` part `!git clone -b v1.5 https://github.com/camenduru/stable-diffusion-webui`

this is working code
```shell
!pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
!pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.14/xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl

!git clone -b v1.5 https://github.com/camenduru/stable-diffusion-webui
%cd /kaggle/working/stable-diffusion-webui

!sed -i -e 's/numpy==1.23.3/numpy==1.21.6/g' requirements_versions.txt
!sed -i -e 's/fairscale==0.4.9/fairscale==0.4.6/g' requirements_versions.txt

!wget https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-1_768-ema-pruned.ckpt -O /kaggle/working/stable-diffusion-webui/models/Stable-diffusion/v2-1_768-ema-pruned.ckpt
!wget https://raw.githubusercontent.com/Stability-AI/stablediffusion/main/configs/stable-diffusion/v2-inference-v.yaml -O /kaggle/working/stable-diffusion-webui/models/Stable-diffusion/v2-1_768-ema-pruned.yaml

!python launch.py --share --force-enable-xformers
```
