### ISSUE TITLE
[Bug]: CivitAi doesn't find models

### ISSUE THREAD

**Issue by tralala87** [camenduru/stable-diffusion-webui-colab#262]
### What happened?

Trying to search for a specific model from CivitAi by it's specific name in webui, but it can't be found, despite existing on the civitai website.

### Console logs

```Shell
CivitAi from webui can't find the following model: https://civitai.com/models/17277/realism-engine
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

SD_v2_1

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by etherealxx** [comment]
the database may not have been updated. If that's the case, use batchlinks downloader extension instead to download.✨
