### ISSUE TITLE
[Bug]: Ignore because weight is 0

### ISSUE THREAD

**Issue by sam5406** [camenduru/stable-diffusion-webui-colab#263]
### What happened?

I have suffering from this bug in all versions (main branch and drive branch of the Colab). I have download some saftensor from Civitai and try to add it into my additonal networks. And i set the rating of them into 0.2 or less than 1 but not 0. After generating the images, i find the console ignores my weighting and i have reopened and rerun the script for serval times and it still doesnt work whatever i am doing it in txtimg or img2img.  

Also, i have tried doing it in local colab, but this error still exist 

![螢幕擷取畫面 (25)](https://user-images.githubusercontent.com/76158404/224559510-2ba50d54-9339-43f0-b73d-8c5a96969812.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

chillout_mix_webui_colab

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--googleusercontent, --cloudflared, --remotemoe, --share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by MinovskyRickland** [comment]
I encountered the same issue as you did,there may be a few possible reasons: conflicts between the seed number and plugins in the controlnet.however eliminating some of the conditions, some LoRA models still fail to load and encounter errors. maybe try raising the threshold

**Comment by camenduru** [comment]
Hi @sam5406 👋 Hi @MinovskyRickland 👋 please check this https://github.com/kohya-ss/sd-webui-additional-networks/issues and try with `nightly` version maybe fixed. If you are still experiencing the same problem, please reopen this issue
