### ISSUE TITLE
[Bug]: cant' download images from webui

### ISSUE THREAD

**Issue by tralala87** [camenduru/stable-diffusion-webui-colab#264]
### What happened?

Can't download images generated in webui. I get `IndexError: list index out of range` error.

### Console logs

```Shell
Can't download images generated in webui. I get `IndexError: list index out of range` error.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

SD_v2_1

### Which repo branch did the colab you use comes from ?

v2.0

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by tralala87** [comment]
Actually, I can't download images from any model provided here, when I run the google colab webui.

**Comment by camenduru** [comment]
Hi @tralala87👋 maybe this is also fixed If you are still experiencing the same problem, please reopen this issue
