### ISSUE TITLE
[Bug]: Generate button not responsing in webui (img2img)

### ISSUE THREAD

**Issue by sam5406** [camenduru/stable-diffusion-webui-colab#265]
### What happened?

The Generate button is not responsing in webui (img2img). 
i can only use it when  i rerun or reopen the ui

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

chillout_mix_webui_colab

### Which repo branch did the colab you use comes from ?

v2.0, drive

### Which tunnel did you use ?

--googleusercontent, --cloudflared, --remotemoe, --share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by etherealxx** [comment]
i think the resolution you use is too high? There's a limit on using resolution in colab before it starts to desync

**Comment by camenduru** [comment]
Hi @sam5406 👋 please try the etherealxx solution. If you are still experiencing the same problem, please reopen this issue
