### ISSUE TITLE
Error when trying to training embedding

### ISSUE THREAD

**Issue by cdefghijkl** [camenduru/stable-diffusion-webui-colab#27]
It's a known error when trying to training embedding. How to solve this is by add a line of code to ddpm.py or just run this code after stopping auto1111 after loading:
```
!sed -i '/logvar_t = self.*/i \ \ \ \ \ \ \ \ self.logvar = self.logvar.to(self.device)' /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py
```

![Screenshot 2023-01-02 at 14-12-53 Google Colaboratory](https://user-images.githubusercontent.com/121331850/210203022-050cbf0a-f2d0-43df-afff-ade52d5ebbd2.png)

**Comment by camenduru** [comment]
check this example https://github.com/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_1_5_webui_colab.ipynb

**Comment by camenduru** [comment]
also you can check this https://github.com/camenduru/stable-diffusion-webui-colab/issues/17

**Comment by cdefghijkl** [comment]
OK got it.
