### ISSUE TITLE
👻 [Bug]: ScuNET upscaler is missing again

### ISSUE THREAD

**Issue by xyzzart** [camenduru/stable-diffusion-webui-colab#272]
### What happened?

Why the ScuNET Gan is not in a list today? Yesterday was trying out different model colabs and it was there. Today its gone again/ something buggy with that upscaler? Is there any way to add it manually? (When using it for the first time this code shows up in colab console :
Downloading: "https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth" to /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

stable-diffusion-webui-colab/v2.0/illuminati_v1_1_webui_colab.ipynb

### Which repo branch did the colab you use comes from ?

lite, stable, nightly

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by etherealxx** [comment]
run this on huggingface tab
```
wget https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth -O /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth
```
or run this from the batchlinks tab
```
!wget https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth -O /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth
```

**Comment by xyzzart** [comment]
> run this on huggingface tab
> 
> ```
> wget https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth -O /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth
> ```
> 
> or run this from the batchlinks tab
> 
> ```
> !wget https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth -O /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth
> ```

thank you for reply. but i dont get it how to download it inside google colab/ can i just put the code into batchlink downloader? sorry for such nooby questions :/

**Comment by etherealxx** [comment]
@xyzzart yes just put this on batchlinks and press download all
```
!wget https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth -O /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth
```

**Comment by xyzzart** [comment]
> or run this from the batchlinks tab
> 
> ```
> !wget https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth -O /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth
> ```

tried it. and it just installed it into extensions folder. it have to be in a models folder

**Comment by etherealxx** [comment]
> tried it. and it just installed it into extensions folder. it have to be in a models folder

really? huh, that's weird. It should've downloaded into models folder. try this then
```
!mkdir /content/stable-diffusion-webui/models/ScuNET
!wget https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth -O /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth
```

**Comment by xyzzart** [comment]
> > tried it. and it just installed it into extensions folder. it have to be in a models folder
> 
> really? huh, that's weird. It should've downloaded into models folder. try this then
> 
> ```
> !mkdir /content/stable-diffusion-webui/models/ScuNET
> !wget https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth -O /content/stable-diffusion-webui/models/ScuNET/ScuNET.pth
> ```

can u please check your discord inbox

**Comment by camenduru** [comment]
If you are still experiencing the same problem, please reopen this issue.

**Comment by etherealxx** [comment]
@camenduru yes he still has the problem, and i told him to ask you yesterday, but haven't asked you since.

@xyzzart go ask him. Maybe here or on the discord server.

**Comment by camenduru** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/ScuNET/scripts/scunet_model.py
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/ScuNET/preload.py

**Comment by camenduru** [comment]
![image](https://user-images.githubusercontent.com/54370274/225512965-c75ebc1e-da25-461b-a70e-cde2ff3df6c5.png)

**Comment by xyzzart** [comment]
thanx a lot! after your last update... the ScuNET is on a list 

> from https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/lite/refslave_v2_webui_colab.ipynb ![image](https://user-images.githubusercontent.com/54370274/225512965-c75ebc1e-da25-461b-a70e-cde2ff3df6c5.png) ScuNET GAN ScuNET PSNR

**Comment by xyzzart** [comment]
> https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/ScuNET/scripts/scunet_model.py https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/ScuNET/preload.py

hello there! the issue with the scunet upscaler seems like repeating every time(

**Comment by camenduru** [comment]
I can’t find anything about why this is happening. Maybe there are ghosts in the internet. idk 👻👻👻 lets wait maybe someone figured it out

**Comment by xyzzart** [comment]
why illuminati?!

**Comment by xyzzart** [comment]
> I can’t find anything about why this is happening. Maybe there are ghosts in the internet. idk 👻👻👻 lets wait maybe someone figured it out

why illuminati?!

**Comment by camenduru** [comment]
looks like this maybe fixed with new version
