### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by w8988998ww** [camenduru/stable-diffusion-webui-colab#275]

**Comment by etherealxx** [comment]
stable-diffusion-colab1.9，Compact version,I've tried the stable version.，stable-diffusion-colab2.0，I used them all once, but 1006 will appear later. I don't know why....ERROR: Exception in ASGI ap。11Traceback (most recent call laFile"/usr/local/lib/python3result = await self.app(seFile"/usr/local/lib/python3return await self.app(scopeFile"/usr/local/lib/python3await super().___call___(scoFile"/usr/local/lib/python3await self.middleware_stacFile"/usr/local/lib/python3await self.app(scope, receFile"/usr/local/lib/python3await self.app(scope, receFile"/usr/local/lib/python3raise excFile"/usr/local/lib/python3await self.app(scope, receFile"/usr/local/lib/python3

**Comment by etherealxx** [comment]
@w8988998ww please rewrite your problem on the comment section like that

**Comment by camenduru** [comment]
#279

**Comment by camenduru** [comment]
Hi @w8988998ww  👋 are you still getting same error, If you are still experiencing the same problem, please reopen this issue.
