### ISSUE TITLE
I have problems with many versions today, and there will always be problems. The moderator will come in and have a look.

### ISSUE THREAD

**Issue by w8988998ww** [camenduru/stable-diffusion-webui-colab#276]
File"/usr/local/1ib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in _call await self.app(scope, receive, sender)
File "/uSr/1ocal/1ib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in ___cal] raise e
File"/usr/local/1ib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in___cal] await self.app(scope. receive. send)
File"/usr/1ocal/1ib/python3.9/dist-packages/starlette/routing.py", line 706, in __call await route.handle(scope, receive, send)
File"/usr/local/1ib/python3.9/dist-packages/starlette/routing.py", line 341, in handle await self.app(scope. receive. send)
File"/usr/local/lib/python3.9/dist-packages/starlette/routing.py",line 82, in app
await func(session)
File"/uSr/1ocal/1ib/python3.9/dist-packages/fastapi/routing.py",line 289, in app
await dependant.call(★*values)
File"/usr/local/lib/python3.9/dist-packages/gradio/routes.py",line 436, in join_queue session info = await websocket.receive ison()
File"/uST/1ocal/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json self._raise_on_disconnect(message)
File"/usr/local/1ib/python3.9/dist-packages/starlette/vebsockets.py", line 105, in _raise_on_disconn raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect;1001
ERROR: Exception in ASGI application
Traceback(most recent call last);
File"/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 25result = await self.app(self.scope, self,asgi receive, self.asgi_send)
File"/usr/local/1ib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py",line 78, in_call. return await self.app(scope, receive, send)
File"/usr/local/1ib/python3.9/dist-packages/fastapi/applications.py", line 271, in _call_ await super().call (scope. receive, send)
File"/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 125, in _call_ await self.middleware stack(scope, receive, send)
File"/usr/local/1ib/python3.9/dist-packages/starlette/middleware/errors.py", line 149, in __call await self.app(scope, receive, send)
File"/usr/local/1ib/python3.9/dist-packages/starlette/middleware/gzip.py", line 26, in__call__ await self.app(scope, receive, send)
File "/uSr/local/1ib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in ___call_ raise exc
File"/usr/local/1ib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in__call_ await self.app(scope. receive, sender)
File"/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in__cal] raise e
File"/usr/local/1ib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __cal] await self.aoo(scope. receive. send)
File"/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 706, in___call_ await route.handle(scope, receive, send)
File"/usr/local/1ib/python3.9/dist-packages/starlette/routing.py", line 341, in handle awaitself.app(scope, receive, send)
File"/usr/local/1ib/python3.9/dist-packages/starlette/routing.py", line 82, in app
await func(session)
File"/usr/local/1ib/python3.9/dist-packages/fastapi/routing.py", line 289, in app
await dependant,call(**values)
File"/usr/local/1ib/python3.9/dist-packages/gradio/routes.py", line 436, in join_queue session_info = await websocket.receive_json()
File"/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json self.raise_on_disconnect(message)
File"/usr/local/1ib/python3.9/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconne raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect:1006

**Comment by camenduru** [comment]
#279

**Comment by w8988998ww** [comment]
？

**Comment by w8988998ww** [comment]
What's the problem?

**Comment by camenduru** [comment]
Hi @w8988998ww 👋 are you still getting same error, If you are still experiencing the same problem, please reopen this issue.
