### ISSUE TITLE
🚧 Gradio Starlette ERROR: Exception in ASGI

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#279]
Maybe fixed idk yet

**Comment by camenduru** [comment]
pip install Starlette -U
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: Starlette in /usr/local/lib/python3.9/dist-packages (0.23.1)
Collecting Starlette
  Downloading starlette-0.26.1-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.9/66.9 KB 3.2 MB/s eta 0:00:00
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.9/dist-packages (from Starlette) (3.6.2)
Requirement already satisfied: typing-extensions>=3.10.0 in /usr/local/lib/python3.9/dist-packages (from Starlette) (4.5.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.9/dist-packages (from anyio<5,>=3.4.0->Starlette) (2.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.9/dist-packages (from anyio<5,>=3.4.0->Starlette) (1.3.0)
Installing collected packages: Starlette
  Attempting uninstall: Starlette
    Found existing installation: starlette 0.23.1
    Uninstalling starlette-0.23.1:
      Successfully uninstalled starlette-0.23.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.90.1 requires starlette<0.24.0,>=0.22.0, but you have starlette 0.26.1 which is incompatible.
Successfully installed Starlette-0.26.1
Name: starlette Version: 0.23.1 Summary: The little ASGI library that shines. Home-page: Author: Author-email: Tom Christie [tom@tomchristie.com](mailto:tom@tomchristie.com) License: Location: [/usr/local/lib/python3.9/dist-packages](https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/lite/mo_di_diffusion_webui_colab.ipynb#) Requires: anyio, typing-extensions Required-by: fastapi

**Comment by camenduru** [comment]
https://github.com/encode/starlette

**Comment by 7108** [comment]
We aren't coder, what's this?

**Comment by camenduru** [comment]
https://github.com/gradio-app/gradio/blob/226e87cd54a1b4cf0340955eac6bc709b6844c0e/gradio/routes.py#L37

**Comment by camenduru** [comment]
Hi @7108 👋 I am working on it 🚧

**Comment by camenduru** [comment]
https://github.com/search?q=Exception+in+ASGI&type=issues&s=updated&o=desc

**Comment by camenduru** [comment]
https://github.com/camenduru/stable-diffusion-webui-colab/releases/tag/0.0.17

**Comment by DonkeyBear** [comment]
I got the same error message when using another 2 links.

**Comment by camenduru** [comment]
Hi @DonkeyBear 👋 thanks for the info ❤ we are working on it

**Comment by sgoal** [comment]
![image](https://user-images.githubusercontent.com/5958865/225531310-2a37cc8f-89bb-4ea4-93c1-ee67db093631.png)
I can't open webui,becase missing index.js on gradio

**Comment by sgoal** [comment]
> Hi @DonkeyBear 👋 thanks for the info ❤ we are working on it

When I open public url,I got white screen.
![image](https://user-images.githubusercontent.com/5958865/225531829-fea0d4a7-a961-47ce-a4b6-a30220e6ded4.png)
![image](https://user-images.githubusercontent.com/5958865/225531884-7f943635-35d0-4f6b-87b4-981dba9346e0.png)

**Comment by camenduru** [comment]
thanks for the good info @sgoal ❤ those files should not come from gradio server 😐

```
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.ff9173a1.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.0cc64d4e.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.5a3337db.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.5e9bdb3b.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Tabs.4607aa1c.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Column.2d03a686.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.c2499812.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.853cecde.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.a57de80f.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.8e0ac58c.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.d619ae2e.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.3ba14455.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/BlockLabel.677b0876.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.92516eb3.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/File.99c9aa38.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Upload.660f83a6.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/ModifyUpload.cecce8cd.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/utils.27234e1d.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.9823b33a.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.2c06fbc1.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.2953baa5.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.0a2a3870.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.c55420bb.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.82581d10.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.e7e4d716.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.95a03248.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Image.8532565d.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.37f98688.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Webcam.df71ae73.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Image.6029e16a.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.e85382dc.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.e747f4e7.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.dc9bf9fe.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.12ae7510.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.2fdc9bcc.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/dsv.7fe76a93.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.1848fd6f.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.74401308.js
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/static/img/api-logo.svg
https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/logo.0a070fcf.svg
```

**Comment by camenduru** [comment]
https://github.com/camenduru/gradio/blob/b1b6841b7ec10a19df0f0d8f4daa797badabe190/ui/packages/app/build_plugins.ts#L20

**Comment by sgoal** [comment]
> thanks for the good info @sgoal ❤ those files should not come from gradio server 😐
> 
> ```
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.ff9173a1.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.0cc64d4e.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.5a3337db.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.5e9bdb3b.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Tabs.4607aa1c.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Column.2d03a686.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.c2499812.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.853cecde.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.a57de80f.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.8e0ac58c.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.d619ae2e.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.3ba14455.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/BlockLabel.677b0876.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.92516eb3.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/File.99c9aa38.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Upload.660f83a6.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/ModifyUpload.cecce8cd.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/utils.27234e1d.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.9823b33a.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.2c06fbc1.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.2953baa5.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.0a2a3870.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.c55420bb.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.82581d10.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.e7e4d716.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.95a03248.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Image.8532565d.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.37f98688.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Webcam.df71ae73.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/Image.6029e16a.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.e85382dc.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.e747f4e7.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.dc9bf9fe.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.12ae7510.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.2fdc9bcc.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/dsv.7fe76a93.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.1848fd6f.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/index.74401308.js
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/static/img/api-logo.svg
> https://gradio.s3-us-west-2.amazonaws.com/3.16.2/assets/logo.0a070fcf.svg
> ```

index.js is still missing 
![image](https://user-images.githubusercontent.com/5958865/225795890-bd51be0c-a3a6-4bce-b353-83609a245cec.png)

**Comment by camenduru** [comment]
Hi @sgoal 👋 we are not using gradio cdn, please update your code if you have --share argument please delete

**Comment by DonkeyBear** [comment]
> Maybe fixed idk yet

Using `remote.moe` and `cloudflared` URL right now, still got the same error.
The colab works, but WebUI will disconnect often, my workaround is stop it and run this again:
```
!python launch.py --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
```

**Comment by DonkeyBear** [comment]
> Hi @DonkeyBear 👋 please send the full error message here also please check if you have this line in your code
> 
> `!sed -i -e 's/fastapi==0.90.1/fastapi==0.89.1/g' /content/stable-diffusion-webui/requirements_versions.txt`

I'm sorry for replying so late.
I had never used WebUI colab since that day, until I used it again today, and it worked fine, without any error message.
I think this issue can be closed again.

**Comment by ggl-wolfy** [comment]
maybe check this out before closing: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8902#issuecomment-1483808904

**Comment by DonkeyBear** [comment]
I'm using `Anything-v4.5`，and it happened again.

- Colab I'm using
  https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/anything_4_webui_colab.ipynb

- WebUI URL I'm using
  trycloudflare

- Error message
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 436, in join_queue
    session_info = await websocket.receive_json()
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```
