### ISSUE TITLE
Pytorch 2.0 + Latest xformers and cuDNN

### ISSUE THREAD

**Issue by ataa** [camenduru/stable-diffusion-webui-colab#28]
I tried to create a Colab notebook with Python 3.10.6,  Pytorch 2.0 + Latest xformers and cuDNN libraries to get better performance without any success.
Is it even achievable on colab? On my local windows machine it was really easy, but I have 8GB of VRam only and decided to try it on Colab.

**Comment by camenduru** [comment]
try conda inside colab 
https://github.com/conda/conda 
https://anaconda.org/ 
https://github.com/conda-incubator/condacolab
