### ISSUE TITLE
[Bug]: ignore because weight is 0: 

### ISSUE THREAD

**Issue by sam5406** [camenduru/stable-diffusion-webui-colab#280]
### What happened?

The ignore because weight is 0:  still exist in stable and nightly colab 

### Console logs

```Shell
Total progress: 100% 30/30 [00:44<00:00,  1.49s/it]
restoring last networks
original forward/weights is restored.
ignore because weight is 0:
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

chillout_mix_webui_colab

### Which repo branch did the colab you use comes from ?

stable, nightly, drive

### Which tunnel did you use ?

--cloudflared, --localhostrun, --remotemoe

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
If you are still experiencing the same problem, please reopen this issue.
