### ISSUE TITLE
Cetus

### ISSUE THREAD

**Issue by Mar0xy** [camenduru/stable-diffusion-webui-colab#282]
Recently I have seen a decent model for anime on Pixai called cetus and went looking for it seeing it on civitai and thought it would be worth being added.

Link: https://civitai.com/models/6755/cetus-mix

I think the mix and v3 should be good if you don't feel like adding it then I might look into adding a colab file myself via PR

**Comment by camenduru** [comment]
Hi @Mar0xy thanks for the suggestion ❤ added
