### ISSUE TITLE
[Bug]:Slow run,why?

### ISSUE THREAD

**Issue by a530810944** [camenduru/stable-diffusion-webui-colab#287]
### What happened?

Run slowly in colab, need 25 minute fisrst，second need 60 minute,but Install a new lite Stable Diffusion only 8 minute。Why?

start
![image](https://user-images.githubusercontent.com/74164033/225466720-f523c3a0-4eea-458f-a383-8611ca5c10d0.png)

end

![image](https://user-images.githubusercontent.com/74164033/225470599-570d8777-69cc-4368-97be-fcb9d4a4cd7d.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

1

### Which repo branch did the colab you use comes from ?

drive

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Microsoft Edge

**Comment by etherealxx** [comment]
Do you know on which state it stuck the longest? (like when downloading something maybe?)

**Comment by camenduru** [comment]
Hi @a530810944 Maybe the regional server is having issues, but it will probably return to normal soon.

**Comment by a530810944** [comment]
Can't remember clearly。But this place need wait time more than 40 minute 

![image](https://user-images.githubusercontent.com/74164033/225476433-0c2b8450-7aad-480d-8fe2-f27150479d3e.png)
![image](https://user-images.githubusercontent.com/74164033/225476634-13d2a42d-e654-4213-a18f-e91094d17065.png)


I tried to execute only the last line,need 15 min,Web UI can be run.
But I don't know if it will affect.
Anyway, it runs slower than instal a new Stable Diffusion.

**Comment by camenduru** [comment]
please try again with new code
