### ISSUE TITLE
FATAL: this function is for sm80, but was built for sm750

### ISSUE THREAD

**Issue by iceandstorm** [camenduru/stable-diffusion-webui-colab#29]
During embedding training, this is called, so often that is stopping the output... 

FATAL: this function is for sm80, but was built for sm750

https://prnt.sc/_z-vsGwCCyEq

**Comment by camenduru** [comment]
probably colab changed some lib I will build xformers this may fix the problem

**Comment by camenduru** [comment]
@iceandstorm please try again with new xformers

**Comment by iceandstorm** [comment]
@camenduru it got worse now, even normal image generation throws it now

https://prnt.sc/pdFe-99Z3qRO

https://prnt.sc/uZyXP-au9qR8



and happy new year for you too! :)

**Comment by camenduru** [comment]
lol

**Comment by camenduru** [comment]
@iceandstorm thanks ❤ happy new year 🥳 I tried and it is working interesting 🤔

**Comment by iceandstorm** [comment]
It's a colab premium environment with high ram and priority. Could this
affect something?

**Comment by camenduru** [comment]
`!nvidia-smi ` please use this command and share the output

**Comment by camenduru** [comment]
probably you got different GPU then T4 you should use different xformers build

**Comment by iceandstorm** [comment]
i get another error when i dont use a premium gpu but high ram:

Total progress: 100% 20/20 [00:08<00:00, 2.34it/s] Training at rate of
0.002 until step 100000 Preparing dataset... 100% 133/133 [00:51<00:00,
2.61it/s] 0% 0/100000 [00:00<?, ?it/s]Traceback (most recent call last):
File
"/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py",
line 328, in train_embedding loss = shared.sd_model(x, c)[0] /
gradient_step File
"/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line
1190, in _call_impl return forward_call(*input, **kwargs) File
"/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py",
line 846, in forward return self.p_losses(x, c, t, *args, **kwargs) File
"/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py",
line 903, in p_losses logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the
indexed tensor (cpu) Applying xformers cross attention optimization.

**Comment by camenduru** [comment]
@iceandstorm, you should build your own xformers using this command. wait 1 hour and you will find the file `xformers-0.0.15+e163309.d20230103-cp38-cp38-linux_x86_64.whl` in your folder. Download that file and put it somewhere for later use, or send it to me and I can put it here.

the command
`!pip wheel git+https://github.com/facebookresearch/xformers#egg=xformers`

**Comment by iceandstorm** [comment]
https://drive.google.com/file/d/10mfoS7ONRSc4i-95bE1_a6yLED1aKfse/view?usp=share_link

link to the outcome

**Comment by camenduru** [comment]
thanks @iceandstorm ❤ what GPU did you use T4 or P100

**Comment by camenduru** [comment]
you can see with this command `!nvidia-smi`

**Comment by camenduru** [comment]
ok I added you can use like this 
`!pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15+e163309.d20230103-cp38-cp38-linux_x86_64_colab_pro.whl`

**Comment by iceandstorm** [comment]
Okay! Fascinating, this was a A100
https://prnt.sc/ridcRk0w9rfb
https://prnt.sc/EYm6XHw7psDS

**Comment by iceandstorm** [comment]
T4 has the same problem
https://prnt.sc/hK2BmWW_rOZ2
https://prnt.sc/QJKFccaLqM2F

**Comment by tgies** [comment]
> Okay! Fascinating, this was a A100 https://prnt.sc/ridcRk0w9rfb https://prnt.sc/EYm6XHw7psDS

This happens because of the `_colab_pro` @camenduru added on the end of the filename, which confuses pip (it is looking for the cpu arch name at the end of the wheel filename).

If Colab gives you an A100, you should be able to work around that by taking the `_colab_pro` back out when you download the file, like so:

```
!wget https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15+e163309.d20230103-cp38-cp38-linux_x86_64_colab_pro.whl -O /content/xformers-0.0.15+e163309.d20230103-cp38-cp38-linux_x86_64.whl
!pip install /content/xformers-0.0.15+e163309.d20230103-cp38-cp38-linux_x86_64.whl
```

This works for me.

**Comment by camenduru** [comment]
oops! thanks @tgies ❤ `{distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl` https://peps.python.org/pep-0427/#file-name-convention

**Comment by camenduru** [comment]
let's rename like this maybe works 🤔 `!pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15+e163309.d20230103.ColabProA100-cp38-cp38-linux_x86_64.whl`

**Comment by camenduru** [comment]
@iceandstorm please try new renamed version with A100
