### ISSUE TITLE
WebUi not loading

### ISSUE THREAD

**Issue by Rudy34160** [camenduru/stable-diffusion-webui-colab#290]
When running the Colab, I don't have a link to access the WebUi, going through Gradiolive:

![image](https://user-images.githubusercontent.com/118270456/225733796-97041c81-0c95-453b-abaf-ccffd4865f3b.png)

**Comment by camenduru** [comment]
Hi @Rudy34160 👋 please update your colab please check this https://github.com/camenduru/stable-diffusion-webui-colab/issues/190

**Comment by Rudy34160** [comment]
> Hi @Rudy34160 👋 please update your colab please check this #190

I don't think that's the problem, I open the Colab from the repository every session to make sure I'm up to date. Some updates require you to redo an installation? 🤔

![image](https://user-images.githubusercontent.com/118270456/225943602-9bcc163b-bfaa-4f0c-9e6c-ae28a48d1550.png)

**Comment by camenduru** [comment]
Hi @Rudy34160 👋 please first use `One Time Install & Update` colab then use `Run` colab you will get links like this

![Screenshot 2023-03-17 181854](https://user-images.githubusercontent.com/54370274/225947133-285e391e-8b80-451b-bc48-0bf24e4fe67b.png)

**Comment by camenduru** [comment]
Show your code part please

**Comment by Rudy34160** [comment]
It's Ok now.. 
I didn't understand what I did wrong, but it works.
