### ISSUE TITLE
hello there! the issue with the scunet upscaler seems like repeating every time([Bug]: 

### ISSUE THREAD

**Issue by xyzzart** [camenduru/stable-diffusion-webui-colab#291]
### What happened?

please give the instructions how to put it in a colab code to download it manually. one more thing,where does the contronet for sd2.1 go? thanx in advance 

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

stable-diffusion-webui-colab/v2.0/illuminati_v1_1_webui_colab.ipynb

### Which repo branch did the colab you use comes from ?

I don't know

### Which tunnel did you use ?

--cloudflared, --remotemoe

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
Hi @xyzzart 👋 lets use the old issue https://github.com/camenduru/stable-diffusion-webui-colab/issues/272

**Comment by xyzzart** [comment]
> Hi @xyzzart 👋 lets use the old issue #272

no prob
