### ISSUE TITLE
[Bug]: Stable Diffusion LoRA Models with Simple Colab Trainer

### ISSUE THREAD

**Issue by sukbearsuwu** [camenduru/stable-diffusion-webui-colab#292]
### What happened?

![271679120506_ pic](https://user-images.githubusercontent.com/120086676/226089049-7f080886-5585-4ccc-b698-2ff901d1ace8.jpg)

![261679120493_ pic](https://user-images.githubusercontent.com/120086676/226089067-db0ff2f6-9df0-4fdd-9fa6-c33f44b391a8.jpg)

![291679120711_ pic](https://user-images.githubusercontent.com/120086676/226089291-c3c593f3-11e1-4d4a-9b68-e8bdda0f3f7e.jpg)

The replacement checkpoint reported an error

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

Can you update Lora's training tutorial?

### Which repo branch did the colab you use comes from ?

I don't know

### What browsers do you use to access the WebUI ?

Microsoft Edge

**Comment by camenduru** [comment]
Hi @sukbearsuwu 👋 lets talk this in the discord `lora` channel this is maybe not a bug
