### ISSUE TITLE
[Bug]: MultiControl net leads to 502 on tunnel

### ISSUE THREAD

**Issue by IPv6** [camenduru/stable-diffusion-webui-colab#294]
### What happened?

- Enable MultiControlNet - set 2 control nets in settings
- Apply and reload ui
- tunnel starts to return 502, WebUI not working after that

### Console logs

```Shell
no logs in collab, nothing happens
But tunnel not working anymore
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/anything_3_webui_colab.ipynb#scrollTo=SaAJk33ppFw1

### Which repo branch did the colab you use comes from ?

stable

### Which tunnel did you use ?

--remotemoe

### What browsers do you use to access the WebUI ?

Mozilla Firefox, Google Chrome - tried both

**Comment by camenduru** [comment]
Hi @IPv6 👋 after editing settings please click apply then click colab stop button then start button again
