### ISSUE TITLE
[Bug]: controlnet some setting only work with slider, not work when you enter numbers

### ISSUE THREAD

**Issue by jimys** [camenduru/stable-diffusion-webui-colab#295]
### What happened?

<img width="569" alt="截屏2023-03-19 04 21 30" src="https://user-images.githubusercontent.com/1137380/226136695-de0bd0b8-edde-4a8a-89bc-5325e54c1ff4.png">
these setting will not change if you enter numbers,

it only change when you use the slide

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

main

### Which repo branch did the colab you use comes from ?

stable

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Apple Safari

**Comment by camenduru** [comment]
Hi @jimys 👋 please open same issue here https://github.com/Mikubill/sd-webui-controlnet/issues
