### ISSUE TITLE
Can I use my own domain to access stable-diffusion-webui?

### ISSUE THREAD

**Issue by Febtw** [camenduru/stable-diffusion-webui-colab#301]
I have my own domain added in cloudflare, can I use it to access stable-diffusion-webui?

**Comment by camenduru** [comment]
Hi @Febtw 👋 yep setup your cloudflare cdn record with your Host IP address

**Comment by Febtw** [comment]
> Hi @Febtw wave yep setup your cloudflare cdn record with your Host IP address

Sorry for not expressing myself clearly. I have installed the WebUI Colab to Google Drive instead of my host and after running I got “Public WebUI Colab remote.moe URL” and “Public WebUI Colab cloudflared URL“ to access my stable-diffusion-webui. But these two URLs are too complicated, I want to access stable-diffusion-webui through my own domain name.

**Comment by etherealxx** [comment]
@Febtw no you can't. It changes every time you run the code because that's how it works.
