### ISSUE TITLE
How do I upload the images in the colab folder in img2img

### ISSUE THREAD

**Issue by LUKESkaywalker314** [camenduru/stable-diffusion-webui-colab#302]
### What happened?

Is there a way to upload images from a Colab folder to img2img? Currently, img2img only allows uploading images from the local machine. I am trying to create an AI animation that requires batch processing, which cannot recognize file paths from local folders. Even if I create an input folder in Colab with the source images for batch processing, the output folder will still only contain the image uploaded from my local machine through img2img. Can you suggest a solution to this problem?English is not my native language, so I may not be able to express my meaning accurately. Thank you for your patience in reading through my question.
![1](https://user-images.githubusercontent.com/126801199/226313995-35b4d7e4-8a35-49d6-a09a-b404e50fad4b.png)
![2](https://user-images.githubusercontent.com/126801199/226314007-b8e64e61-4a77-43d0-b6d0-70176f30a7b1.png)
![3](https://user-images.githubusercontent.com/126801199/226314021-4dccfb5c-f2d7-4ed5-99c1-10a4b5f847d5.png)
![4](https://user-images.githubusercontent.com/126801199/226314029-6576b248-9ea3-447f-b80a-fc7fbb094ab3.png)
![5](https://user-images.githubusercontent.com/126801199/226314032-e500a285-bc8a-4f52-b473-1e9d72afb599.png)
![6](https://user-images.githubusercontent.com/126801199/226314040-adcc12f2-68aa-4fdc-9c62-99a3a8869958.png)
![7](https://user-images.githubusercontent.com/126801199/226314056-5a9dac78-b9c0-4a75-b01b-540331e1e474.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

a_certain_model_webui_colab.ipynb

### Which repo branch did the colab you use comes from ?

I don't know

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
Hi @LUKESkaywalker314 👋 please try this 

![Screenshot 2023-03-20 134538](https://user-images.githubusercontent.com/54370274/226317713-8b68b542-b792-4e09-b1f9-56a379098d12.png)
