### ISSUE TITLE
chilloutmix的模型跑起来了，怎么生成小姐姐啊

### ISSUE THREAD

**Issue by younggggger** [camenduru/stable-diffusion-webui-colab#303]
### What happened?

chilloutmix的模型跑起来了，怎么生成小姐姐啊

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

chilloutmix

### Which repo branch did the colab you use comes from ?

stable

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
Hi @younggggger 👋 please check this https://civitai.com/models/6424/chilloutmix
