### ISSUE TITLE
📕 Setting WebUI Configurations without Restarting

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#305]
### Tutorial Video

https://www.youtube.com/watch?v=UTAXj0DOv_k

create your config files and add this line end of the `!python`
```py
--ui-config-file /content/drive/MyDrive/webui_configs/ui-config.json --ui-settings-file /content/drive/MyDrive/webui_configs/config.json
```

![Screenshot 2023-03-20 210650](https://user-images.githubusercontent.com/54370274/226428897-b8f35c41-328f-465d-9c9f-d5f26fee80f8.png)

**Comment by camenduru** [comment]
create your config files and add this line end of the `!python`
```py
--ui-config-file /content/drive/MyDrive/webui_configs/ui-config.json --ui-settings-file /content/drive/MyDrive/webui_configs/config.json
```

![Screenshot 2023-03-20 210650](https://user-images.githubusercontent.com/54370274/226428897-b8f35c41-328f-465d-9c9f-d5f26fee80f8.png)

**Comment by jjiikkkk** [comment]
you see, google has a risk control on colab when we are using colab
always and frequently disconnecting. and impossible to apply and restart the ui interface after extensions are inserted
