### ISSUE TITLE
Issue Trying to Launch UI from Google Drive

### ISSUE THREAD

**Issue by TheGho7t** [camenduru/stable-diffusion-webui-colab#310]
Wasn't sure if anyone could help with this but I'm trying to launch the UI from my Google Drive. 

It recognizes it and functions properly however, each time I start a Colab session up, it has to install gfpgan, clip, xformers, requirements for Web UI, etc...

I moved my own venv folder to Drive but cannot figure out how to connect it into the launch.py, or if it can grasp that. I can't even tell where the aforementioned folders are being downloaded to. 

Is there any way to add those files/folders to my Google Drive so that I can bypass having to reinstall them every time I start up my session? It's not the biggest issue in the world but it would save me 7-10 minutes each time I hop on. Thanks.

**Comment by camenduru** [comment]
Hi @TheGho7t 👋 please use this https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive
