### ISSUE TITLE
[QUESTION]: Where is the notebook for illuminati1.1 ?

### ISSUE THREAD

**Issue by svupper** [camenduru/stable-diffusion-webui-colab#313]
### What happened?

Hello, I can't find it, is it not supported anymore?

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

N/A

### Which repo branch did the colab you use comes from ?

stable

### Which tunnel did you use ?

--share (Gradio Tunnel)

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by etherealxx** [comment]
![image](https://user-images.githubusercontent.com/64251396/227452799-8a987343-fd98-47c2-b450-2acece746d11.png)
![image](https://user-images.githubusercontent.com/64251396/227452866-8fa40a5d-df7c-413e-92bd-63614eac1cc1.png)
![image](https://user-images.githubusercontent.com/64251396/227453016-083b2422-2a29-4754-9925-d10532e0f8f7.png)

The model is still available to download manually/with batchlinks on civitai, but the point is, camenduru won't include the colab on his repo for those reasons.
