### ISSUE TITLE
No module named 'triton'

### ISSUE THREAD

**Issue by etherealxx** [camenduru/stable-diffusion-webui-colab#32]
![2023-01-06 20_57_16-cafe_instagram_v6_webui_colab ipynb - Colaboratory](https://user-images.githubusercontent.com/64251396/211027019-fa366855-15d3-4ea6-bd10-80fe11ce3bb6.jpg)

Is the 'optimization' module not that important that you didn't include it?

**Comment by camenduru** [comment]
please install `!pip install triton` then compare with not triton version, is it effecting something or not I also want to learn

**Comment by camenduru** [comment]
please check this for more info https://openai.com/blog/triton/

**Comment by camenduru** [comment]
also http://www.eecs.harvard.edu/~htk/publication/2019-mapl-tillet-kung-cox.pdf

**Comment by etherealxx** [comment]
I tried this `!pip install triton==2.0.0.dev20221120`
Basically no difference in generation time using txt2img. Idk about Training and other stuff.
Also i'm not that smart to read those paper😅
