### ISSUE TITLE
bug报错

### ISSUE THREAD

**Issue by lfglfg11** [camenduru/stable-diffusion-webui-colab#320]
sed: can't read /content/stable-diffusion-webui/launch.py: No such file or directory
sed: can't read /content/stable-diffusion-webui/requirements_versions.txt: No such file or directory
python3: can't open file '/content/stable-diffusion-webui/launch.py': [Errno 2] No such file or directory

**Comment by camenduru** [comment]
Hi @lfglfg11 👋 please send the colab link

**Comment by lfglfg11** [comment]
> 

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/stable_diffusion_1_5_webui_colab.ipynb

**Comment by lfglfg11** [comment]
> 你好@lfglfg11 👋请发送colab链接

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/stable_diffusion_1_5_webui_colab.ipynb

**Comment by camenduru** [comment]
tested and it is working 🥳 please try again
