### ISSUE TITLE
Why the 1.6-1.8 version suddenly doesn't work?Please open version 1.6-1.8.

### ISSUE THREAD

**Issue by w8988998ww** [camenduru/stable-diffusion-webui-colab#321]
请开放1.6-1.8的版本

**Comment by camenduru** [comment]
Hi @w8988998ww 👋 to access the latest versions, please use the updated versions available at  https://github.com/camenduru/stable-diffusion-webui-colab

`lite` has a stable WebUI and stable installed extensions.
`stable` has ControlNet, a stable WebUI, and stable installed extensions.
`nightly` has ControlNet, the latest WebUI, and daily installed extension updates.
