### ISSUE TITLE
Possible to add upscalers from "extras" to "deforum"?

### ISSUE THREAD

**Issue by tralala87** [camenduru/stable-diffusion-webui-colab#322]
### What happened?

Hey.

First of all, thank you very much for this amazing collection and repo!!

Secondly, is it possible to add all those upscalers from the "extra" section to the "deforum" section?

Thank you!

### Console logs

```Shell
Hey.

First of all, thank you very much for this amazing collection and repo!!

Secondly, is it possible to add all those upscalers from the "extra" section to the "deforum" section?

Thank you!
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

SD_v2_1

### Which repo branch did the colab you use comes from ?

stable

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by etherealxx** [comment]
Hi👋 I think you should open this issue/feature request to deforum repo instead😁✨
