### ISSUE TITLE
[Bug]: The “moe” address for starting multiple colabs is the same

### ISSUE THREAD

**Issue by Hsoraa** [camenduru/stable-diffusion-webui-colab#328]
### What happened?

When I start multiple colab, the same storage space,The other three are all different addresses, and only the moe address is the same

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

run.ipynb

### Which repo branch did the colab you use comes from ?

drive

### Which tunnel did you use ?

--multiple

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by Hsoraa** [comment]
By the way,Everytime startup has the same address, can I change it

**Comment by NUROISEA** [comment]
> By the way,Everytime startup has the same address, can I change it

Yes you can change it.

Go to `stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-tunnels` folder in your Google Drive, find `id_rsa` (or something similar) file and delete it. Next, rename the `sd-webui-tunnels` folder to something different, like `sd-tunnel`.

Renaming the folder prevents the extension from creating the `id_rsa` file again (I hope)

**Comment by Hsoraa** [comment]
> > By the way,Everytime startup has the same address, can I change it
> 
> Yes you can change it.
> 
> Go to `stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-tunnels` folder in your Google Drive, find `id_rsa` (or something similar) file and delete it. Next, rename the `sd-webui-tunnels` folder to something different, like `sd-tunnel`.
> 
> Renaming the folder prevents the extension from creating the `id_rsa` file again (I hope)

Thanks! It works well!
