### ISSUE TITLE
[Bug]: bug with new version of gradio

### ISSUE THREAD

**Issue by Indras91** [camenduru/stable-diffusion-webui-colab#330]
### What happened?

The new version of gradio have a lot of issue, like infinite loading of selecting checkpoint, in civitai browser, please rollback to the version before, thats more stable than this, 

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

abyss_orange_mix_3_webui_colab

### Which repo branch did the colab you use comes from ?

nightly

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Mozilla Firefox

**Comment by camenduru** [comment]
Hi @Indras91 👋 please use `stable` version we will fix the issues

**Comment by camenduru** [comment]
Now, the `stable` version is the old `nightly` version.
