### ISSUE TITLE
[Bug]: Controlnet plugin stopped working after March 30th

### ISSUE THREAD

**Issue by kirin161** [camenduru/stable-diffusion-webui-colab#331]
### What happened?

Hi, the Controlnet plugin no longer works after March 30th. 

In the log, it looked all normal (see the console logs) but the poses in the pictures were completely random. 

My suspicion is on these two lines checking out specific version branches:

```
!git clone -b v2.1 https://github.com/camenduru/stable-diffusion-webui
!git clone -b v2.0 https://github.com/camenduru/sd-civitai-browser /content/stable-diffusion-webui/extensions/sd-civitai-browser
```

After removing `-b v2.x` to check out main branch, it's working again...
```
!git clone https://github.com/camenduru/stable-diffusion-webui
!git clone https://github.com/camenduru/sd-civitai-browser /content/stable-diffusion-webui/extensions/sd-civitai-browser
```

Not sure if it is the right fix, please help to verify. Thank you 😄 

### Console logs

```Shell
Startup time: 96.0s (import torch: 8.5s, import gradio: 1.2s, import ldm: 2.0s, other imports: 2.3s, setup codeformer: 0.3s, load scripts: 34.1s, load SD checkpoint: 38.1s, create ui: 8.8s, gradio launch: 0.7s).
Loading model: control_openpose-fp16 [9ca67cc5]
Loaded state_dict from [/content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_openpose-fp16.safetensors]
ControlNet model control_openpose-fp16 [9ca67cc5] loaded.
Loading preprocessor: openpose_hand
0% 0/35 [00:00<?, ?it/s]
3% 1/35 [00:10<05:51, 10.34s/it]
```

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Are you using the latest version of the colab notebook?

- [X] Yes, i am using the latest version from the repo

### Which colab notebook did you use?

meina_mix_v8_webui_colab

### Which repo branch did the colab you use comes from ?

stable

### Which tunnel did you use ?

--cloudflared

### What browsers do you use to access the WebUI ?

Google Chrome

**Comment by camenduru** [comment]
Hi @kirin161 👋 it looks like the huggingface cdn is down. probably, it will be fixed soon.
![image](https://user-images.githubusercontent.com/54370274/229624171-7552c7bd-9e70-4bec-a132-03ae0221c819.png)
