### ISSUE TITLE
[Bug]: Connection errored out. after send img2img 

### ISSUE THREAD

**Issue by Asmedeus998** [camenduru/stable-diffusion-webui-colab#340]
### What happened?

Generate image by using img2img in google collab.

After that I try to send it to `Send to img2img` but I get Connection errored out.

I also try using gradio and cloudflare link but it also not working.

here the output of error:
![image](https://user-images.githubusercontent.com/60872999/229997437-2d98c0dd-ef9a-4854-a068-29b36846d763.png)

### Console logs

```shell
None
```

### Which model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/neverending_dream_webui_colab.ipynb

**Comment by camenduru** [comment]
Hi @Asmedeus998 👋 which public webui colab url were you using when the error occurred?

**Comment by camenduru** [comment]
did you get any error message in the colab output?

**Comment by camenduru** [comment]
I can't solve this issue without more information. If this happens again, please copy and paste everything from the Colab cell output here and open the issue please
