### ISSUE TITLE
[Bug]: showing error after opening of stable diffusion webui

### ISSUE THREAD

**Issue by YuukiRuyam** [camenduru/stable-diffusion-webui-colab#343]
I used drive coloab run file after launching one of the link it shows this command in colab and error in webui tab at setting area and model change area can anyone tell me why its showing :

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 947, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 371, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 257, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: update() got an unexpected keyword argument 'multiline

**Comment by camenduru** [comment]
Hi @YuukiRuyam 👋 did you use install colab 
![image](https://user-images.githubusercontent.com/54370274/230281043-cf8c3ff9-b506-46fd-8597-9cf7a259e75a.png)

**Comment by YuukiRuyam** [comment]
> Hi @YuukiRuyam 👋 did you use install colab ![image](https://user-images.githubusercontent.com/54370274/230281043-cf8c3ff9-b506-46fd-8597-9cf7a259e75a.png)

yes first i install it and then run
i was using it for quite a while after update its showing this problem

**Comment by camenduru** [comment]
please use One Time Install & Update again maybe fixes

**Comment by YuukiRuyam** [comment]
I already used one time install & update 2 time but it's still not fixed so I m thinking to fully uninstall and reinstall again .so will it not cause any problems??

**Comment by camenduru** [comment]
please copy paste the install colab output here

**Comment by YuukiRuyam** [comment]
Whole code output

**Comment by camenduru** [comment]
yep

**Comment by 253189147cc** [comment]
![image](https://user-images.githubusercontent.com/125724271/230375440-0eb6116e-cabc-4e7c-b041-544e9e0726d9.png)
It was running fine before today, but today there is such an error, what is the problem, how can I solve it, it seems that my friend also has the same problem

**Comment by YuukiRuyam** [comment]
Install colab output


/content
Mounted at /content/drive
env: PYTHONDONTWRITEBYTECODE=1
Selecting previously unselected package libc-ares2:amd64.
(Reading database ... 122349 files and directories currently installed.)
Preparing to unpack .../libc-ares2_1.15.0-1ubuntu0.2_amd64.deb ...
Unpacking libc-ares2:amd64 (1.15.0-1ubuntu0.2) ...
Selecting previously unselected package libaria2-0:amd64.
Preparing to unpack .../libaria2-0_1.35.0-1build1_amd64.deb ...
Unpacking libaria2-0:amd64 (1.35.0-1build1) ...
Selecting previously unselected package aria2.
Preparing to unpack .../aria2_1.35.0-1build1_amd64.deb ...
Unpacking aria2 (1.35.0-1build1) ...
Setting up libc-ares2:amd64 (1.15.0-1ubuntu0.2) ...
Setting up libaria2-0:amd64 (1.35.0-1build1) ...
Setting up aria2 (1.35.0-1build1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui'...
remote: Enumerating objects: 17762, done.
remote: Total 17762 (delta 0), reused 0 (delta 0), pack-reused 17762
Receiving objects: 100% (17762/17762), 28.19 MiB | 13.10 MiB/s, done.
Resolving deltas: 100% (12435/12435), done.
Updating files: 100% (200/200), done.
Already on 'v2.1'
Your branch is up to date with 'origin/v2.1'.
HEAD is now at a9fed7c3 Merge pull request #8503 from mcmonkey4eva/filename-length-limit-fix
From https://github.com/camenduru/stable-diffusion-webui
 * branch              v2.1       -> FETCH_HEAD
Already up to date.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/embeddings/negative'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), 1.70 KiB | 9.00 KiB/s, done.
fatal: cannot exec '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/embeddings/negative/.git/hooks/post-checkout': Permission denied
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Lora/positive'...
remote: Enumerating objects: 6, done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 6
Unpacking objects: 100% (6/6), 830 bytes | 7.00 KiB/s, done.
fatal: cannot exec '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Lora/positive/.git/hooks/post-checkout': Permission denied

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
63049b|OK  |    83MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/ESRGAN/4x-UltraSharp.pth

Status Legend:
(OK):download completed.
--2023-04-06 12:00:10--  https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-scripts/main/run_n_times.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 533 [text/plain]
Saving to: ‘/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/scripts/run_n_times.py’

/content/drive/MyDr 100%[===================>]     533  --.-KB/s    in 0s      

2023-04-06 12:00:10 (20.9 MB/s) - ‘/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/scripts/run_n_times.py’ saved [533/533]

Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui'...
remote: Enumerating objects: 11907, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 11907 (delta 62), reused 89 (delta 47), pack-reused 11783
Receiving objects: 100% (11907/11907), 127.83 MiB | 12.58 MiB/s, done.
Resolving deltas: 100% (6988/6988), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser'...
remote: Enumerating objects: 172, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 172 (delta 32), reused 32 (delta 23), pack-reused 116
Receiving objects: 100% (172/172), 65.54 KiB | 2.11 MiB/s, done.
Resolving deltas: 100% (58/58), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/stable-diffusion-webui-huggingface'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 121 (delta 12), reused 10 (delta 10), pack-reused 106
Receiving objects: 100% (121/121), 28.80 KiB | 1.37 MiB/s, done.
Resolving deltas: 100% (42/42), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-civitai-browser'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 143 (delta 31), reused 20 (delta 20), pack-reused 108
Receiving objects: 100% (143/143), 34.15 KiB | 1.37 MiB/s, done.
Resolving deltas: 100% (31/31), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-additional-networks'...
remote: Enumerating objects: 716, done.
remote: Counting objects: 100% (414/414), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 716 (delta 273), reused 314 (delta 238), pack-reused 302
Receiving objects: 100% (716/716), 217.52 KiB | 3.20 MiB/s, done.
Resolving deltas: 100% (391/391), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet'...
remote: Enumerating objects: 3330, done.
remote: Counting objects: 100% (482/482), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 3330 (delta 476), reused 474 (delta 474), pack-reused 2848
Receiving objects: 100% (3330/3330), 8.28 MiB | 11.79 MiB/s, done.
Resolving deltas: 100% (1738/1738), done.
Updating files: 100% (447/447), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/openpose-editor'...
remote: Enumerating objects: 112, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 112 (delta 44), reused 37 (delta 37), pack-reused 62
Receiving objects: 100% (112/112), 237.58 KiB | 2.93 MiB/s, done.
Resolving deltas: 100% (47/47), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-depth-lib'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 93 (delta 17), reused 73 (delta 8), pack-reused 0
Unpacking objects: 100% (93/93), 5.75 MiB | 2.90 MiB/s, done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/posex'...
remote: Enumerating objects: 402, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 402 (delta 19), reused 29 (delta 16), pack-reused 364
Receiving objects: 100% (402/402), 11.39 MiB | 14.57 MiB/s, done.
Resolving deltas: 100% (194/194), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-tunnels'...
remote: Enumerating objects: 367, done.
remote: Counting objects: 100% (220/220), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 367 (delta 164), reused 114 (delta 108), pack-reused 147
Receiving objects: 100% (367/367), 66.73 KiB | 1.80 MiB/s, done.
Resolving deltas: 100% (181/181), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/batchlinks-webui'...
remote: Enumerating objects: 483, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 483 (delta 135), reused 143 (delta 87), pack-reused 277
Receiving objects: 100% (483/483), 4.34 MiB | 11.69 MiB/s, done.
Resolving deltas: 100% (259/259), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/stable-diffusion-webui-catppuccin'...
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 202 (delta 22), reused 20 (delta 13), pack-reused 165
Receiving objects: 100% (202/202), 13.43 MiB | 13.65 MiB/s, done.
Resolving deltas: 100% (89/89), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/a1111-sd-webui-locon'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 151 (delta 76), reused 103 (delta 38), pack-reused 0
Receiving objects: 100% (151/151), 33.69 KiB | 1.29 MiB/s, done.
Resolving deltas: 100% (76/76), done.
Cloning into '/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd_webui_stealth_pnginfo'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 34 (delta 12), reused 27 (delta 7), pack-reused 0
Unpacking objects: 100% (34/34), 7.54 KiB | 14.00 KiB/s, done.
/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui
HEAD is now at fbe6eab Merge pull request #530 from hithereai/fix_interp_ffmpeg
Already up to date.
HEAD is now at 46dfa95 Merge pull request #1 from camenduru/v2.0
Already up to date.
HEAD is now at 6e824a1 Create LICENSE
Already up to date.
HEAD is now at 0a5aec6 Merge pull request #15 from camenduru/v2.0
Already up to date.
HEAD is now at d944d42 Update README.md
Already up to date.
HEAD is now at 241c05f Merge pull request #652 from DiligentCatCat/main
Already up to date.
HEAD is now at a55ab7c test
Already up to date.
HEAD is now at 28a2238 Update readme and ui screenshot
Already up to date.
HEAD is now at 61169d3 improve style
Already up to date.
HEAD is now at 709b8a0 Update ssh_tunnel.py
Already up to date.
HEAD is now at fceda4d 🎁🪲🔨Hotfix 3.1.1b
Already up to date.
HEAD is now at e11df39 Update webp
Already up to date.
HEAD is now at 8ffee40 Update main.py
Already up to date.
HEAD is now at 9a8709a 🐛universal fix for naughty extensions feeding alpha channel to hiresfix
Already up to date.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
df906c|OK  |    77MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/hand_pose_model.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7fee97|OK  |    64MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body_pose_model.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1f51c8|OK  |    77MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/midas/dpt_hybrid-midas-501f0c75.pt

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
47e0ab|OK  |    43MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mlsd/mlsd_large_512_fp32.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
4cb6ab|OK  |    22MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mlsd/mlsd_tiny_512_fp32.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
d9350c|OK  |    68MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/hed/network-bsds500.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f487b9|OK  |    66MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/upernet_global_small.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
40bfc3|OK  |    65MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_canny-fp16.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
2087e8|OK  |    69MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_depth-fp16.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
de602c|OK  |    68MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_hed-fp16.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
537a5c|OK  |    71MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_mlsd-fp16.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
d33505|OK  |    72MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_normal-fp16.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
aea81d|OK  |    75MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_openpose-fp16.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0fafd7|OK  |    36MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_scribble-fp16.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f843a2|OK  |    18MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_seg-fp16.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
d38d40|OK  |    66MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_style_sd14v1.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
119501|OK  |    70MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_sketch_sd14v1.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
cee131|OK  |    23MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_keypose_sd14v1.pth

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
47dd38|OK  |    74MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/t2iadapter_color_sd14v1.pth

Status Legend:
(OK):download completed.
 *** Download Progress Summary as of Thu Apr  6 12:05:12 2023 *** 
=
[#8ddb4d 1.3GiB/3.9GiB(33%) CN:16 DL:22MiB ETA:2m2s]
FILE: /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
-

 *** Download Progress Summary as of Thu Apr  6 12:06:12 2023 *** 
=
[#8ddb4d 2.7GiB/3.9GiB(68%) CN:16 DL:24MiB ETA:52s]
FILE: /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
-

 *** Download Progress Summary as of Thu Apr  6 12:07:13 2023 *** 
=
[#8ddb4d 3.9GiB/3.9GiB(99%) CN:16 DL:21MiB ETA:1s]
FILE: /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
-


Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8ddb4d|OK  |    24MiB/s|/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt

Status Legend:
(OK):download completed.
/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/taming-transformers...
Cloning K-diffusion into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/k-diffusion...
Cloning CodeFormer into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/CodeFormer...
Cloning BLIP into /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Installing Deforum requirement: av
Installing Deforum requirement: pims



Installing sd-webui-controlnet requirement: svglib

Installing pycloudflared


Installed

**Comment by kaisar149** [comment]
Just to leave it here, I'm also receiving the same error... Even after reinstalling everything anew

**Comment by camenduru** [comment]
Hi @YuukiRuyam 👋  It looks like everything installed correctly. could you also please send the `run` colab output?

**Comment by camenduru** [comment]
Hi @253189147cc 👋 Hi @kaisar149 Sorry, I accidently deleted `import os` and forgot to test. 😔 please try again

**Comment by YuukiRuyam** [comment]
Now it's working fine
Thanks

**Comment by YuukiRuyam** [comment]
sry after error showing again after i restart the webui after changing some setting .
here the output of run
you can see error at the end 
[run output file.txt](https://github.com/camenduru/stable-diffusion-webui-colab/files/11177160/run.output.file.txt)

**Comment by camenduru** [comment]
It looks like the tunnel's websocket has disconnected. Please try another link `starlette.websockets.WebSocketDisconnect: 1006`

ERROR:    Exception in ASGI application https://github.com/camenduru/stable-diffusion-webui-colab/issues/279

**Comment by 253189147cc** [comment]
Many thanks bro.Now it's working fine
