### ISSUE TITLE
[Bug]: NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by Salvia2023** [camenduru/stable-diffusion-webui-colab#344]
### What happened?

This Webui is really useful, and I appreciate your contributions. 
However, when I opened it today, I received the following error message: 
**"NameError: name 'os' is not defined".** 
I thought that I might have accidentally damaged the operating files during operation, so I reinstalled and deployed them on Google Drive and Google Colab. 
However, the problem was not resolved after redeployment.
What should I do to fix it? 
Or could you please fix the issue in the "RUN" program? 
Thank you very much.

### Console logs

---------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-1-428a9d632560>](https://localhost:8080/#) in <cell line: 64>()
     62 get_ipython().system('mkdir /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/models')
     63 
---> 64 if not os.path.exists(f"/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP"):
     65   os.mkdir(f"/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP")
     66 get_ipython().system('aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://openaipublic.azureedge.net/clip/models/b8cca3fd41ae0c99ba7e8951adf17d267cdb84cd88be6f7c2e0eca1737a03836/ViT-L-14.pt -d /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP -o ViT-L-14.pt')
**NameError: name 'os' is not defined**
### Which colab and model(s) were you using when the error occurred?

https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by elvis972602** [comment]
I think this is caused by the latest commit: https://github.com/camenduru/stable-diffusion-webui-colab/commit/58b77cfed199659ea18cf17ccd991b70496ab42d
You can try to add back the deleted part first or just add `import os`

**Comment by elvis972602** [comment]
You should add it to the top of the file and re-run it.

**Comment by Salvia2023** [comment]
Okay, I'll try it tomorrow, the Google Colab's free server is busy now.
Thank you very much.

**Comment by kaisar149** [comment]
> I think this is caused by the latest commit: [58b77cf](https://github.com/camenduru/stable-diffusion-webui-colab/commit/58b77cfed199659ea18cf17ccd991b70496ab42d) You can try to add back the deleted part first or just add `import os`

This is it, thanks

**Comment by camenduru** [comment]
Sorry, I accidently deleted `import os` and forgot to test. 😔

**Comment by Salvia2023** [comment]
> Sorry, I accidently deleted `import os` and forgot to test. 😔

It has returned to normal, thanks a lot!
Also thanks for the suggestion from @elvis972602  .
