### ISSUE TITLE
Loopback Wave script

### ISSUE THREAD

**Issue by zaviier** [camenduru/stable-diffusion-webui-colab#348]
hi.. can you please add Loopback Wave script on the next update?
https://rentry.org/sd-loopback-wave

also, it's required ffmpeg.
i don't know how to install them for google colab, can you install them?

**Comment by camenduru** [comment]
please test with this colab https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/dev/test.ipynb

**Comment by zaviier** [comment]
@camenduru all good, but I got 2 error in colab.
1. Stealth PNGinfo, so i need to disable it
2. no such file or directory
"[image2 @ 0x55d1c69fe000] Could find no file with path 'outputs/img2img-images/loopback-wave/asada55-3976919548/%d.png' and index in the range 0-4
outputs/img2img-images/loopback-wave/asada55-3976919548/%d.png: No such file or directory"

so, need to disable "Save images to a subdirectory"

everything good.. just need to disable those 2 setting

**Comment by camenduru** [comment]
thanks ❤ you can find here 
![image](https://user-images.githubusercontent.com/54370274/230719584-9713b01b-b543-4108-b605-471cc6957725.png)
