### ISSUE TITLE
Issues with steps passed a certain point

### ISSUE THREAD

**Issue by Onierous** [camenduru/stable-diffusion-webui-colab#35]
Before yesterday all of the colab notebooks you maintain were working great. Now (and I noticed the interface has changed a little bit as well, see the pictures below) if I set the steps to 150 for example (this is just one example I've been able to confirm that breaks it) colab will run like it's rendering the picture but then it gets to 100% and freezes and doesn't load the images into the web ui. Nothing else in the web ui works after this either so I'm guessing it's somehow getting hung up on something.

This only started happening today.

Here are the screenshots:

interface before -
![image](https://user-images.githubusercontent.com/89480919/211434424-5618365a-b94d-4a5c-acdc-5bbae1e56518.png)

interface now - 
![image](https://user-images.githubusercontent.com/89480919/211435776-8e86c3d8-8800-4905-93ee-42ed34485992.png)

**Comment by camenduru** [comment]
I updated the repo please try again if still unstable I will go back to old version until webui becomes stable

**Comment by camenduru** [comment]
Also this is the way to go back to the old version
!git clone https://github.com/camenduru/stable-diffusion-webui
to this 
!git clone -b v1.6 https://github.com/camenduru/stable-diffusion-webui

**Comment by SkyFryz24** [comment]
Sorry but I'll try it and It still freeze 😥

**Comment by megazaz80** [comment]
it is broken af )))), every time its needed to reload the page that you can start render again and you can only see the photos in image browser.... old version was much better...if it ain't broke, don't fix it by SONY ))))

**Comment by camenduru** [comment]
back to old version  until webui becomes stable
