### ISSUE TITLE
After the installation is complete, the runis very slow

### ISSUE THREAD

**Issue by chuanSir123** [camenduru/stable-diffusion-webui-colab#370]
execuse me, could you optimize the startup speed? or do not repeat installation？

**Comment by chuanSir123** [comment]
ps: I have enough drive space

**Comment by Anonimouche** [comment]
Are you running the collab locally?

**Comment by camenduru** [comment]
Hi @chuanSir123 👋 please use `One Time Install & Update` colab

**Comment by chuanSir123** [comment]
> Hi @chuanSir123 👋 please use `One Time Install & Update` colab

sure,i use One Time Install & Update colab,but still slow. install many project

**Comment by camenduru** [comment]
slow? 10 minutes? 20 minutes? please tell me your startup time

**Comment by chuanSir123** [comment]
> slow? 10 minutes? 20 minutes? please tell me your startup time

10minutes，I saw the cloud platform of autodl, the data is mounted to the cloud disk, and it can be quickly started within 1 minute after a complete restart

**Comment by camenduru** [comment]
send me the autodl link please

**Comment by camenduru** [comment]
if this https://www.autodl.com/home we cannot do like this with free colab sorry 10 minutes is normal
