### ISSUE TITLE
[Warning]: The system may not allow you to run the code you are currently executing, which may limit your ability to use Colab's features in the future.

### ISSUE THREAD

**Issue by Salvia2023** [camenduru/stable-diffusion-webui-colab#379]
### What happened?

When I running the code today, I received the message below:
"The system may not allow you to run the code you are currently executing, which may limit your ability to use Colab's features in the future."
And the action I could take were: "Still run the code" & "Cancel running" .
Is there anything that I should pay attention to?

### Colab cell output

```shell
none
```

### Which colab and model(s) were you using when the error occurred?

drive

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by etherealxx** [comment]
Read the topmost message on this repo readme page:

![image](https://user-images.githubusercontent.com/64251396/233676772-daadacac-fef7-4f35-8905-066545a87ee1.png)

Currently, like, for this day and maybe tomorrow, just continue, until further notice.

**Comment by Salvia2023** [comment]
> Read the topmost message on this repo readme page:
> 
> ![image](https://user-images.githubusercontent.com/64251396/233676772-daadacac-fef7-4f35-8905-066545a87ee1.png)
> 
> Currently, like, for this day and maybe tomorrow, just continue, until further notice.

Got it, thanks a lots!
