### ISSUE TITLE
Install the dependencies to Google Drive?

### ISSUE THREAD

**Issue by Febtw** [camenduru/stable-diffusion-webui-colab#393]
Can the dependencies of SDW and extensions be installed to Google Drive to save the time of each running? I see some issues mentioning slow running, and I also find that installing dependencies takes a long time at the begining of each running. Therefore, I am wondering if it would be effective to install the dependencies to Google Drive once to avoid duplicate installations at the begining of each running?

**Comment by camenduru** [comment]
Hi @Febtw 👋 please check community colabs https://github.com/camenduru/stable-diffusion-webui-colab/tree/community
