### ISSUE TITLE
[request]: can you add styles please

### ISSUE THREAD

**Issue by WalidAliAlfaid** [camenduru/stable-diffusion-webui-colab#394]
### What happened?

.

### Colab cell output

```shell
.
```

### Which colab and model(s) were you using when the error occurred?

.

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

### If you used HiRes mode when the error occurred, please provide the Hires info

.

**Comment by machiavel23** [comment]
What do you mean by styles? The "style" thing under the prompt? It's just prompts saved as txt, you Can find plenty online if it's that 🤔
