### ISSUE TITLE
Can't load some safetensor models anymore

### ISSUE THREAD

**Issue by JcynR** [camenduru/stable-diffusion-webui-colab#399]
I'm getting an error while loading Deliberate V2 safetensor on colab.

It was working fine yesterday. I didn't change anything,

```
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by JcynR** [comment]
@Anonimouche I added it myself and made it download, which has been working fine for months. Until last night...

Also, the colab you linked doesn't work. Getting this with it:
```
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
```

**Comment by Anonimouche** [comment]
> @Anonimouche I added it myself and made it download, which has been working fine for months. Until last night...
> 
> Also, the colab you linked doesn't work. Getting this with it:
> 
> ```
> RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
> ```

Did you try running it without changing anything, it worked perfectly fine for me when I tested it. 

Also could you send the original colab you were using and the modifications you did on it?

**Comment by Headupdef** [comment]
Your colab works however it disconnects right away after generating only an image or two

**Comment by camenduru** [comment]
Hi @Headupdef 👋 try this https://github.com/etherealxx/volatile-concentration-localux-colab 😜

**Comment by camenduru** [comment]
https://github.com/camenduru/stable-diffusion-webui-colab/issues/401

**Comment by Headupdef** [comment]
You are awesome!
