### ISSUE TITLE
Any idea on how to fix this?

### ISSUE THREAD

**Issue by okbabynhe** [camenduru/stable-diffusion-webui-colab#4]
Cloning into 'stable-diffusion-webui'...
remote: Enumerating objects: 10956, done.
remote: Total 10956 (delta 0), reused 0 (delta 0), pack-reused 10956
Receiving objects: 100% (10956/10956), 23.68 MiB | 11.96 MiB/s, done.
Resolving deltas: 100% (7670/7670), done.
/content/stable-diffusion-webui/stable-diffusion-webui/stable-diffusion-webui
--2022-11-28 06:23:59--  https://huggingface.co/Linaqruf/anything-v3.0/resolve/main/Anything-V3.0-pruned.ckpt
Resolving huggingface.co (huggingface.co)... 54.147.99.175, 34.227.196.80, 2600:1f18:147f:e850:fad3:e054:c752:ff16, ...
Connecting to huggingface.co (huggingface.co)|54.147.99.175|:443... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
Retrying.

--2022-11-28 06:25:01--  (try: 2)  https://huggingface.co/Linaqruf/anything-v3.0/resolve/main/Anything-V3.0-pruned.ckpt
Reusing existing connection to huggingface.co:443.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs.huggingface.co/repos/1e/ef/1eefd55077badc87cd1798672a058b8d55aeab58e781be883f2ec0e0917679e3/543bcbc21294831c6245cd74c8a7707761e28812c690f946cb81fef930d54b5e?response-content-disposition=attachment%3B%20filename%3D%22Anything-V3.0-pruned.ckpt%22&Expires=1669857826&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzFlL2VmLzFlZWZkNTUwNzdiYWRjODdjZDE3OTg2NzJhMDU4YjhkNTVhZWFiNThlNzgxYmU4ODNmMmVjMGUwOTE3Njc5ZTMvNTQzYmNiYzIxMjk0ODMxYzYyNDVjZDc0YzhhNzcwNzc2MWUyODgxMmM2OTBmOTQ2Y2I4MWZlZjkzMGQ1NGI1ZT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0IlMjBmaWxlbmFtZSUzRCUyMkFueXRoaW5nLVYzLjAtcHJ1bmVkLmNrcHQlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2Njk4NTc4MjZ9fX1dfQ__&Signature=sYFNx6ju0tafFmerly2zjlIZtHqBcIgQX9Q1STNZVwVNzH~Ss-oXOA749TDRdQlC5A49nmGAVv7XW-B317JiVEvtHOdVww9315fENEfDdbwBXd2h0BkqLw7gLNZ5BQAZltg0JUnbITB67Eh3ZrPKQ2Ut-QMGERtNif3LEY5WnuS~bdVrP1rBJsfAQTzE~jyOXAZ1PIzFmtfj7vVMkS9LACRBbSDYXxMH4LFKOuciSQXWnTuePvUXTySbgSzi4p4TrWSkykdncLa~hu27~z7N5NelnDcyWzlRCSx73b1H6ICPvC6G6B73i~i69sN3xcDjjIaISNOKRVnk99ABNLtbwA__&Key-Pair-Id=KVTP0A1DKRTAX [following]
--2022-11-28 06:25:01--  https://cdn-lfs.huggingface.co/repos/1e/ef/1eefd55077badc87cd1798672a058b8d55aeab58e781be883f2ec0e0917679e3/543bcbc21294831c6245cd74c8a7707761e28812c690f946cb81fef930d54b5e?response-content-disposition=attachment%3B%20filename%3D%22Anything-V3.0-pruned.ckpt%22&Expires=1669857826&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzFlL2VmLzFlZWZkNTUwNzdiYWRjODdjZDE3OTg2NzJhMDU4YjhkNTVhZWFiNThlNzgxYmU4ODNmMmVjMGUwOTE3Njc5ZTMvNTQzYmNiYzIxMjk0ODMxYzYyNDVjZDc0YzhhNzcwNzc2MWUyODgxMmM2OTBmOTQ2Y2I4MWZlZjkzMGQ1NGI1ZT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0IlMjBmaWxlbmFtZSUzRCUyMkFueXRoaW5nLVYzLjAtcHJ1bmVkLmNrcHQlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2Njk4NTc4MjZ9fX1dfQ__&Signature=sYFNx6ju0tafFmerly2zjlIZtHqBcIgQX9Q1STNZVwVNzH~Ss-oXOA749TDRdQlC5A49nmGAVv7XW-B317JiVEvtHOdVww9315fENEfDdbwBXd2h0BkqLw7gLNZ5BQAZltg0JUnbITB67Eh3ZrPKQ2Ut-QMGERtNif3LEY5WnuS~bdVrP1rBJsfAQTzE~jyOXAZ1PIzFmtfj7vVMkS9LACRBbSDYXxMH4LFKOuciSQXWnTuePvUXTySbgSzi4p4TrWSkykdncLa~hu27~z7N5NelnDcyWzlRCSx73b1H6ICPvC6G6B73i~i69sN3xcDjjIaISNOKRVnk99ABNLtbwA__&Key-Pair-Id=KVTP0A1DKRTAX
Resolving cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)... 13.227.219.43, 13.227.219.41, 13.227.219.4, ...
Connecting to cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)|13.227.219.43|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3852134462 (3.6G) [binary/octet-stream]
Saving to: ‘/content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned.ckpt’

/content/stable-dif 100%[===================>]   3.59G   162MB/s    in 16s     

2022-11-28 06:25:17 (231 MB/s) - ‘/content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned.ckpt’ saved [3852134462/3852134462]

Python 3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
Commit hash: b5050ad2071644f7b4c99660dc66a8a95136102f
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for Web UI
Launching Web UI with arguments: --share --force-enable-xformers
No checkpoints found. When searching for checkpoints, looked at:
 - file /content/stable-diffusion-webui/stable-diffusion-webui/stable-diffusion-webui/model.ckpt
 - directory /content/stable-diffusion-webui/stable-diffusion-webui/stable-diffusion-webui/models/Stable-diffusion
Can't run without a checkpoint. Find and place a .ckpt file into any of those locations. The program will exit.

**Comment by okbabynhe** [comment]
This too, i guess




Cloning into 'stable-diffusion-webui'...
remote: Enumerating objects: 10956, done.
remote: Total 10956 (delta 0), reused 0 (delta 0), pack-reused 10956
Receiving objects: 100% (10956/10956), 23.71 MiB | 14.64 MiB/s, done.
Resolving deltas: 100% (7669/7669), done.
/content/stable-diffusion-webui
--2022-11-28 06:27:50--  https://huggingface.co/Linaqruf/anything-v3.0/resolve/main/Anything-V3.0-pruned.ckpt
Resolving huggingface.co (huggingface.co)... 54.147.99.175, 34.227.196.80, 2600:1f18:147f:e800:3df1:c2fc:20aa:9b45, ...
Connecting to huggingface.co (huggingface.co)|54.147.99.175|:443... connected.
HTTP request sent, awaiting response... 504 Gateway Time-out
Retrying.

--2022-11-28 06:28:51--  (try: 2)  https://huggingface.co/Linaqruf/anything-v3.0/resolve/main/Anything-V3.0-pruned.ckpt
Reusing existing connection to huggingface.co:443.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs.huggingface.co/repos/1e/ef/1eefd55077badc87cd1798672a058b8d55aeab58e781be883f2ec0e0917679e3/543bcbc21294831c6245cd74c8a7707761e28812c690f946cb81fef930d54b5e?response-content-disposition=attachment%3B%20filename%3D%22Anything-V3.0-pruned.ckpt%22&Expires=1669855444&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzFlL2VmLzFlZWZkNTUwNzdiYWRjODdjZDE3OTg2NzJhMDU4YjhkNTVhZWFiNThlNzgxYmU4ODNmMmVjMGUwOTE3Njc5ZTMvNTQzYmNiYzIxMjk0ODMxYzYyNDVjZDc0YzhhNzcwNzc2MWUyODgxMmM2OTBmOTQ2Y2I4MWZlZjkzMGQ1NGI1ZT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0IlMjBmaWxlbmFtZSUzRCUyMkFueXRoaW5nLVYzLjAtcHJ1bmVkLmNrcHQlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2Njk4NTU0NDR9fX1dfQ__&Signature=T9mklEmfS8JQyyglKA8OmWuK4y0k9unRsxBnvk2WxXHeogLi82oKQssWXo6Aeh9RgLAQkRhNXaHR-CkABH4NRhSqvt8rU3W77P5DMcq5Ffjt0h5ySqqRnQNoVoNAm~m~6q5USQX1kIl909LoA1yXfx-Ndr9EGtXequtLVc43RpZlFhopSqGwTjk9Z9eh0tXA8CzPYwhbIIRkv73mdxAh2LO0ot4rjYKI3sfigwKj3w0YpIbtQBUPtVhlgxk-R4rtvILl15KDvXP79dIOvAvFqIO7RAZu91-5qs9UIsupG0lmC8flzdWjTCdyoNUs5hGJ68pRSR-iHUgScQJf-z1ZYg__&Key-Pair-Id=KVTP0A1DKRTAX [following]
--2022-11-28 06:28:51--  https://cdn-lfs.huggingface.co/repos/1e/ef/1eefd55077badc87cd1798672a058b8d55aeab58e781be883f2ec0e0917679e3/543bcbc21294831c6245cd74c8a7707761e28812c690f946cb81fef930d54b5e?response-content-disposition=attachment%3B%20filename%3D%22Anything-V3.0-pruned.ckpt%22&Expires=1669855444&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzFlL2VmLzFlZWZkNTUwNzdiYWRjODdjZDE3OTg2NzJhMDU4YjhkNTVhZWFiNThlNzgxYmU4ODNmMmVjMGUwOTE3Njc5ZTMvNTQzYmNiYzIxMjk0ODMxYzYyNDVjZDc0YzhhNzcwNzc2MWUyODgxMmM2OTBmOTQ2Y2I4MWZlZjkzMGQ1NGI1ZT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0IlMjBmaWxlbmFtZSUzRCUyMkFueXRoaW5nLVYzLjAtcHJ1bmVkLmNrcHQlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2Njk4NTU0NDR9fX1dfQ__&Signature=T9mklEmfS8JQyyglKA8OmWuK4y0k9unRsxBnvk2WxXHeogLi82oKQssWXo6Aeh9RgLAQkRhNXaHR-CkABH4NRhSqvt8rU3W77P5DMcq5Ffjt0h5ySqqRnQNoVoNAm~m~6q5USQX1kIl909LoA1yXfx-Ndr9EGtXequtLVc43RpZlFhopSqGwTjk9Z9eh0tXA8CzPYwhbIIRkv73mdxAh2LO0ot4rjYKI3sfigwKj3w0YpIbtQBUPtVhlgxk-R4rtvILl15KDvXP79dIOvAvFqIO7RAZu91-5qs9UIsupG0lmC8flzdWjTCdyoNUs5hGJ68pRSR-iHUgScQJf-z1ZYg__&Key-Pair-Id=KVTP0A1DKRTAX
Resolving cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)... 108.156.60.112, 108.156.60.37, 108.156.60.109, ...
Connecting to cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)|108.156.60.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3852134462 (3.6G) [binary/octet-stream]
Saving to: ‘/content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned.ckpt’

/content/stable-dif 100%[===================>]   3.59G   230MB/s    in 15s     

2022-11-28 06:29:06 (242 MB/s) - ‘/content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned.ckpt’ saved [3852134462/3852134462]

Python 3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]
Commit hash: b5050ad2071644f7b4c99660dc66a8a95136102f
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Launching Web UI with arguments: --share --force-enable-xformers
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Traceback (most recent call last):
  File "launch.py", line 255, in <module>
    start()
  File "launch.py", line 250, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 149, in webui
    initialize()
  File "/content/stable-diffusion-webui/webui.py", line 84, in initialize
    modules.sd_models.load_model()
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 247, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/encoders/modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1731, in from_pretrained
    user_agent=user_agent,
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 290, in cached_path
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 585, in get_from_cache
    http_get(url_to_download, temp_file, proxies=proxies, resume_size=resume_size, headers=headers)
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 424, in http_get
    _raise_for_status(r)
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 413, in _raise_for_status
    request.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/vocab.json

**Comment by katresars** [comment]
same as yours, solved by reinstalling all the files, possibly caused by the new version of webui (git pull).

**Comment by camenduru** [comment]
because huggingface was down https://status.huggingface.co/
