### ISSUE TITLE
Do they finally stop free account leeches?

### ISSUE THREAD

**Issue by Anonimouche** [camenduru/stable-diffusion-webui-colab#401]
Tried a bunch of stable-diffusion colabs, they all end in the same way...
The VM just shuts-off. Sometimes you have time to generate 1 or 2 images but after that it's done. The machine just shuts off without any errors, without warnings, it's just gone.
My guess is that they are finally cracking down on free accounts use of those colabs but I'm not sure.

**Comment by camenduru** [comment]
https://github.com/etherealxx/volatile-concentration-localux-colab 😜

**Comment by etherealxx** [comment]
can confirms it did happened with me too. the time is just random i guess? It disconnects without warning, like, true disconnect, where you need to run everything from the start again.. the vm and all downloaded stuff is removed.

**Comment by Rush-gif** [comment]
@etherealxx the colab you provide also work only for 2 three images .

**Comment by tenrandomdigits** [comment]
One colab I was using obfuscated the word “webui” using base.64 encryption throughout the entire notebook. I’m guessing for this reason.

**Comment by WalidAliAlfaid** [comment]
> https://github.com/etherealxx/volatile-concentration-localux-colab 😜

it doesn't work when you restart the webui like when you add an extension or edit controlNet settings.
Nolan Aatama's colabs seems to be working fine though, so whatever the problem is it must be from you maybe an update you did yesterday?

**Comment by etherealxx** [comment]
@WalidAliAlfaid if there's anything wrong with my colab, would be appreciated if you give me the detailed problems on the issue page of the repo🙏
