### ISSUE TITLE
[Bug]: why colab is disconnecting   automatically.

### ISSUE THREAD

**Issue by Rush-gif** [camenduru/stable-diffusion-webui-colab#402]
### What happened?

no error is showing up .to understand.

### Colab cell output

```shell
.
```

### Which colab and model(s) were you using when the error occurred?

All models.

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

### If you used HiRes mode when the error occurred, please provide the Hires info

.

**Comment by camenduru** [comment]
https://github.com/camenduru/stable-diffusion-webui-colab/issues/401

**Comment by Rush-gif** [comment]
@camenduru It like there is no error it just disconnecting automatically and when I run it back everything restart from intial steps again it download everything and stop

**Comment by camenduru** [comment]
Hi @Rush-gif 👋 please check this link -> https://github.com/camenduru/stable-diffusion-webui-colab/issues/401

**Comment by Rush-gif** [comment]
@camenduru ok bro thanks 🙏

**Comment by camenduru** [comment]
let's keep it open

**Comment by Rush-gif** [comment]
@camenduru bro it didn't work just work for two three image

**Comment by farpit** [comment]
same here

**Comment by etherealxx** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/issues/2103
https://github.com/googlecolab/colabtools/issues/3628

**Comment by Anonimouche** [comment]
> @camenduru bro it didn't work just work for two three image

I'm actually using this colab without any issues at all, it's been 30 min so far no disconnects.

**Comment by everydoc** [comment]
I also had this problem, don't know what to do.
