### ISSUE TITLE
colab disconnect after 5 minutes or so

### ISSUE THREAD

**Issue by WalidAliAlfaid** [camenduru/stable-diffusion-webui-colab#403]
### What happened?

everything runs as usual but 5 minutes after opning the webui the colab discounnect and delete the timeline by itself 

### Colab cell output

```shell
Public WebUI Colab URL: http://jddlbr7mvvtuyy5uq7weox3f6l3flhybz3rdjozz3lzhxmemnzda.remote.moe 
Public WebUI Colab URL: https://7582203d-492b-4d7a.gradio.live 
Public WebUI Colab URL: https://65035955a993b8.lhr.life
Public WebUI Colab URL: https://impaired-served-citizenship-proportion.trycloudflare.com
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/nightly/dreamshaper_3_32_webui_colab.ipynb

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/nightly/dreamshaper_3_32_webui_colab.ipynb

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/nightly/deliberate_webui_colab.ipynb

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/nightly/dreamlike_diffusion_1_webui_colab.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by camenduru** [comment]
Hi @WalidAliAlfaid 👋 please check https://github.com/camenduru/stable-diffusion-webui-colab/issues/401
