### ISSUE TITLE
JPG format not working because old outdated automatic1111 version

### ISSUE THREAD

**Issue by elBlacksmith** [camenduru/stable-diffusion-webui-colab#41]
Hi, first of all thanks for your work. It´s nive to have a quick way to test those models

The problem that I facing is when I setup Automatic1111 to use jpg instead of PNG. I got an error on Colab and no results on the interface.
I think that it´s because your colabs are using an outdated cloned repo of Automatic1111

cheers

**Comment by elBlacksmith** [comment]
> just remove the version like this
> 
> `!git clone -b v1.6 https://github.com/camenduru/stable-diffusion-webui`
> 
> to
> 
> `!git clone https://github.com/camenduru/stable-diffusion-webui`

Hi, thanks for the quick response. I'll do it that way.

Just for corridor curiosity, are you forcing the use of a previous version for a special reason? Maybe because it's a more reliable version?
I guess that the "-b v1.6" command does that.

**Comment by camenduru** [comment]
yep not stable for colab at this time

**Comment by elBlacksmith** [comment]
> yep not stable for colab at this time

Ah, so that's why I was having problems with other colabs.

Thanks!
