### ISSUE TITLE
[Error]: Trying to use Extension Outpainting in colab

### ISSUE THREAD

**Issue by Arhadrianman10** [camenduru/stable-diffusion-webui-colab#412]
### What happened?

I have tried to install this extension:
https://github.com/zero01101/openOutpaint-webUI-extension

When installing and reloading the UI there is no problem.

In fact I am able to see the tab of the extension and open it.

![wwwwwwwwa](https://user-images.githubusercontent.com/86854034/236864432-1448fd9e-3673-422a-85d1-8de87d24cd97.PNG)

The problem is that inside the extension I get an error, this:

'Have you run the webui with the flag '--api', or is the flag '--gradio-debug' currently active?'

in the lower left corner, in a red message, (it looks a bit bad) and also it doesn't let me use the extension because it is blocked.

![Captura](https://user-images.githubusercontent.com/86854034/236864740-5a4156e0-a216-48ad-a5af-bbaf2450a9e3.PNG)

Inside the extension git they refer to this workaround as a possible solution.

https://github.com/TheLastBen/fast-stable-diffusion/discussions/1161

I understand that the first part does not apply because there is no problem but I would like to know how I can change the flag to true.
![209936885-379d83fe-2137-49d2-811e-4868323c23da](https://user-images.githubusercontent.com/86854034/236864258-6ec668bb-d34a-4704-8fd8-db383cee5657.png)

### Colab cell output

```shell
No errors in colab output
```

### Which colab and model(s) were you using when the error occurred?

All

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by camenduru** [comment]
Hi @Arhadrianman10 ❤ it is working please add --api 

![image](https://user-images.githubusercontent.com/54370274/236873785-8fed9f4b-5ff4-43a4-a3dc-e7eb362b1ac9.png)


![image](https://user-images.githubusercontent.com/54370274/236873596-4c62408c-3e15-4f0c-8aa7-28cf264af310.png)

**Comment by greatwolf** [comment]
I added `--api` but I get a bunch of validation errors for model checkpoint, options and other stuff. I wonder if it's look in the wrong place for those files. I'm testing this on colab btw: https://colab.research.google.com/drive/1hzlynbVswaFjxjPUq3rlqIGjuH_amZSV

From your screenshot it looks like the colab interface you tested that command with. How were you able to get it to work without getting those validation errors?
