### ISSUE TITLE
[Bug]: 504 Gateway Timeout

### ISSUE THREAD

**Issue by bincooo** [camenduru/stable-diffusion-webui-colab#417]
### What happened?

The WebUI generates three http links.
If 'https://xxx.gradio.live' exceeds 1 minute, '504 Gateway Timeout' appears.
I used --api /sdapi/v1/txt2img.

Perhaps the default timeout of nginx has not been changed

### Colab cell output

```shell
null
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/chillout_mix_webui_colab.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by camenduru** [comment]
Hi @bincooo 👋 please use `cloudflare` tunnel
