### ISSUE TITLE
[Bug]: The stable diffusion will disconnect in just a few minutes.

### ISSUE THREAD

**Issue by zhuzi0125** [camenduru/stable-diffusion-webui-colab#422]
### What happened?

Why is it so easy for stable diffusion cloab to disconnect now? It can't be installed for more than 2 minutes and it automatically disconnects, requiring a reinstallation

### Colab cell output

```shell
X
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/stable_diffusion_webui_colab.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by zhuzi0125** [comment]
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/43361813/a4e6e797-181e-4cab-9ef7-f73144f7cb1b)
It automatically disconnects right after installation.

**Comment by etherealxx** [comment]
https://github.com/camenduru/stable-diffusion-webui-colab/issues/405 <- Please read this first.
