### ISSUE TITLE
ERROR: xformers-0.0.17+b6be33a.d20230315-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by OguzhanUmutlu** [camenduru/stable-diffusion-webui-colab#423]
### What happened?

It gives the following error:

```ERROR: xformers-0.0.17+b6be33a.d20230315-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.```

When you run:

```pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.17/xformers-0.0.17+b6be33a.d20230315-cp39-cp39-linux_x86_64.whl```

### Colab cell output

```shell
Defaulting to user installation because normal site-packages is not writeable
ERROR: xformers-0.0.17+b6be33a.d20230315-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.
```

### Which colab and model(s) were you using when the error occurred?

Local

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by camenduru** [comment]
Hi @OguzhanUmutlu 👋 please us `pip install xformers`
