### ISSUE TITLE
[Bug]: Batch controlnet broken

### ISSUE THREAD

**Issue by Enferlain** [camenduru/stable-diffusion-webui-colab#424]
### What happened?

Use of batch controlnet in img2img. Set the settings, select controlnet, see results:

Openpose - completely blank, black detectmaps, useless

Depth - fried 
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/15861396/6b218ec3-fabb-4193-ba07-b84b4ff9756f)

Cunny - fried
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/15861396/599001f1-b7e6-4b29-8e03-1e7b77fbda8b)

The others are likely similarly broken. I tested on drive and 2 different colab notebooks so far, same results. I asked someone to test in a different notebook (nolan something) and it worked for them as it should, with the same steps I was giving.

Seems like something I'd need help with looking into so pls help

Reported about it previously [here](https://github.com/Mikubill/sd-webui-controlnet/issues/1147) in case they knew anything about it, but I feel like this place is more relevant now that I found out that it's not only on the drive instance.

### Colab cell output

```shell
Loading model from cache: control_v11f1p_sd15_depth_fp16 [4b72d323]
Loading preprocessor: depth_zoe
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 1024
raw_W = 640
target_H = 1024
target_W = 640
estimation = 640.0
```

### Which colab and model(s) were you using when the error occurred?

Any model

but https://civitai.com/api/download/models/36936

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by Enferlain** [comment]
Exact settings and steps to replicate for testing:

Controlnet settings
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/15861396/0b3887f5-824d-428c-9385-cc4649ac5dff)

img2img settings
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/15861396/70f8470d-ef48-4cca-9d53-de3587cd78da)

batch settings
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/15861396/fa1ea5e7-6c4e-4276-97e6-5cec2b4151e6)

controlnet setup
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/15861396/9c59ee18-000c-401e-8656-dbab12bba7d0)

**Comment by camenduru** [comment]
https://ezgif.com converter problem right?
