### ISSUE TITLE
🆕 A code for Kaggle to use Python 3.8, xformers and last version of Web UI

### ISSUE THREAD

**Issue by AxelFar94** [camenduru/stable-diffusion-webui-colab#43]
After a whole day in this (never worked with python before), i've managed to get a code for Kaggle to use python 3.8 (the default is 3.7) to run the last Web UI version and a new xformers version. It's possible to change "cctbx202008" to "cctbx202208" to use python 3.10 or above in the future if someone do a compatible xformers version for it.
Working nice with the new Civitai model download option.

Here:

https://www.kaggle.com/axelfar/stable-diffusion-webui-kaggle

**Comment by camenduru** [comment]
did you try this https://www.kaggle.com/code/camenduru/stable-diffusion-webui-kaggle

**Comment by camenduru** [comment]
very cool conda thanks for sharing ❤

**Comment by AxelFar94** [comment]
> did you try this https://www.kaggle.com/code/camenduru/stable-diffusion-webui-kaggle

Yes, i changed it on top of your Kaggle code and by looking on your Google Colab codes. Kaggle use Python 3.7 so it isn't possible to run the last WebUI version by default, so i had to search how to force Kaggle to change Python version, then i tested your xformers releases to find one that worked with it.

**Comment by camenduru** [comment]
moved to discord
