### ISSUE TITLE
[Bug]: The button to import previously generated images in txt2img cannot be used

### ISSUE THREAD

**Issue by mnrr01** [camenduru/stable-diffusion-webui-colab#434]
### What happened?

I want to import the image generated by txt2img before, and click the import button, but there is no effect.

### Colab cell output

```shell
Error: no "view" mailcap rules found for type "inode/directory"
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'outputs/txt2img-images'
```

### Which colab and model(s) were you using when the error occurred?

https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive

### Which Public WebUI Colab URL were you using when the error occurred?

trycloudflare.com

**Comment by camenduru** [comment]
hi @mnrr01 please use `One Time Install & Update` colab
