### ISSUE TITLE
no bug but a request .

### ISSUE THREAD

**Issue by Rush-gif** [camenduru/stable-diffusion-webui-colab#435]
### What happened?

@camenduru there is no issue but there is a request ,when you are going to update the sage maker there are some people using it right .love your work bro .so please update the sage-maker repository

### Colab cell output

```shell
.
```

### Which colab and model(s) were you using when the error occurred?

.

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

### If you used HiRes mode when the error occurred, please provide the Hires info

.

**Comment by camenduru** [comment]
maybe solved please check our discord
