### ISSUE TITLE
[Bug]: sd-webui colab stops executing around the end without showing any consistent error!

### ISSUE THREAD

**Issue by zucced** [camenduru/stable-diffusion-webui-colab#453]
### What happened?

The notebook executes till around the end then stops out of nowhere and without any consistent error, It used to work just fine, but not anymore.

![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/139365342/85e59136-12ae-4d64-bb71-536f07d4d9f2)

### Colab cell output

```shell
Status Legend:
(OK):download completed.
Python 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into /content/stable-diffusion-webui/repositories/taming-transformers...
Cloning K-diffusion into /content/stable-diffusion-webui/repositories/k-diffusion...
Cloning CodeFormer into /content/stable-diffusion-webui/repositories/CodeFormer...
Cloning BLIP into /content/stable-diffusion-webui/repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Installing Deforum requirement: av
Installing Deforum requirement: pims

Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore



Installing rembg
Installing onnxruntime for REMBG extension
Installing pymatting for REMBG extension


Installing pycloudflared

Downloading pose_landmark_full.tflite...
Downloading pose_web.binarypb...
Downloading pose_solution_packed_assets.data...
Downloading pose_solution_simd_wasm_bin.wasm...
Downloading pose_solution_packed_assets_loader.js...
Downloading pose_solution_simd_wasm_bin.js...

Installing requirements for CivitAI Browser

sed: can't read /content//repositories/stable-diffusion-stability-ai/ldm/util.py: No such file or directory
Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
2023-07-12 15:58:18.887365: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/majicmix_realistic_webui_colab.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by etherealxx** [comment]
if you're a free colab user, that's normal (and that sucks i know). Use other [community colabs](https://github.com/camenduru/stable-diffusion-webui-colab/tree/community) as an alternative.

**Comment by zucced** [comment]
> if you're a free colab user, that's normal (and that sucks i know). Use other [community colabs](https://github.com/camenduru/stable-diffusion-webui-colab/tree/community) as an alternative.

But why was it working just fine until yesterday, and trying to run the same notebook code in one of those community colabs produce the same case, it stops executing..

**Comment by etherealxx** [comment]
@zucced try this one https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb

**Comment by aniketyevankar** [comment]
wow! this actually worked! Thank you. @etherealxx
