### ISSUE TITLE
[Bug]: ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py)

### ISSUE THREAD

**Issue by seeklake** [camenduru/stable-diffusion-webui-colab#454]
### What happened?

![2681689218375_ pic](https://github.com/camenduru/stable-diffusion-webui-colab/assets/33951364/025b5b88-6085-44c7-9560-577be97c2db5)

ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py)

### Colab cell output

```shell
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py)
```

### Which colab and model(s) were you using when the error occurred?

ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py)

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by etherealxx** [comment]
Hi👋
On this line, add this text and please try again
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/64251396/01197da5-56a1-4414-a236-4b762e390dd2)

**Comment by seeklake** [comment]
Thank you very much, this method is available and has been used normally
