### ISSUE TITLE
[Bug]: I get an error when the webui is about to launch

### ISSUE THREAD

**Issue by xHeadshotbtw** [camenduru/stable-diffusion-webui-colab#458]
### What happened?

The notebook worked fine few hours ago but i had to restart it to download another model (edit the code a bit to add a link to a custom model), then I got an error so i retried without the editing the notebook and still the same error.
I created a new notebook and cloned the repo then run it but it doesn't seem to fix the issue.
(I removed controlnet that's why the output below is different)

### Colab cell output

```shell
Status Legend:
(OK):download completed.
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into /content/stable-diffusion-webui/repositories/taming-transformers...
Cloning K-diffusion into /content/stable-diffusion-webui/repositories/k-diffusion...
Cloning CodeFormer into /content/stable-diffusion-webui/repositories/CodeFormer...
Cloning BLIP into /content/stable-diffusion-webui/repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI

Installing Deforum requirement: av
Installing Deforum requirement: pims

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x56100a23b740
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/abyss_orange_mix_3_webui_colab.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by closemike58** [comment]
Same problem, same error code "src/tcmalloc.cc:283] Attempt to free invalid pointer 0x56100a23b740" with routine running of "run" cell.

**Comment by GrowD7** [comment]
Same problem here, pc crashed 2 hours ago and since i have the same problem and can't launch the colab.

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5a25724cf740

**Comment by IviSoftware** [comment]
same problem, i try add the next line 
!pip install https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/c/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl
but  it does not work 🤡

**Comment by GrowD7** [comment]
seen the same problem on reddit, we all lost it at approximately the same time so my guess is something has broken in the code or something he use. Hope they us quickly :)

**Comment by Nightee1** [comment]
I'm having the same problem, is there a solution for this? I did the update and it still didn't work

**Comment by ariraz513** [comment]
same

**Comment by etherealxx** [comment]
please check the latest colab update🙏

and if you use the drive one, remove these lines
![image](https://github.com/camenduru/stable-diffusion-webui-colab/assets/64251396/c9958d92-42b4-4a92-b8e9-871ea2c355a4)

**Comment by GrowD7** [comment]
Thanks after updating it works great again, thx for your reactivity
