### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 6h0s70n3** [camenduru/stable-diffusion-webui-colab#459]
### What happened?

When I click on "execute all" everything goes fine until I get to "Start Stable-Diffusion" and the notebook stops showing the following error message

src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5748aed639d0 

### Colab cell output

```shell
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5bc51e8039d0
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=PjzwxTkPSPHf

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by Jeffgrey91** [comment]
yes same thing happening here, only started happening today.

**Comment by etherealxx** [comment]
@6h0s70n3 I think you're using ThrLastBrn colab there? You should submit an issue to that repo instead.

Though you can check this solution https://github.com/camenduru/stable-diffusion-webui-colab/issues/458 to see if it also works for this scenario.

**Comment by Index98** [comment]
use new run.ipynb version

**Comment by Jeffgrey91** [comment]
@etherealxx using camenduru's

**Comment by camenduru** [comment]
maybe fixed please try again
