### ISSUE TITLE
How to use the API interface to call the service

### ISSUE THREAD

**Issue by shanhouwang** [camenduru/stable-diffusion-webui-colab#460]
### What happened?

How to use the API interface to call the service

### Colab cell output

```shell
How to use the API interface to call the service
```

### Which colab and model(s) were you using when the error occurred?

How to use the API interface to call the service

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

### If you used HiRes mode when the error occurred, please provide the Hires info

How to use the API interface to call the service

**Comment by camenduru** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API
