### ISSUE TITLE
[Bug]: Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple src/tcmalloc.cc:283] Attempt to free invalid pointer 0x59570a899740 

### ISSUE THREAD

**Issue by seeklake** [camenduru/stable-diffusion-webui-colab#463]
### What happened?

Installing requirements for CivitAI Browser

Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore

Installing pycloudflared

Installing rembg
Installing onnxruntime for REMBG extension
Installing pymatting for REMBG extension

Installing sd-dynamic-prompts requirements.txt

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x59570a899740 

### Colab cell output

```shell
Installing requirements for CivitAI Browser

Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore


Installing pycloudflared


Installing rembg
Installing onnxruntime for REMBG extension
Installing pymatting for REMBG extension

Installing sd-dynamic-prompts requirements.txt

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x59570a899740
```

### Which colab and model(s) were you using when the error occurred?

Installing requirements for CivitAI Browser

Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore

Installing pycloudflared

Installing rembg
Installing onnxruntime for REMBG extension
Installing pymatting for REMBG extension

Installing sd-dynamic-prompts requirements.txt

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x59570a899740 

### Which Public WebUI Colab URL were you using when the error occurred?

remote.moe

**Comment by seeklake** [comment]
Could you please help me see what the problem is

**Comment by etherealxx** [comment]
Hi👋, please read this: https://github.com/camenduru/stable-diffusion-webui-colab/issues/458 and tell me if the solution works.

**Comment by seeklake** [comment]
Thank you very much，remove these lines，THE job is good
