### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MultiPointMP** [camenduru/stable-diffusion-webui-colab#465]
### What happened?

Nothing happens, but this error is frequently encountered at the colab runtime

### Colab cell output

```shell
RuntimeError: File at path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-3d-open-pose-editor/pages/theme/default/layer.css does not exist.
```

### Which colab and model(s) were you using when the error occurred?

https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by etherealxx** [comment]
can you delete the entire /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-3d-open-pose-editor folder first then restart, and reinstall the extension?

**Comment by camenduru** [comment]
Please try the new version
