### ISSUE TITLE
Error, Bugs and Crashes since the latest update

### ISSUE THREAD

**Issue by RealKibate** [camenduru/stable-diffusion-webui-colab#47]
Hi. I'm new here, so sorry if I don't say or mention the right thing, or even if this is the right place to talk about this.
Anyway, I've been enjoying a lot the stable diffusion google colab models here, I have to give a huge thanks to camenduru for providing these.
However since the latest update(I assume it was the latest), the one where the UI was also changed from the webapp, I've gotten, as the title says, constant errors, bugs and crashes when trying to render images.  It can happen at any time, but the most promiment crashes happen when I try to img2img with a resolution higher than 512x512.
From the preview images it seems like everything is working fine, but right after the print code says "100%" this error pops up and the preview images are replaced with nothing:
```
Error completing request
Arguments: ('task(n5lc4gwju3l7vet)', 0, '[1 girl][sweatpants]', '', 'None', 'None', <PIL.Image.Image image mode=RGBA size=768x768 at 0x7F2E46600850>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 4, 7, 0.5, -1.0, -1.0, 0, 0, 0, False, 768, 768, 0, 0, 32, 0, '', '', 0, False, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'Refresh models', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, '<p style="font-weight:bold;margin-bottom:0.75em">Deforum v0.5-webui-beta</p>', '<p>This script is deprecated. Please use the full Deforum extension instead.<br>\nUpdate instructions:</p>', '<p>github.com/deforum-art/deforum-for-automatic1111-webui/blob/automatic1111-webui/README.md</p>', '<p>discord.gg/deforum</p>') {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/img2img.py", line 148, in img2img
    processed = process_images(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 480, in process_images
    res = process_images_inner(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 613, in process_images_inner
    devices.test_for_nans(x, "vae")
  File "/content/stable-diffusion-webui/modules/devices.py", line 136, in test_for_nans
    raise NansException(message)
modules.devices.NansException: A tensor with all NaNs was produced in VAE. This could be because there's not enough precision to represent the picture. Try adding --no-half-vae commandline argument to fix this.
```
And no, using --no-half-vae doesn't work, it changes nothing whatsoever.
Sometimes I can still try to generate another image, another times the app in the current browser tab stops responding when clicking on "Generate" and sometimes, and sometimes it breaks down all together, where even refresh doesn't work.

Is there a way to fix this, or at least to go back to the previous version that worked like 99.9% of the time?
Oh, and I don't know if this is important, but I've been using "Anything 3" stable diffusion .

**Comment by camenduru** [comment]
this is the way to go back to the old version
`!git clone https://github.com/camenduru/stable-diffusion-webui`
to this 
`!git clone -b v1.6 https://github.com/camenduru/stable-diffusion-webui`
please try this and tell me if it works.

**Comment by RealKibate** [comment]
Thanks, but that doesn't do anything, both the UI and the errors are the same.
