### ISSUE TITLE
[Bug]:  Attempt to free invalid pointer 0x5c0e13b646b0 

### ISSUE THREAD

**Issue by alelordelo** [camenduru/stable-diffusion-webui-colab#470]
### What happened?

Updated to latest Colab using the "Install" repo.
Tried build the "run" Colab
got this error: src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5c0e13b646b0 

### Colab cell output

```shell
Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --clip-models-path /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/models/CLIP --ckpt-dir /content/fused-models --lora-dir /content/fused-lora --multiple
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5c0e13b646b0
```

### Which colab and model(s) were you using when the error occurred?

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/drive/run.ipynb

### Which Public WebUI Colab URL were you using when the error occurred?

gradio.live

**Comment by etherealxx** [comment]
Hi👋, please read this: https://github.com/camenduru/stable-diffusion-webui-colab/issues/458 and tell me if the solution works.

**Comment by alelordelo** [comment]
I updated  with the “one install and update” repo but didn’t work.Sent from my iPhoneOn 5 Aug 2023, at 08:35, Etherealxx ***@***.***> wrote:﻿
Hi👋, please read this: #458 and tell me if the solution works.

**Comment by camenduru** [comment]
Please try the new version
