### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by yesyeahvh123** [camenduru/stable-diffusion-webui-colab#48]
hello sir, how can i make the interface look cleaner like this, thanks
![Capture](https://user-images.githubusercontent.com/69633089/213464662-a5758d01-b655-45fb-996c-1e55755416f9.PNG)

**Comment by Siddhanta01** [comment]
> hello sir, how can i make the interface look cleaner like this, thanks ![Capture](https://user-images.githubusercontent.com/69633089/213464662-a5758d01-b655-45fb-996c-1e55755416f9.PNG)

This version of the ui is not stable. That's why the repo creator reverted the update. Just wait up until the ui version goes stable and the repo owner will update it. Rest assured, this repo deserves more love! such a great initiative.

**Comment by qwertea** [comment]
If you really need it, change:
```
!git clone -b v1.6 https://github.com/camenduru/stable-diffusion-webui
```
with:
```
!git clone https://github.com/camenduru/stable-diffusion-webui
```
Then add these lines after `%cd /content/stable-diffusion-webui`:
```
!git checkout d8f8bcb
!sed -i 's/gradio==3.15.0/gradio==3.13.0/g' requirements.txt requirements_versions.txt
```
That's the latest version which works with old gradio and doesn't freeze.

**Comment by yesyeahvh123** [comment]
@qwertea thank you this is what i needed, the new version results in general i feel better than the old version but the preview image is showing error, even though the image is creating but it doesn't show anything

**Comment by qwertea** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6898#issuecomment-1399276325

The issues are possibly fixed now if we use that option.

**Comment by yesyeahvh123** [comment]
@qwertea how to do it? im new here, thanks

**Comment by camenduru** [comment]
lets wait https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6898#issuecomment-1399293529
https://github.com/gradio-app/gradio/issues/2980
https://github.com/gradio-app/gradio/pull/3022

**Comment by yesyeahvh123** [comment]
@camenduru i see everything working fine when replacing Gradio with Localtunnel

**Comment by camenduru** [comment]
Hi @yesyeahvh123 👋 please teach us how we can use Localtunnel?

**Comment by yesyeahvh123** [comment]
@camenduru i don't know but i use TheLastBen's repository with option Use LocalTunnel instead of Gradio and it works fine, live preview no problem

**Comment by etherealxx** [comment]
> Hi @yesyeahvh123 👋 please teach us how we can use Localtunnel?

i use this on my colab
```
import time
!npm install -g localtunnel

%cd /content/stable-diffusion-webui/
!nohup lt -p 7860 > lt.log 2>&1 &  
time.sleep(2)
with open('/content/stable-diffusion-webui/lt.log', 'r') as testwritefile:
  print("\033[92m" + "Wait for the model to load and follow this link")
  print(testwritefile.read())
  print("\033[95m")
!python launch.py --xformers
```

**Comment by yesyeahvh123** [comment]
i found the problem was in Gradio, so when i switch to use localTunnel or ngrok everything works fine you can add these 2 connection options

**Comment by qwertea** [comment]
localtunnel is currently broken, I personally just switched to --gradio-queue and it hasn't given me any issues since with heavy usage

**Comment by yesyeahvh123** [comment]
@qwertea how, i'm new, where do i fix the code

**Comment by camenduru** [comment]
Hi everyone👋 please test
