### ISSUE TITLE
how to add different SD Checkpoints?

### ISSUE THREAD

**Issue by Surlix** [camenduru/stable-diffusion-webui-colab#49]
Hello Camenduru, 

Thanks a lot for the Colab Collection, it's a really pleasant experience, especially for those without good graphics cards.

I wanted to run SD with different checkpoints, in detail DreamShaper3.3([HuggingFace](https://huggingface.co/Lykon/DreamShaper)|[CivitAI](https://civitai.com/models/4384/dreamshaper)) and DungeonsAndDiffusion([HuggingFace](https://huggingface.co/0xJustin/Dungeons-and-Diffusion)|[Checkpoint](https://huggingface.co/0xJustin/Dungeons-and-Diffusion/blob/main/D%26Diffusion3.0_Protogen.ckpt))

(not both at the same time)

i tried editing a notbook and changed the links for the *.ckpt, but that did not work :/

Any easy way to get a specific checkpoint working without the need to download it during a running Notebook?

Cheers!

**Comment by etherealxx** [comment]
afaik there's a civitai extension tab, go to that tab on webui, and search for the model you need.

![image](https://user-images.githubusercontent.com/64251396/213665630-5e9d530b-917a-4aa2-b6d5-4ceaf521471b.png)
make sure for huggingface model, you need to right click that arrow beside the lfs image, then click `copy link address` for the actual link

**Comment by megazaz80** [comment]
CivitAI down
![IMG_20230120_195120566](https://user-images.githubusercontent.com/70824762/213782411-7dcf3c2d-0184-43a4-81a7-da48c630af79.jpg)
