### ISSUE TITLE
Is it possible to launch automatic1111 in API mode on colab?

### ISSUE THREAD

**Issue by ForceConstant** [camenduru/stable-diffusion-webui-colab#54]
I see there are some tools that connect to webui API to access Stable Diffusion remotely, so I was seeing if this would be possible with these scripts. Since you launch with launch.py, and the gradio server gets created in there, but doesn't when using --api. Do you know an easy way to create an external link for the API?

**Comment by camenduru** [comment]
yes possible you need add `--api` and if it is website you should also add `--cors-allow-origins=*` and you can see the api doc like this  `https://---------.gradio.app/docs`
