### ISSUE TITLE
Ran out of input

### ISSUE THREAD

**Issue by SenaKaito** [camenduru/stable-diffusion-webui-colab#56]
Hii sir, nice work and thank you!

Btw, I got this error this morning.
Using AOM2 model.
Any solution?

Thanks!

![image](https://user-images.githubusercontent.com/47252962/214200822-d193ae96-f039-441c-82f1-ed908bba95dc.png)

**Comment by camenduru** [comment]
https://huggingface.co/Linaqruf/anything-v3.0 delete the model I will fix it thanks for the info ❤

**Comment by camenduru** [comment]
please try again

**Comment by SenaKaito** [comment]
Problem solved!
Thank you so much.
(〃￣︶￣)人(￣︶￣〃)
