### ISSUE TITLE
"xformers is not a supported wheel on this platform"

### ISSUE THREAD

**Issue by Mar0xy** [camenduru/stable-diffusion-webui-colab#6]
everytime I run the colab now it throws
"ERROR: xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform."

**Comment by F3N0mz** [comment]
Also got this issue, seems that xformers build got bonked somehow.

**Comment by Mar0xy** [comment]
I have built a new XFormer wheel which you can get here:
https://github.com/Mar0xy/xformer-colab/releases/download/0.0.15/xformers-0.0.15.dev0+1515f77.d20221130-cp38-cp38-linux_x86_64.whl

**Comment by camenduru** [comment]
cool thanks @Mar0xy ❤

**Comment by Mar0xy** [comment]
Gonna close this now as I have seen that everything was update :ok_hand:
