### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by CoolSave** [camenduru/stable-diffusion-webui-colab#63]
Hi sir, i notice some Loras only works with the last version of the extension Sd-webui-additional networks, i try to update the extension in the colab, but can't. You mind update that ? Or how can i update the extension ?. Thanks in advance, and sorry for my bad eng.

**Comment by camenduru** [comment]
please first change this
`!git clone -b v1.6 https://github.com/camenduru/stable-diffusion-webui `  
to this
`!git clone https://github.com/camenduru/stable-diffusion-webui ` 
 

 then change this 
 `https://github.com/camenduru/sd-webui-additional-networks` 
 to this 
 `https://github.com/kohya-ss/sd-webui-additional-networks`

**Comment by CoolSave** [comment]
Thanks. For the second changue, i only need to changue the URL, and the path let the same, right ?

**Comment by camenduru** [comment]
just URL I made the path  same `models/lora`

**Comment by CoolSave** [comment]
Works perfectly, but now in the Civitai extension when i select a model it dont show the URL, and the download fail. I can update that extension by the same way ? or this problem have another solution? (I know i can put the models manually, but that take long to load, extension its the fastest way for that). Thanks in advance again.

**Comment by camenduru** [comment]
Do the same thing for https://github.com/camenduru/sd-civitai-browser to https://github.com/Vetchems/sd-civitai-browser
