### ISSUE TITLE
📕 How to use latest version?

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#67]
Please select `v2.0` from `switch branches/tags`

https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0

![Screenshot 2023-02-02 185650](https://user-images.githubusercontent.com/54370274/216375296-a2197999-bacc-47c1-9306-07194a1cf0ad.jpg)

**Comment by etherealxx** [comment]
is there any reason that makes you stay on v1.6 on the main branch?

**Comment by SenaKaito** [comment]
> a little question, is there any reason that makes you stay on v1.6 on the main branch?

For me, I found the latest version is unstable for now. After I generated images, generate button is not working after that (it can be clicked, but no processing), so I need to duplicate/re-open gradio tab. And doing over and over again when that generate button stuck.

**Comment by etherealxx** [comment]
> > a little question, is there any reason that makes you stay on v1.6 on the main branch?
> 
> For me, I found the latest version is unstable for now. After I generated images, generate button is not working after that (it can be clicked, but no processing), so I need to duplicate/re-open gradio tab. And doing over and over again when that generate button stuck.

ah yes, sometimes also restart ui doesn't work.

**Comment by 9Somboon** [comment]
> > > a little question, is there any reason that makes you stay on v1.6 on the main branch?
> > 
> > 
> > For me, I found the latest version is unstable for now. After I generated images, generate button is not working after that (it can be clicked, but no processing), so I need to duplicate/re-open gradio tab. And doing over and over again when that generate button stuck.
> 
> ah yes, sometimes also restart ui doesn't work.

same

**Comment by etherealxx** [comment]
@9Somboon yeah, i noticed that too lately (on v2.0).

**Comment by camenduru** [comment]
https://github.com/gradio-app/gradio/pull/3022

**Comment by camenduru** [comment]
@9Somboon please try without queue maybe works https://github.com/gradio-app/gradio/issues/2980
