### ISSUE TITLE
Additional Network not showing model Downloaded

### ISSUE THREAD

**Issue by Notme227** [camenduru/stable-diffusion-webui-colab#71]
![screenshotanyv3](https://user-images.githubusercontent.com/113231355/216049616-7dd5dac8-8fc5-481a-8775-14d2b0cc6f10.png)
I downloaded model in Civitai and Checked File in Colab,but I get on to Additional network,set enabled and refresh model,it won't show the model

**Comment by Notme227** [comment]
> thanks for the notify @Notme227 ❤ please try again

try 2,3 times ,same result

**Comment by camenduru** [comment]
please click this and try again  
![Screenshot 2023-02-01 162553](https://user-images.githubusercontent.com/54370274/216055785-e04bcd54-1b16-463d-bee6-f1993ca3c1f6.jpg)
