### ISSUE TITLE
How to add and select VAE ?

### ISSUE THREAD

**Issue by xMikami** [camenduru/stable-diffusion-webui-colab#76]
Hi, a little help ? lets say i want to use the Waifu difussion VAE in the v2,0 Anything v4.5 colab, is there a way to do that ? I tried for myself adding a line like this: !wget https://huggingface.co/hakurei/waifu-diffusion-v1-4/blob/main/vae/kl-f8-anime2.ckpt -O /content/stable-diffusion-webui/models/VAE/kl-f8-anime2.ckpt but that didnt work, when i go to settings to select the VAE it give me an error

**Comment by camenduru** [comment]
please try this 
```py
!wget https://huggingface.co/ckpt/waifu-diffusion-v1-4/resolve/main/kl-f8-anime2.ckpt -O /content/stable-diffusion-webui/models/Stable-diffusion/anything-v4.5-pruned.vae.pt
```

**Comment by xMikami** [comment]
that seems to work, it let me select without errors, but when select it show me 3 options : Automatic, None, and now anything-v4.5-pruned.vae.pt, that last one is the new VAE i add ? its the waifu diffusion VAE but with that name ?

**Comment by camenduru** [comment]
yes, if we make vae same name with model, webui auto uses that vae
