### ISSUE TITLE
Extension download

### ISSUE THREAD

**Issue by yesyeahvh123** [camenduru/stable-diffusion-webui-colab#78]
hi, can you add an extension that has the function of enter download links and choosing a folder to save right on web ui, because every time you need to download more vae, the model, lora...other is not in civitai, you need to turn off webui and run the wget command

**Comment by camenduru** [comment]
thanks for the idea @yesyeahvh123 we have now `Colab Run Command` inside Hugging Face extension 
![Screenshot 2023-02-04 154822](https://user-images.githubusercontent.com/54370274/216768843-fcac90a9-daf1-4a0b-99ff-30144a616f03.jpg)
