### ISSUE TITLE
There is an error in the "generation" button

### ISSUE THREAD

**Issue by I-Zin-I** [camenduru/stable-diffusion-webui-colab#8]
After a while using any of the collaborations, the image generation button is stuck on skip/stop, no option, you need to refresh the page to make it work again, but all the settings and prompts are erased, so after configuring everything again, the error keeps happening, this is a bit annoying and tiring.

Hope this can be fixed and thanks for your work!!

**Comment by camenduru** [comment]
Thanks ♥️ I will check and there is a restart in the settings yellow button
