### ISSUE TITLE
anyv4 outputting desaturated images

### ISSUE THREAD

**Issue by subby2006** [camenduru/stable-diffusion-webui-colab#81]
The anything v4 model isn't outputting images as expected, when used with the example prompts for the model I get an image that looks similar to the example images but they're desaturated. I've checked through the discussions tab on the huggingface repo and they all say to import the vae but the colab script should already be importing it. Is there anything that I'm doing wrong here?

**Comment by camenduru** [comment]
settings SD VAE select the VAE then click apply settings
