### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by nephistar20** [camenduru/stable-diffusion-webui-colab#82]
extensions/sd-webui-additional-networks/models/lora/Kobeni/kobeni_v10.safetensors successfully downloaded.
LoRA weight: 1, model: kobeni_v10(c8c9ae92)
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 338, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 177, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 73, in create_network_and_apply_compvis
    network_dim = min([s for s in size if s > 1])
ValueError: min() arg is an empty sequence

I tried downloading in civit ai extension and tried in aditonal network when generating image, the loras can't work, how to solve it?

**Comment by camenduru** [comment]
Hi @nephistar20 👋 is this v2.0 which colab is this

**Comment by camenduru** [comment]
please try this  https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0

**Comment by nephistar20** [comment]
> Hi @nephistar20 👋 is this v2.0 which colab is this 

The main one v1.6

**Comment by nephistar20** [comment]
> please try this  https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0

Okay tysm! 😊
