### ISSUE TITLE
Run Command not working on v1.6 version

### ISSUE THREAD

**Issue by Cherryblossomoflove** [camenduru/stable-diffusion-webui-colab#83]
What the title says ^

**Comment by camenduru** [comment]
hi @Cherryblossomoflove 👋 looks like commands are working with v1.6
![Screenshot 2023-02-08 001810](https://user-images.githubusercontent.com/54370274/217367934-a9a0e691-f39c-4cd7-844f-f678af2eb9c2.jpg)

**Comment by Cherryblossomoflove** [comment]
![image](https://user-images.githubusercontent.com/123427184/217660054-643ea90d-be25-4b18-afed-0490998f6927.png)

**Comment by etherealxx** [comment]
@Cherryblossomoflove why does a safetensors file is on embeddings folder😅

**Comment by etherealxx** [comment]
@camenduru i think you mean EasyNegative.pt on that link?

**Comment by camenduru** [comment]
oops

**Comment by Cherryblossomoflove** [comment]
> @Cherryblossomoflove why does a safetensors file is on embeddings folder😅

idk, I was wondering why it was safetensors file

**Comment by baooduy** [comment]
> @camenduru i think you mean EasyNegative.pt on that link?

I don't think there's a .pt version of EasyNegative? It only have .safetensors version and the owner said put it in the embeddings folder

**Comment by etherealxx** [comment]
> > @camenduru i think you mean EasyNegative.pt on that link?
> 
> I don't think there's a .pt version of EasyNegative? It only have .safetensors version and the owner said put it in the embeddings folder

do you have a local installation? can you do that in your local installation?

**Comment by baooduy** [comment]
No i only use colab version, i think it works in local tho

**Comment by etherealxx** [comment]
> No i only use colab version, i think it works in local tho

![image](https://user-images.githubusercontent.com/64251396/218287509-6c93edd2-2d38-4d87-8e1d-91f12aa47dc3.png)
nah it doesn't.

**Comment by etherealxx** [comment]
> No i only use colab version, i think it works in local tho

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f9706acf431f77e0ce9e4270e5be7299922ee963 found the problem. The webui fork used for these colab might doesn't support loading safetensors yet.

**Comment by baooduy** [comment]
> [AUTOMATIC1111/stable-diffusion-webui@f9706ac](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f9706acf431f77e0ce9e4270e5be7299922ee963) found the problem. The webui fork used for these colab might doesn't support loading safetensors yet.

Weird, the current version can't use safetensors embeddings but older version can, I don't remember what version is it but without `-b v1.6` they works fine
