### ISSUE TITLE
SD CivitAit Browser not working

### ISSUE THREAD

**Issue by elBlacksmith** [camenduru/stable-diffusion-webui-colab#84]
Hi,

the mentioned extension for downloading from CivitAI is not working properly. I guess that there was some change.
I tried this fork, and it works: https://github.com/axsddlr/sd-civitai-browser

**Comment by etherealxx** [comment]
Can confirm, but that fork also has some [problems](https://github.com/Vetchems/sd-civitai-browser/issues/6).

**Comment by etherealxx** [comment]
try [this fork](https://github.com/etherealxx/sd-civitai-browser).

**Comment by camenduru** [comment]
thanks @etherealxx ❤

**Comment by camenduru** [comment]
Hi @etherealxx 👋 is it possible to add something like this https://github.com/camenduru/sd-civitai-browser/pull/2 other then `update_info = gr.Button(value='1st - Get Model Info')`

**Comment by etherealxx** [comment]
> Hi @etherealxx 👋 is it possible to add something like this [camenduru/sd-civitai-browser#2](https://github.com/camenduru/sd-civitai-browser/pull/2) other then `update_info = gr.Button(value='1st - Get Model Info')`

maybe i'll figure it out. in the meantime, check out this [branch that supports LORA](https://github.com/etherealxx/sd-civitai-browser/tree/lora). 
![image](https://user-images.githubusercontent.com/64251396/217612190-b6432f27-0b62-464e-94be-98e1c4039acc.png)

For your colab, tick that `additional-networks` box. Hope things doesn't break.

**Comment by camenduru** [comment]
thanks @etherealxx ❤ it is working great 🎉 I merged your lora to v2.0 and main to v1.6
