### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by YurDu65** [camenduru/stable-diffusion-webui-colab#86]
![11](https://user-images.githubusercontent.com/58310323/218136235-4aa84767-5daf-4e1a-9ed0-583dc846a715.png)

**Comment by dpapadam** [comment]
I second this also not launching same error. Cannot add middleware after an app has started. Also tried v2 as well as clicking on the stable_diffusion_v2 links

**Comment by YurDu65** [comment]
> I second this also not launching same error. Cannot add middleware after an app has started. Also tried v2 as well as clicking on the stable_diffusion_v2 colab links

Same here, a second ago everything was fine, until it just decided not to launch anymore

**Comment by dpapadam** [comment]
Did you just subscribe to the paid subscription ? I used it all night, then ran out of compute points. Then subscribed, after I subcribed I get the middleware compile error. Did you follow the same route per chance ? Wondering if it's related.

**Comment by YurDu65** [comment]
nah, im just on free one, it was right before this crashes a bit cluncky, had to restart multiple times bc it wont generate and just stop. so i dont really know what it is related with, but i think it may be with some sort of update, and those who are starting now have the same issue, but i can be wrong

**Comment by dpapadam** [comment]
ok phew so looks like it's something on their end. Guess we have to wait sigh :(

**Comment by YurDu65** [comment]
we will see, but as i said, i could be wrong, my mate is checking is it working on his pc or not, as soon as i will hear from him i will give an update

**Comment by YurDu65** [comment]
so he has the same issue, i guess we need to wait a little, most likely something on their side

**Comment by camenduru** [comment]
maybe we should downgrade fastapi

**Comment by dpapadam** [comment]
Hi there camenduru ! Thank you very much for this repo since we have you in thread :)

**Comment by camenduru** [comment]
Name: fastapi
Version: 0.91.0
Summary: FastAPI framework, high performance, easy to learn, fast to code, ready for production
Home-page: 
Author: 
Author-email: Sebastián Ramírez <[tiangolo@gmail.com](mailto:tiangolo@gmail.com)>
License: 
Location: /usr/local/lib/python3.8/dist-packages
Requires: pydantic, starlette
Required-by: gradio

**Comment by camenduru** [comment]
lets try 0.90.0

**Comment by dpapadam** [comment]
Is that something for us to do is that from your end ?

**Comment by camenduru** [comment]
`!pip install fastapi==0.90.0 -U`

**Comment by YurDu65** [comment]
![image](https://user-images.githubusercontent.com/58310323/218144056-67863070-ffa2-4bc0-964e-91d594694fd4.png)

**Comment by YurDu65** [comment]
i should put it here?

**Comment by dpapadam** [comment]
Yah was thinking the same:

!pip install -q https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.16/xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl
!pip install -q --pre triton
!pip install fastapi==0.90.0 -U

**Comment by YurDu65** [comment]
okay, thanks! i will try

**Comment by YurDu65** [comment]
![image](https://user-images.githubusercontent.com/58310323/218145366-78c06c09-d1e7-4302-a21d-2d39580945bc.png)
Works for me

**Comment by YurDu65** [comment]
Thank you for your help camenduru!

**Comment by dpapadam** [comment]
Works with 2_1 as well, testing first img2img now. Thanks as well Camenduru !

**Comment by camenduru** [comment]
please check again I added `!sed -i '$a fastapi==0.90.0' requirements_versions.txt`

**Comment by dpapadam** [comment]
sup sup testing..

**Comment by etherealxx** [comment]
thank you for being fast. This problem also happened on my local installation.

**Comment by dpapadam** [comment]
Compiling on 2_1... Since we've got you camenduru if you don't mind, what do you recommend ? Default or V2 branch ? 1_4 2_0 or 2_1 version ?

**Comment by dpapadam** [comment]
Oh it doesn't work for the others yet.. fails on 2_1 unless you add the 

!pip install fastapi==0.90.0 -U

**Comment by dpapadam** [comment]
camenduru: hmm seems to fail unless you specify the
!pip install fastapi==0.90.0 -U

(same middleware error)

This was on the v1_4 default branch now

**Comment by camenduru** [comment]
Hi @dpapadam 👋 it looks like working please try again
