### ISSUE TITLE
How do I fix it?  502 Bad Gateway

### ISSUE THREAD

**Issue by ninebluestudio** [camenduru/stable-diffusion-webui-colab#90]
Version: anything_3_webui_colab.ipynb
-------------------------------------------------
Traceback (most recent call last):
  File "launch.py", line 299, in <module>
    start()
  File "launch.py", line 292, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 163, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started
-------------------------------------------------------------------------------------
How do I fix it?  502 Bad Gateway..
![1676085470848](https://user-images.githubusercontent.com/7386143/218236713-7a704982-216c-47d6-8e70-85b6050e2c2f.jpg)
![1676085456795](https://user-images.githubusercontent.com/7386143/218236718-05145171-0684-46e1-b5ea-cad8d936a13c.jpg)

**Comment by etherealxx** [comment]
make sure to use the latest version from this repo. it should fix that problem

**Comment by ninebluestudio** [comment]
Thanks! Now it's working!
