### ISSUE TITLE
🆕 New Community Colabs ❤

### ISSUE THREAD

**Issue by camenduru** [camenduru/stable-diffusion-webui-colab#94]
Now we have cool 🔥 community colabs 🥳 please try it 🐣 select `community` from `switch branches/tags` 

![Screenshot 2023-02-12 113244](https://user-images.githubusercontent.com/54370274/218300944-a6c67c6a-92a9-441e-84c5-c0f72edf53dd.jpg)

**Comment by MACAUQGIRL** [comment]
女孩
