### ISSUE TITLE
Suggestion protogen nova model

### ISSUE THREAD

**Issue by alvaromaltrain** [camenduru/stable-diffusion-webui-colab#96]
Hopefully it will be added

**Comment by camenduru** [comment]
please give me the link

**Comment by alvaromaltrain** [comment]
Here it is https://huggingface.co/darkstorm2150/Protogen_Nova_Official_Release/blob/main/model.ckpt

**Comment by camenduru** [comment]
thanks @alvaromaltrain ❤
