### ISSUE TITLE
Extensions not showing and not working, 

### ISSUE THREAD

**Issue by jabbasami** [camenduru/stable-diffusion-webui-colab#98]
Please i have a problem when installing an extension it's seems not to appear and other extensions are not working ? in the 2.1 version works just fine but not the 1.5

**Comment by camenduru** [comment]
please share your colab link

**Comment by jabbasami** [comment]
this one: 

https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/anything_3_webui_colab.ipynb?authuser=3 
when i restart my colab after installing an extension for example it suppose to show up but i get this error?
any solution please ?
and in the 2.0version it seems to work and no problems with extension 

![image_2023-02-14_162539487](https://user-images.githubusercontent.com/66371114/218781801-4d9d7eb7-c70c-48bd-b9b0-4e1442c349f3.png)

**Comment by jabbasami** [comment]
Any answers ? <3

**Comment by etherealxx** [comment]
> Any answers ? <3

give me the extension you've used

**Comment by jabbasami** [comment]
Animator

**Comment by camenduru** [comment]
Hi @jabbasami 👋 please give the extension link

**Comment by jabbasami** [comment]
https://github.com/Animator-Anon/animator_extension this is the link

**Comment by jabbasami** [comment]
but why does it work locally just fine??? likr all the extensions aren't even the checkpoit merger,

**Comment by camenduru** [comment]
please use with v2.0
